### ISSUE TITLE
95% confidence limits in plot of baseline hazard

### ISSUE THREAD

**Issue by sambrilleman** [CecileProust-Lima/lcmm#1]
I am wondering whether it is possible to include confidence limits in the plot of the baseline hazard, for `Jointlcmm` objects?

For example, could 95% confidence limits be added somehow to the example below?

In the documentation, I couldn't find anywhere explaining how to do it...

Thanks in advance.

--------- start reprex -----------

```
library(lcmm)

m3 <- Jointlcmm(fixed= Ydep1~Time*X1,mixture=~Time,random=~Time,
classmb=~X3,subject='ID',survival = Surv(Tevent,Event)~ X1+mixture(X2),
hazard='3-quant-splines',hazardtype='PH',ng=3,data=data_lcmm,
B=c(0.7576, 0.4095, -0.8232, -0.2737, 0, 0, 0, 0.2838, -0.6338, 
2.6324, 5.3963, -0.0273, 1.3979, 0.8168, -15.041, 10.164, 10.2394, 
11.5109, -2.6219, -0.4553, -0.6055, 1.473, -0.0383, 0.8512, 0.0389, 
0.2624, 1.4982))

plot(m3,which="baselinerisk",bty="l")
```

--------- end reprex -----------

**Comment by CecileProust-Lima** [comment]
Dear Sam, 
we did not included 95%CI in the plot function for the baseline risk. 
However, we implemented a function to compute cumulative incidence function for any profile of covariates specified by the user. In this function, you can obtain 95% CI computed using MC method with draws=T option. For instance:
ci00 <- cuminc(m3,time=seq(0,20,1),draws=TRUE,ndraws=1000)
plot(ci00)
Hope it helps !
Cécile
