### ISSUE TITLE
How to avoid negative predicted mean trajecotry

### ISSUE THREAD

**Issue by fliang1976** [CecileProust-Lima/lcmm#101]
Dear Sir or Madam,
I posted two questions just now. I think I'd better ask my following question in a new post. I tried to examine the trajectory of BMI and controlled for age and gender in the model (I used hlme function). When I drew the Class−specific mean predicted trajectory, I found both negative and extremely high predicted mean BMI within the time range I specified (based on actual follow-up period). Do you know what I can do to avoid negative predicted mean BMI? Thank you!

Best Regards,
Feng Liang

**Comment by CecileProust-Lima** [comment]
Dear Feng, 
this is very weird and must have an explanation. If you have dropout, one explanation might happen in classes with a high level of dropout when you extrapolate the trajectory sometime later. But there might be many other explanations. You have to look at the data and the model very precisely. 
Good luck
Cécile

**Comment by fliang1976** [comment]
Dear  Dr Cécile,
Thank you so much for advice! I will examine both the model and data to find out the reason.
