### ISSUE TITLE
how I can fix Error in UseMethod("simulate") ?

### ISSUE THREAD

**Issue by hundes** [CecileProust-Lima/lcmm#102]
Dear Dr. Cecile,
I trust you are doing well.
here is my question based on simulation.

when I do simulation like as follow, it said 

m2 <- hlme(Y~Time*age,mixture=~Time,random=~Time,classmb=~X2+X3,subject='ID',ng=2,data=full_data,B=c(0.11,-0.74,-0.07,20.71,29.39,-1,0.13,2.45,-0.29,4.5,0.36,0.79,0.97))
summary(m2)

dsim1 <- simulate(m2, times=c(0,3,0.5,0), n=300, tname="Time",Xbin=list(X1=0.5, X2=0.5), Xcont=list(age=c(1,1)))

Error in UseMethod("simulate") : 
  no applicable method for 'simulate' applied to an object of class "hlme"
Calls: simulate

**Comment by VivianePhilipps** [comment]
Hello,

the simulate function is only available on the github version of the lcmm package and on the master branch. If you are using another branch or the CRAN version, the method does not exist for hlme models.
Could you please check the version you are using?

Viviane

**Comment by hundes** [comment]
Thank you. I hope that might be my problem. will check it
