### ISSUE TITLE
how imputation data is pooled in jointlcmm function in LCMM package?

### ISSUE THREAD

**Issue by hundes** [CecileProust-Lima/lcmm#103]
Dear Dr. Cecile,
I am Hunde from Stellenbosch University, South Africa.
I am working in R to impute missing data using MICEMD package. I have one imputed datasets that I would like to pool the results of. My original data is analyzed using jointlcmm  function in lcmm . please Dear Dr. Cecile, can assist me how I can pool the results from jlcmm or lcmm to produce one result?
Here is my syntax i used to pool the results:

Jlcmm1<-with(res.mice,expr=Jointlcmm(Y ~ Time*Sex+Education,random = ~ Time, subject = 'ID', survival = Surv(Tevent, Event) ~  Education + Sex, hazard = "Weibull"))

Be patient, Jointlcmm is running ... 
Error in Jointlcmm(Y ~ Time * Sex + Education, random = ~Time, subject = "ID",  : 
  The argument data should be specified and defined as a data.frame  

Thank you in advance

**Comment by CecileProust-Lima** [comment]
Hi, 
we have never use MICEMD with Jointlcmm or any other software to aggregate results from jointlcmm of other functions of lcmm. I am not sure our specification of the model would work, but this can be explored. 
Regarding your problem, it looks like jointlcmm does not have any dataset to work on, or this dataset is not a data.frame. 
We had trouble in the past with dplyr outputs but this has been solved in the last version of lcmm. If you do use the last version, maybe the specification of our functions is not compatible with those of micemd. 
Cécile

**Comment by hundes** [comment]
Thank you very much for your kind response. 
In my case it works when I used single imputation method but the problem is when I used multiple imputation for missing data. it pop-ups the previous error. I will look into it may be further. 
Thank u again
Hunde
