### ISSUE TITLE
Error in data.frame(unique(IND), classif, ppi) : Parameter values mean different lines: 500, 0

### ISSUE THREAD

**Issue by YanzeCui** [CecileProust-Lima/lcmm#106]
Recently I was learning how to use the LCMM package, and when I tested multlcmm functionality using the Paquid dataset, an error occurred as described in the question.

paquid$age65 <- (paquid$age-65)/10
mult1 <- multlcmm(MMSE+BVRT~age65+I(age65^2)+CEP+male,random=~age65+I(age65^2),
                  subject="ID",link=c("5-quant-splines","4-quant-splines"),data=paquid)
m1S <- mpjlcmm(longitudinal=list(mult1),subject="ID",ng=1,data=paquid,
               survival=Surv(age_init,agedem,dem)~1)
#####     Until this point, the script works fine
mult2 <- multlcmm(MMSE+BVRT~age65+I(age65^2)+CEP+male,random=~age65+I(age65^2),
                  subject="ID",link=c("5-quant-splines","4-quant-splines"),ng=2,
                  mixture=~age65+I(age65^2),data=paquid,B=random(mult1),maxiter=0)
#####                      Error in data.frame(unique(IND), classif, ppi) : Parameter values mean different lines: 500, 0 
Is there anyone who can help me solve this problem?  Thanks.

**Comment by VivianePhilipps** [comment]
Hello,

I think there was a computation problem in the posterior probabilities. Maybe you get some infinite values.
I changed the code (in the master branch only) so that this will not cause an error anymore.
Thank you for the feedback.

Viviane

**Comment by YanzeCui** [comment]
Thank you so much for your help.
