### ISSUE TITLE
Correlation term between intercept & coefficients

### ISSUE THREAD

**Issue by sss203** [CecileProust-Lima/lcmm#111]
Does the LCMM package allow for a correlation term between intercept and coefficients? I believe the 'cor' argument in the _hlme_ call is for modeling correlations between observations - this is different?

**Comment by CecileProust-Lima** [comment]
Hi, 
I don't understand what "correlation term between intercept and coefficient" means. If this is the correlation between a random intercept and a random slope, then yes, this is what we assume by default. The independence assumption is obtained with idiag=T argument. 
The cor argument is something else: this is to add an autocorrelation process to the model. With cor=AR(vartime), you assume an exponential decay correlation between vartime measures. With cor=BM(vartime), you assume a Brownian motion process with vartime, the time variable.
I hope this helps
Cécile
