### ISSUE TITLE
Multivariate latent class growth analysis - results depending on sequence of outcome variables

### ISSUE THREAD

**Issue by DrLundRasmussen** [CecileProust-Lima/lcmm#112]
Hi!

I am attempting to use the _multlcmm_ function for a multivariate latent class growth analysis for compositional data. 

In short, I have a dataset with 3 (dependent) continues outcome variables. These are called _ilr1_, _ilr2_ and _ilr3_.
Each variable has 7 repeated measurements (i.e. all weekdays from Monday to Sunday). This variable is called _weekday_num_.

I am running this script to conduct my analysis:

multlcmm(ilr1+ilr2+ilr3  ~ weekday_num , random = ~ weekday_num, subject = "ID", 
                      data = d3_v2, link = c("linear", "linear", "linear"),
                      ng = 2, mixture = ~weekday_num)

However, the fixed effect estimated for group 1 and group 2 differs depending on the sequence of the outcomes variables. Does this mean that not all outcome variables are considered simultaneously when running the function? 

Thanks you for the help (and for taking the time to develop this highly maintained package!).

Best,
Charlotte

**Comment by VivianePhilipps** [comment]
Hi,

all outcomes specified in the model are used simultaneously to estimate the model's parameters. So you should get completely equivalent models whatever the order of the outcome variables. Only the order of the outcome specific parameters will differ (the measurement errors and the parameters called Linear 1 and Linear 2 in your case).
If you get different results, one model may not have converged properly or have converged to a local maximum. We recommend using the gridsearch function to ensure that we reach the global maximum. The results obtained by the 2 gridseach should give the same results.

Best,

Viviane
