### ISSUE TITLE
Questions on Jointlcmm

### ISSUE THREAD

**Issue by shanpengli** [CecileProust-Lima/lcmm#113]
Hi, I can run Jointlcmm() using your example data and make up the Event variable with competing risks events:

data_lcmm$Event <- sample(c(0, 1, 2), 1678, replace = TRUE)
m2 <- Jointlcmm(fixed= Ydep1~Time*X1,random=~Time, ng = 1, subject='ID',
                survival = Surv(Tevent,Event)~X1+X2,
                hazard="Weibull",hazardtype="PH", data=data_lcmm)

When I was looking at the survival fixed effects, I found that they are the same across all causes of events. Do you think your function can relax this assumption and make the fixed effects cause-specific, besides the baseline hazard?

Thanks.

**Comment by VivianePhilipps** [comment]
Hi,

you can get cause-specific effects by using 'cause' in the survival formula. If you want both X1 and X2 with cause-specific effect, the syntax is :
survival = Surv(Tevent,Event)~cause(X1)+cause(X2)

Best, 
Viviane
