### ISSUE TITLE
Jointlcmm issue identifying latent classes, compared to hlme command

### ISSUE THREAD

**Issue by BrendanHallam** [CecileProust-Lima/lcmm#116]
Dear Cecile and Viviane,

I hope you are both well. I have fitted a number of latent class models using the hlme command:

```
m1 <- hlme(sbp ~ BPageCE+I(BPageCE^2),random =~ BPageCE+I(BPageCE^2), subject = 'xtID', data = BPtrajSample)
m3 <- hlme(sbp ~ BPageCE+I(BPageCE^2), random =~ BPageCE+I(BPageCE^2), subject = 'xtID', data = BPtrajSample, ng = 3, mixture=~BPageCE+I(BPageCE^2), B=m1) 

data_pred0 <- data.frame(BPage=seq(65,100,length.out=50)) 
data_pred0$BPageCE <- (data_pred0$BPage - mean(data_pred0$BPage, na.rm = TRUE))

predG1 <- predictY(m1, data_pred0, var.time = "BPage", na.rm = TRUE)
predG3 <- predictY(m3, data_pred0, var.time = "BPage", na.rm = TRUE)
```

To produce results like this (code above repeated for 6 latent class models):

![image](https://user-images.githubusercontent.com/101123979/158366088-74b7e6f1-431d-44a3-83f9-c8e5b4be3622.png)

**Jointlcmm**

Once I move onto my next step which is to use the Jointlcmm command to investigate  SBP latent classes (longitudinal component) and risk of dementia (survival component), using a similar process of commands:

```
jmm1 <- Jointlcmm(sbp ~ BPageCE+I(BPageCE^2), random =~ BPageCE+I(BPageCE^2), survival = Surv(TIME, DEMind)~ 1, hazard = "Weibull", subject = 'xtID', data = BPtrajsample2)

jmm3 <- Jointlcmm(sbp ~ BPageCE+I(BPageCE^2), random =~ BPageCE+I(BPageCE^2), mixture=~BPageCE+I(BPageCE^2), survival = Surv(TIME, DEMind)~ 1, hazard = "Weibull", subject = 'xtID', ng = 3, B=jmm1, data = BPtrajsample2)

data_pred3 <- data.frame(BPage=seq(65,100,length.out=50)) 
data_pred3$BPageCE <- (data_pred3$BPage - mean(data_pred3$BPage, na.rm = TRUE))

jmm3.pred <- predictY(jmm3, data_pred3, var.time = "BPage", na.rm = TRUE)

```

![image](https://user-images.githubusercontent.com/101123979/158367198-7c7c0236-1310-4683-999e-748a849bd2d6.png)

![image](https://user-images.githubusercontent.com/101123979/158367207-55441855-5457-4c86-bf91-3c3e33dd229e.png)

The base model between hlme and jointlcmm (g=1) is the same. However, when I introduced more latent classes (in the example above, 3 latent classes): A) the classes are not similar to the hlme commands and B) 100% of the subjects are assigned to g=1 (red line) and two more unfeasible groups are formulated (black and green lines). I assume there is something I am entering incorrectly for the code. Whilst understanding that the latent classes wouldn't be exactly the same from the Jointlcmm and hlme command, I thought that they should both be fairly similar and wondered if there was a way to correct the mistake I have made with the jointlcmm command. 

I am sorry if a similar question has been answered but I could not find it when looking through previous questions raised on this forum. 

Any support/feedback would be very much appreciated, thank you.

Best wishes,

Brendan

**Comment by VivianePhilipps** [comment]
Hi Brendan,

you used correctly the Jointlcmm function, but the jmm3 model with jmm1 as starting values converged to a local solution. To get the global solution we recommend to use the gridsearch function (ie multiple starting points). Please see issues #25 or #26 for more details answers.

Best,

Viviane

**Comment by BrendanHallam** [comment]
Hi Viviane,

Thank you very much for your response - it was very helpful. I just have a further question if that is okay.

I have used the gridsearch function with slightly more success in terms of producing more accurate trajectories as latent classes; however, the number of people assign to classes (other than class 1) are still 2% or less. 

Would you recommend to increase the value for the rep = x and maxiter = x, as suggested on top of page.44 in the _lcmm: Extended Mixed Models Using Latent Classes and Processes in R_ paper?

Additionally, within the same paper, for the mj3b model (page.43) how did you decide on how many and what arbitrary values to choose for the initial values of the "binit" model. Example below from the  _lcmm: Extended Mixed Models Using Latent Classes and Processes in R_ paper

**Three Class:** 
```
R> Binit <- rep(0, length(mj2$best) + 6)
R> Binit[c(2, 5:10, 12, 13, 15, 16, 18, 19:(length(Binit)))] <- mj2$best
R> Binit[c(1, 3, 4, 11, 14, 17)] <- c(0, 0.11, 4, 70, 0, 0)
R> mj3b <- Jointlcmm(normMMSE ~ poly(age65, degree = 2, raw = TRUE) + CEP,
+ mixture = ~ poly(age65, degree = 2, raw = TRUE),
+ random = ~ poly(age65, degree = 2, raw = TRUE),
+ survival = Surv(age_init, agedem, dem) ~ CEP + male,
+ hazard = "Weibull", subject = "ID", data = paquidS, ng = 3, B = Binit)
```

**Four Class:**
```
R> Binit <- rep(0, length(mj3b$best) + 2 + 3 + 1)
R> Binit[c(1, 2, 4:7, 10:15, 17:19, 21:23, 25:length(Binit))] <- mj3b$best
R> Binit[c(3, 8, 9, 16, 20, 24)] <- c(0, 0.1, 10, 60, 5, -10)
R> mj4b <- Jointlcmm(normMMSE ~ poly(age65, degree = 2, raw = TRUE) + CEP,
+ mixture = ~ poly(age65, degree = 2, raw = TRUE),
+ random = ~ poly(age65, degree = 2, raw = TRUE),
+ survival = Surv(age_init, agedem, dem) ~ CEP + male,
+ hazard = "Weibull", subject = "ID", data = paquidS, ng = 4, B = Binit)
```

Once again, thank you very much for your feedback already and any further advice would be very much appreciated, thank you! 

Best wishes , 

Brendan

**Comment by VivianePhilipps** [comment]
Hi,

you can try to increase rep and maxiter to explore more widely the space of parameters. Maybe the global maximum is not reached yet.
Or you may not have specified a model flexible enough (in the class specific part) to see any heterogeneity. 

For the initial values in the JSS example, we use the estimations of the 2 class model to specify the parameters of classes 2 and 3. For the class 1, we used more or less arbitrary values. You see in model mj2 that the weibull parameters are about 0.1 and 5, so we choose similar values for the weibull parameters of the additional class (class 1). Similarly, the intercepts of the longitudinal submodel  are 59 and 63, so we stay in the same scale and provide value 70 for class 1.
There is no correct or incorrect way to choose values, but they have to make sense for your data.

Best,

Viviane
