### ISSUE TITLE
Predictive metrics and time-dependent ROC curves

### ISSUE THREAD

**Issue by jegubo** [CecileProust-Lima/lcmm#118]
Dear Cécile,

I am Jesús Gutiérrez, from the University of Santiago de Compostela. I am working with your package, concretely with the **Jlcmm function** to adjust joint latent class models, and I have some questions about how predictive capability of these models can be measured. 

In your paper "Estimation of Extended Mixed Models Using Latent Classes and Latent Processes: The R Package lcmm" (2015), some predictive metrics are described. Within this section, it is said that "Further predictive accuracy measures can be computed by using timeROC on individual dynamic predictions computed by dynpred from a Jointlcmm object". 

**My questions are:**

- how can I use timeROC to obtain predictive metrics?
- is it possible to obtain a time-dependent ROC curve; maybe working with this package and the predictions from dynpred? It can be very useful to visually compare the predictive ability of two models like an extended Cox model and a joint latent class model. 

Thank you in advance for your help.

**Comment by CecileProust-Lima** [comment]
Dear Jesus, 
the lcmm package provides the individual predictions from a landmark and up to a horizon specified by the user. The vector of these predictions for an external sample can be included as the marker to be tested in packages that compute predictive accuracy measures in presence of censoring. This is the case for timeROC in which the vector of predicted probabilities of the event can be specified in the marker= argument. Please refer to the timeROC package for further details. 
Notice that pec R package and riskRegression R package also provide tools for predictive accuracy measures in presence of censoring. 
Cécile
