### ISSUE TITLE
Group-Based Multi-Trajectory Modeling with lcmm Package

### ISSUE THREAD

**Issue by Smilinglion** [CecileProust-Lima/lcmm#119]
Hello Cecile, and thank you for your work on the lcmm package!

I was wondering whether group-based multi-trajectory modeling similar the one described by Nagin and coauthors (2018)  can be implemented with the lcmm package? That is, a joint analysis of multiple variables that allows to see the trajectory of each of these variables over time (I’m not sure the function multlcmm  is implementing similar features).

Nagin, D. S., Jones, B. L., Passos, V. L., & Tremblay, R. E. (2018). Group-based multi-trajectory modeling. Statistical Methods in Medical Research, 27(7), 2015-2023.

**Comment by VivianePhilipps** [comment]
Hello,

to model different outcome over time, each having its own trajectory, we have the mpjlcmm function.
To use it, you define the structure of each submodel with the  hlme or lcmm function, and then you combine them using the mpjlcmm function. The latent classes will be estimated using all outcomes, so each class will be associated to a particular profile of trajectories.

You have an example in the help page of the function (example 2). It includes also a time-to-event model, but this is not necessarily required. 

Best,

Viviane

**Comment by Smilinglion** [comment]
Hi Viviane,

And thank you very much for your reply.
Much appreciated.

Bonne journée!
