### ISSUE TITLE
Pooling results from multiple imputation

### ISSUE THREAD

**Issue by martinschlund** [CecileProust-Lima/lcmm#120]
Dear Cecile and Viviane

I am doing a model with lcmm() where some of my explanatory variables have missing data. To account for that, I want to do multiple imputation using the mice-package. However, lcmm does not fit into the workflow of mice, so I have had to fit a model separately for each imputed dataset. 
Now I am stuck trying to summarise the results from the models. I'm interested in whether one particular explanatory variable is associated with my outcome, so I want a pooled estimate for the effect and a p-value for that estimate. 
I saw in a response to a previous question (here: [https://github.com/CecileProust-Lima/lcmm/issues/70]) that this can be calculated easily but I must admit that doing so surpasses my skills and knowledge. I have searched around and haven't found information on how to do this. 

Do you have a line of code showing how to pool the results manually or can you point me to a resource where I can learn? 

Best regards

Martin

**Comment by VivianePhilipps** [comment]
Hello Martin,

to pool the results, we use the Rubin's formula to get the variance of the pooled parameters.

Say you have 3 imputed datasets, so you have 3 estimated models (m1, m2, m3).
Your final parameters will simply be the mean of the 3 estimates. With the lcmm functions you get it with :
`estim <- cbind(estimates(m1), estimates(m2), estimates(m3))`
 `estim_pool <- apply(estim,1,mean) # the mean parameters
`
The variance of estim_pool is a combination of the variances of each model and of the empirical variances of the 3 estimates :

`M <- 3 # number of imputations`
`v1 <- vcov(m1)  # variance of the first model's parameters`
`v2 <- vcov(m2)`
`v3 <- vcov(m3)`

`U <- 1/M*(v1+v2+v3) # mean of the 3 variances`

`B <- 1/(M-1) * ((estim[,1]-est_pool)%*%t(estim[,1]-est_pool)+
               (estim[,2]-est_pool)%*%t(estim[,2]-est_pool)+
               (estim[,3]-est_pool)%*%t(estim[,3]-est_pool)) # empirical variance
`

`var_pool <- U + (1 + 1/M) * sum(diag(B%*%solve(U)))/length(estim_pool)*U # the variance of estim_pool`

Now you have your final parameters estim_pool and the associated variance var_pool, so you can make the inference based on that values.

Best,

Viviane
