### ISSUE TITLE
Covariance Pattern Growth Mixture Models

### ISSUE THREAD

**Issue by papinisan** [CecileProust-Lima/lcmm#121]
Hi all, 
I have been using your lcmm package to model trajectories. This article suggests Covariance Pattern Growth Mixture Models over LGMM or LCGA in some scenarios(https://psycnet.apa.org/doiLanding?doi=10.1037%2Fmet0000456). As I understand it, in the CPGMM approach there are no random effects and class-specific covariance structures are permitted. Is this possible in the lcmm package? Would it be equivalent to fitting an LCGA and setting nwg = TRUE?
Thanks,
Santiago

**Comment by CecileProust-Lima** [comment]
Dear Santiago, 
thank you for this reference. lcmm package does not include the Covariance Pattern Growth Mixture Models, it relies on random effects to structure the variance-covariance matrix of the observations. However, lcmm does not necessarily constrain the variance matrix to be equal across classes: unequal variance across classes can be specified using a proportionality assumption (option nwg=T). 
Best
Cécile
