### ISSUE TITLE
Estimating a longitudinal model with varying class membership

### ISSUE THREAD

**Issue by loxavia** [CecileProust-Lima/lcmm#124]
I am trying to estimate a model of physical activity that includes e.g.,  motivation, stress, sociality as predictors of number of steps, the data is measured every month for say 10 months

Model1 <- hlme(step_count ~ motivation + stress + sociality, random =~  location, subject = 'User', ng=3,  mixture=~ motivation + stress + sociality, data = Data ,  B= precious_iteration_ng1)

I assume that a person could have a trajectory that could be something like e.g., active, moderate, inactive. But I also assume that at each time point a person can vary e.g., active at t1, moderate at t2 and back active at t3. Does the library computes probabilities at each time point ? or is there any way I can. The current pprob outputs assigns each user a single class over all time points, which is of course good too.

Second question am I specifying the model right ?

**Comment by VivianePhilipps** [comment]
Hello,

the lcmm package does not allow dynamical latent classes. As you noticed, the subjects are classified from all their observations.
However, with flexible time functions in the fixed and mixture parts of the model, you could estimate non monotonous trajectories. So you could get, for example, a class with decreasing activity over the first time points and increasing activity afterwards.
A subject will still be assigned to a single class, but the class will be defined by a time varying profile.

Regards,

Viviane

**Comment by loxavia** [comment]
Thank you Viviane, I see, still, I think assignment overall as you do is great, but also if there is another output that assign the person to a class at each time point based on their data at such time-point will be a great option.
