### ISSUE TITLE
Mean age of classes

### ISSUE THREAD

**Issue by Jonasqsl** [CecileProust-Lima/lcmm#125]
Hi all,

I am an MSc student who is currently undertaking a dissertation on cognitive decline over time. I have used the hlme function of this package and have fitted a model with my predictor variable as a fixed effect, time as random effect, and baseline age as a class indicator (classmb). 

In analysing my data it would be very interesting for me to see the average baseline age of each class. Is this something that is possible using this package and how would I go about it? I have not been able to find (or maybe just not understand) anything about it in the package documentation, google, or prior topics here.

Thank you in advance!

Jonas

**Comment by VivianePhilipps** [comment]
Hi Jonas,

you will find the classification in the output $pprob of the hlme model. You can then merge it with your dataset to easily cross the information. 
Here is an example :

#- estimate the model
`m2b<-hlme(Y~Time*X1,mixture=~Time,random=~Time,classmb=~X2+X3,subject='ID',
         ng=2,data=data_hlme,B=c(0.11,-0.74,-0.07,20.71,
                                 29.39,-1,0.13,2.45,-0.29,4.5,0.36,0.79,0.97))`

#- check the output pprob
`head(m2b$pprob)`

#- merge the classification and the data
`d <- merge(data_hlme, m2b$pprob[,1:2])`
`head(d)`

#- compute the mean of X3 for subjects in class 1
`mean(d$X3[which(d$class==1 & !duplicated(d$ID))])`


Viviane

**Comment by Jonasqsl** [comment]
Amazing. It has been a pleasure working with your R package for my dissertation. Thank you, Viviane!
