### ISSUE TITLE
Dear author, I met this error when doing lcmm

### ISSUE THREAD

**Issue by qifasong** [CecileProust-Lima/lcmm#126]
Numerical problem by computing fn 
          value of function is : NaN 

My code: lcmm( BMI~SBP+height,subject='No',data=D,random=~weight,maxiter=5): an error.
lcmm( BMI~SBP*height,subject='No',data=D,random=~weight,maxiter=4):  It is OK.
hlme( BMI~SBP*height,subject='No',data=D,random=~weight,maxiter=100):  It is ok

NA values are removed in the data. 

The running is OK by hlme, but it is stopped when doing iteration at the 5th round. It is ok at 4th.

Thank you

**Comment by VivianePhilipps** [comment]
Hello,

the values found at the 5th iteration are causing problems and the likelihood cannot be computed. So the algorithm stops.
You can try with different initial values (specified in argument B), using for example the estimated parameters of the hlme model.
The default initial values seem here not to be a good starting point.

Best,
Viviane
