### ISSUE TITLE
Predictions made by the predictY function sometimes result in NA

### ISSUE THREAD

**Issue by Apprentice2** [CecileProust-Lima/lcmm#128]
Dear author,

I used the following commands to create my model, m4g.

--------------------------------

m1 <- lcmm(Index ~ poly(age, degree = 2, raw = TRUE), random = ~ age, subject = "ID", data = data,ng=1,link = "4-quant-splines")
m4g<-gridsearch(lcmm(Index ~ poly(age, degree = 2, raw = TRUE), random = ~ age,  mixture = ~ poly(age, degree = 2, raw = TRUE),subject = "ID",   data = data,ng=4,link = "4-quant-splines",maxiter=1000),rep = 30, maxiter = 15, minit = m1)

--------------------------------

Applying the summary function to the resulting m4g yielded the output of the attachment.
[summary.txt](https://github.com/CecileProust-Lima/lcmm/files/9504212/summary.txt)

Then, when the new data (data_pred ) is predicted by the predictY function in the model m4g, it returns NA at a specific age (ex. age=50) as shown below. This happens at multiple values of age, is there a solution?

--------------------------------

> data_pred <- data.frame(age=c(40,50))
> pred_f <- predictY(m4g, data_pred, var.time = "age")
> pred_f
$pred
     Ypred_class1 Ypred_class2 Ypred_class3 Ypred_class4
[1,]    -2.907409     2.521853    -2.911654    -2.911618
[2,]           NA           NA    -3.043962    -3.043960

$times
  age
1  40
2  50

attr(,"class")
[1] "predictY"

--------------------------------

**Comment by CecileProust-Lima** [comment]
Hi, 
I don't have examples that replicate your issue. Do you have the same issue if you recenter and standardize your age? For instance doing agebis = (age - min(age) / 10)
Cécile

**Comment by Apprentice2** [comment]
Thank you for your advice.
I have tried standardizing and centering  the data as you suggested, but I still have the same problem, which seems to occur when I use the splines as the link function.

**Comment by VivianePhilipps** [comment]
Hi,

this should not be a problem if some subjects are only measured once.
In your summary I see that the first node (at -3.321928) of the spline link function is very close to the minimum value (-3.322). This can cause numerical problems. Did you try with other interior nodes?

Viviane

**Comment by Apprentice2** [comment]
Dear Viviane

Thank you for your advice! I followed your advice and changed the interior nodes with intnodes option and the predictY function no longer returns NA. Thank you very much!
