### ISSUE TITLE
predict latent classes without shift in classes

### ISSUE THREAD

**Issue by miiroth** [CecileProust-Lima/lcmm#129]
Hi everyone!

Currently I am working on a project studying relationship satisfaction across 10 years with the aim of identifying latent classes in those trajectories.

So far I used hlme() and then gridsearch() command to identify those classes and found a satisfying model with 4 classes. In a next step the goal is to predict class membership from several predictor variables (e.g. communication skills, personality traits). 
In doing so, the goal is that the classes remain stable when adding predictors to the model, i.e. no shifts/changes in classes when adding predictors. So far I found appropriate methods in Mplus - the BCH method - but so far did not manage to implement it in R using the lcmm package. I tried with the "classmb =~ " command but this led to shifts in classes.

Does anyone have recommendations on this? 

Thank you 
Michelle

**Comment by CecileProust-Lima** [comment]
Hi Michelle, 
thank you for your question. We are currently implementing easy-to-use methods to do this correctly. In the meantime, here is a solution: you can indeed use classmb but you need to fix the latent class model as you suspected in your post to avoid any shift. 
Here is how I do it in a simple example: 


Estimation of the latent class model without classmb
`m1 <- hlme(Y ~ Time,random=~ Time,subject='ID',ng=1,data=data_hlme)
set.seed(1111)
m2 <- hlme(Y ~ Time,mixture=~ Time,random=~Time,subject='ID',
          ng=2,data=data_hlme,B=random(m1))
`
I have my estimates: 
`Esti <- m2$best
`
Posterior identification of predictors (without shifting the classes). Example with 2 covariates:
I need to define the new vector of initial values that includes the np covariates in classmb for ng classes: 
`ng <- 2
np <- 2
Binit <- c(Esti[1:(ng-1)],rep(0,np*(ng-1)),Esti[-(1:(ng-1))])
`
I fix the parameters of the latent class model, except the classmb model (and its intercept)
`FixedParms <- ((np+1)*(ng-1)+1):length(Binit)
`
I check that this is what I want: 
`Binit[FixedParms]
`
I recall the same latent class model with the classmb I want in addition + I only estimate the parameters of the classmb model

`m2POST <- hlme(Y ~ Time,mixture= ~ Time,random= ~ Time,subject='ID', classmb= ~ X2+X3,
               ng=2,data=data_hlme,B=Binit, posfix=FixedParms)
`
I estimated 3 parameters corresponding to the intercept and 2 covariates for latent class 1 with latent class 2 in reference
`summary(m2POST)
`


The variance might be slightly underestimated in small samples as this technique neglects the uncertainty on the parameters. This will be accounted for in the next lcmm version. In the meantime, bootstrap technique can be done easily on small samples. On relatively large, our current simulations show that underestimation of the variance is this is not very important. 
I hope this is clear enough and will help you!
Cécile

**Comment by miiroth** [comment]
Dear Cécile

Thank you so much for your detailed answer and explanation!

I was working on it and trying to implement it, however, some problems occur. 

I was setting up the models with the gridsearch() command, here my code:

set.seed(2002)

gmm1 <- hlme(fCSI ~ time, subject = "CoupleID", random=~1 + time, ng = 1,
               data = data_long)
gmm2 <- gridsearch(rep = 100, maxiter = 10, minit = gmm1_2,
                     hlme(fCSI ~ time, subject = "CoupleID", random=~1 + time,
                          ng = 2, data = data_long, mixture = ~ time, nwg=T))
gmm3 <- gridsearch(rep = 100, maxiter = 10, minit = gmm1_2,
                     hlme(fCSI ~ time, subject = "CoupleID", random=~1+time,
                          ng = 3, data = data_long, mixture = ~ time,
                          nwg=T))
gmm4 <- gridsearch(rep = 100, maxiter = 10, minit = gmm1_2,
                     hlme(fCSI ~ time, subject = "CoupleID", random=~1+time,
                          ng = 4, data = data_long, mixture = ~ time,
                          nwg=T))

gmm5 <- gridsearch(rep = 100, maxiter = 10, minit = gmm1_2,
                     hlme(fCSI ~ time, subject = "CoupleID", random=~1+time,
                          ng = 5, data = data_long, mixture = ~ time,
                          nwg=T))

this led to the model with 4 classes as the best one. I then entered this model into the code you provided before:

set.seed(1111)
m2 <- gmm4

Esti <- m2$best 
Esti

ng <- 4
np <- 2
Binit <- c(Esti[1:(ng-1)],rep(0,np*(ng-1)),Esti[-(1:(ng-1))]) 

FixedParms <- ((np+1)*(ng-1)+1):length(Binit) 
Binit[FixedParms] 

m2POST <- hlme(fCSI ~ time, mixture=~ time, random=~ 1+time, subject='CoupleID',
               classmb =~ afDCI_tot + amDCI_tot, ng=4, data = data_long, B=Binit, posfix=FixedParms) 
summary(m2POST)

However, with this i always run in the following problem:
"Fehler in hlme(fCSI ~ time, mixture = ~time, random = ~1 + time, subject = "CoupleID",  : 
  Indexes in posfix are not correct"

Do you have any advide on this? I am quite new to applying these models so I am not sure if there is a mistake in my model elsewhere which could cause this problem?

Thank you so much and best regards
Michelle

**Comment by VivianePhilipps** [comment]
Hi,

The model in your second step should be exactly the same as the one used in the first step, excepted for the classmb part. Here you missed the nwg=TRUE command in the m2POST model. 
The rest looks good :)

Viviane

**Comment by miiroth** [comment]
Hi Viviane

worked perfectly now, thank you so much!

Best
Michelle
