### ISSUE TITLE
How do we get increasing thresholds parameters for ordinal markers?

### ISSUE THREAD

**Issue by ivonnerenteria** [CecileProust-Lima/lcmm#13]
Dear Dr. Proust,

When I  replicated the following routine in the section 6.3 lcmm, 
`mord0 <- lcmm(CESD ~  age65*male, random = ~-1, subject = 'ID', link = ‘thresholds’, data = paquid)`
the list of thresholds parameters is not strictly increasing.

                    coef      Se    Wald  p-value
thresh. parm1         -0.99852  0.08843  -11.291  0.00000
thresh. parm2          0.56689  0.02055   27.591   0.00000
thresh. parm3         0.49852  0.01874   26.597   0.00000
thresh. parm4         0.45676  0.01793   25.469   0.00000
...
thresh. parm20       0.27593  0.02446  11.282   0.00000
thresh. parm21       0.25844  0.02555  10.115   0.00000
thresh. parm22       0.20718  0.02655   7.803    0.00000
...
thresh. parm48       0.30197  0.14983   2.015   0.04386
thresh. parm49       0.35615  0.17626   2.021   0.04332
thresh. parm50       0.45527  0.22627   2.012   0.04421

with thanks for any guidance you can offer,

Ivonne Rentería

**Comment by CecileProust-Lima** [comment]
The parameters that are estimated are not directly the successive ordinal thresholds. Only the first parameter (-0.99852) is the first threshold. Then, I estimate the square root of the increment to ensure that the thresholds are increasing (so the second threshold is -0.99852+0.56689^2). 
You can find details about the specification of the model with thresholds in the JSS paper (page 5). 
If you want to directly obtain the hierarchy, you can find it in the value estimlink, i.e., mord0$estimlink. 
Cécile

**Comment by ivonnerenteria** [comment]
Thanks a lot Dr. Proust for your clear answer.
