### ISSUE TITLE
Error with mpjlcmm: "No classmb should be specified in the longitudinal models"

### ISSUE THREAD

**Issue by Smilinglion** [CecileProust-Lima/lcmm#131]
Hello,
I'm using the mpjlcmm function and getting an error message, and  I do not understand/know how to fix it; "No classmb should be specified in the longitudinal models". Your help is much appreciated.

> mult1 <- multlcmm(Y1 + Y2 + Y3 + Y4 ~ poly(year, degree = 2, raw = TRUE) + X1 +  X2, random = ~1, subject = "id", ng = 1, data = dataset)
> mult3 <- multlcmm(Y1 + Y2 + Y3 + Y4 ~ poly(year, degree = 2, raw = TRUE) + X1 +  X2, random = ~ 1,  mixture = ~ poly(year, degree = 2, raw = TRUE)+ X1 +  X2, subject = "id",  ng = 3, data = dataset, B = mult1)
> m3S <- mpjlcmm(longitudinal=list(mult3),subject = "id",  ng = 3, data = dataset, classmb= ~ factor(X3) + factor(X4) + factor(X5) + factor(X6))

Thank you,
sincerely.

**Comment by CecileProust-Lima** [comment]
Hi, 
sorry, we don't understand as it seems you did not put any classmb in the initialization models, but as recommended in the mpjlcmm directly. Can you elaborate on your problem please? 
Thank you
Cécile

**Comment by Smilinglion** [comment]
Hi Cecile,
No worries, I solved the issue. I was fitting a single model with multlcmm, instead of four separate models (one for each Y) with lcmm. I made the changes and it worked. Thank you for your feedback.
