### ISSUE TITLE
lcmm is not available in R 4.2.1

### ISSUE THREAD

**Issue by tinaty** [CecileProust-Lima/lcmm#133]
lcmm is not available in R 4.2.1, please could I ask what is the latest version of R that support lcmm

**Comment by CecileProust-Lima** [comment]
This is very surprising. I am under R 4.2.1 and I use lcmm version 2.0.0. 
What is your system?

**Comment by tinaty** [comment]
thanks for the confirmation, it is an issue coming from our server environment i think, now I am able to install lcmm in R v4.2.1
