### ISSUE TITLE
Error with mpjlcmm:  Number of items to replace is not a multiple of replacement length

### ISSUE THREAD

**Issue by Smilinglion** [CecileProust-Lima/lcmm#134]
Hello,

I'm using the mpjlcmm function with 4 lcmm objects. Each of these lcmm models were run with ng=5 and worked without any bug. But I'm getting an error when running the code below, and I'm not sure how to solve it.

_mS5 <- mpjlcmm(longitudinal=list(mult5_A, mult5_B, mult5_C, mult5_D),subject = "ID",  ng = 5, data = dataset)__

**Error in nmesM[, sum(ny[1:k]) - ny[k] + m] <- table(matYXord[which(matYXord$processK ==  :   number of items to replace is not a multiple of replacement length**

Your help is much appreciated,
Sincerely.

**Comment by CecileProust-Lima** [comment]
Hi, 
this is likely a problem of the number of subjects that differ between the dimensions considered. For now, we have restricted mpjlcmm to be used on samples where each subject has at least one measure of each dimension considered. 
We will add a warning on this for the future update on cran. 
Thank you for your feedback
Cécile

**Comment by Smilinglion** [comment]
Hi Cecile,
and thank you for your feedback.
