### ISSUE TITLE
Dataset Size Limits - HPC Optimizing, big data alternatives?

### ISSUE THREAD

**Issue by greermar** [CecileProust-Lima/lcmm#135]
Dear Dr Proust-Lima,
Thank-you for this fantastic package. I have used it successfully in a small study (6000 measurements in 400 patients), which hopefully will be published soon. I am currently attempting to model a larger cohort (2000 patients with 130k measurements) which has proven a challenge with resources. Even the simplest jclmm models require 7-10 days to run on my m1 mac. I have included parallelization now for the different latent class size calculations and moved the analysis to a HPC cluster but progess is very slow. I understand that R is the most likely bottleneck. Can you provide some insight into your experiences? Is this to be expected? Is something wrong with my processes or do you suggest I look elsewhere for datasets of this size? Microsoft-R Open??
Any insights here would be greatly appreciated!
Mark

**Comment by CecileProust-Lima** [comment]
Hi, 
This is indeed a very large cohort! We had issues like this before. In terms of time, from V2.0.0, you can now use parallel computing with all the lcmm functions, by using nproc = argument. 
I do not have right now any other suggestion to help you, really sorry. 
Cécile
