### ISSUE TITLE
Error when using predictClass with threshold link function

### ISSUE THREAD

**Issue by dirkpelt** [CecileProust-Lima/lcmm#138]
When using predictClass after fitting an lcmm() model with 2 classes with a threshold link function, I get the following error:

```
Error in .Ordlcmm(fixed = fixed, mixture = mixture, random = random, subject = subject, : 
NA/NaN/Inf in foreign function call (arg 30)
```

Below my code:

```
m2at <- lcmm(loud ~ poly(agec, degree = 2, raw = TRUE), random = ~ -1, subject = "ID",
             data = long, ng = 1, link = "thresholds")
m3at <- lcmm(loud ~ poly(agec, degree = 2, raw = TRUE), random = ~ -1, subject = "ID",
             mixture= ~ poly(agec, degree = 2, raw = TRUE), data = long, ng = 2, link = "thresholds", B=random(m2at) )

predictClass(m3at,newdata=long )
```

I saw issue #130 which seemed similar, so I have already tried copying the newest commit (?) of the predictClass function but I still get the same error. This is the function I used: https://github.com/CecileProust-Lima/lcmm/blob/45f3b7a807f7936717d778e99c2372accde9c6dc/R/predictClass.R

**Comment by dirkpelt** [comment]
One thing to add, my outcome is a three category variable (0-1-2) and is heavily skewed with the majority being zero's. I am not sure whether this has to with the error, or whether it is some bug.

**Comment by VivianePhilipps** [comment]
Hi,

you are right, this is a bug. The last version (commit bdefd89) should solve the issue.
Thank you for your message.

Viviane

**Comment by dirkpelt** [comment]
Thanks for the quick reply, it does work now after pulling the newest github version.
