### ISSUE TITLE
"Error in chol.default(varcov) :    the leading minor of order X is not positive definite"

### ISSUE THREAD

**Issue by maltenform** [CecileProust-Lima/lcmm#139]
I'm getting variations on 

"Error in chol.default(varcov) :    the leading minor of order X is not positive definite"

trying to run hlme.  This may be due to my particular data -- about 17 k subjects, average of 19 observations per subject, 50% with 2-5 observations, and rather noisy.   But I knocked it down to 100 subjects and had the same problem.

Examining the code, I am guessing that somehow the exploration of potential parameter space is hitting regions that are not numerically permissible, but I'm not sure if it's possible to either adjust my data or the function call to keep out of that trouble. Can anyone assist?

**Comment by VivianePhilipps** [comment]
Hi,

could you please give us more information on what you are exactly running?
If you are using the gridsearch function (or hlme with B=random(m1)), it may be a problem of non-convergence of the initial model as in #24 .

Viviane

**Comment by maltenform** [comment]
Thanks, I hadn't seen #24.  And yes, I was using hlme with a random parameter.

**Comment by maltenform** [comment]
Forgive my manners, not sure best mode of correspondence on these things.

Posted in comments:

“Thanks, I hadn't seen #24<https://github.com/CecileProust-Lima/lcmm/issues/24>. And yes, I was using hlme with a random parameter.
Update: I've tried changing the convergences to 1e-02, and I've also tried limiting the timespan (from 0-12 years to 0-3 years) and looking at 1 group vs 3 and still having same issue.”


From: VivianePhilipps ***@***.***>
Reply-To: CecileProust-Lima/lcmm ***@***.***>
Date: Wednesday, October 26, 2022 at 7:45 AM
To: CecileProust-Lima/lcmm ***@***.***>
Cc: "Maltenfort, Mitchell" ***@***.***>, Author ***@***.***>
Subject: [External]Re: [CecileProust-Lima/lcmm] "Error in chol.default(varcov) : the leading minor of order X is not positive definite" (Issue #139)


Hi,

could you please give us more information on what you are exactly running?
If you are using the gridsearch function (or hlme with B=random(m1)), it may be a problem of non-convergence of the initial model as in #24<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCecileProust-Lima%2Flcmm%2Fissues%2F24&data=05%7C01%7CMALTENFORM%40chop.edu%7C03014d7cc3c04fcb0aea08dab747a27f%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638023815543949010%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fHy9Hl86Ia3%2BvQTpytFodrXVy4nJCVFcO6cqWKx1wOM%3D&reserved=0> .

Viviane

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCecileProust-Lima%2Flcmm%2Fissues%2F139%23issuecomment-1291908763&data=05%7C01%7CMALTENFORM%40chop.edu%7C03014d7cc3c04fcb0aea08dab747a27f%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638023815543949010%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hkG4rBuZVuVPTJ%2FUDxkwBV2%2BrkA5Ac9IVgeQiWwg8Fs%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGQXDM4VNPMT5GYWCJJMRSLWFEKW5ANCNFSM6AAAAAAROKDF7I&data=05%7C01%7CMALTENFORM%40chop.edu%7C03014d7cc3c04fcb0aea08dab747a27f%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638023815543949010%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Rk4sPkArinTFsl2Pk%2BPLmzYvQceeSxS290yIrJqmb5U%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>
** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by maltenform** [comment]
Good news and bad news.

Good news -- it ran with 1 group, normal convergences, looks OK.

Bad news -- I try it with 2 classes, using either grid_search or hlme, and I get failure.  

With hlme, I get infinite parameters. With grid_search, I get the varcov not positive definite as before.

**Comment by VivianePhilipps** [comment]
I don't exactly understand why you have this issue.
Could you please check the variance of the random effects for the 1 class model?
If you are running a model like 
 `m <- hlme(outcome~y1+y2, random=~y1+y2, subject="id", data=d)`
the random effects' variance should be obtained with
 `vRE <- matrix(m$best[3+c(1,2,4,2,3,5,4,5,6)],3,3)`
`det(vRE)`

**Comment by VivianePhilipps** [comment]
Your variances are very very big.
I think you have to work on the time trend (fixed and/or random). The quadratic trajectory you choose may not be very appropriate if you observed such huge variability around your mean trajectory.

**Comment by maltenform** [comment]
Thanks.  I’ll look into using a different time scale

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: VivianePhilipps ***@***.***>
Sent: Thursday, October 27, 2022 11:35:52 AM
To: CecileProust-Lima/lcmm ***@***.***>
Cc: Maltenfort, Mitchell ***@***.***>; Author ***@***.***>
Subject: [External]Re: [CecileProust-Lima/lcmm] "Error in chol.default(varcov) : the leading minor of order X is not positive definite" (Issue #139)


Your variances are very very big.
I think you have to work on the time trend (fixed and/or random). The quadratic trajectory you choose may not be very appropriate if you observed such huge variability around your mean trajectory.

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCecileProust-Lima%2Flcmm%2Fissues%2F139%23issuecomment-1293716527&data=05%7C01%7CMALTENFORM%40chop.edu%7C60b675c1eee2417b628908dab830ee9f%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638024817555595593%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1ei2Dy5YXT5YGHhGzybfpSU5S307eGYw8e1oN1WOZDM%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGQXDM24F7JXE5XQXI5B7JDWFKONRANCNFSM6AAAAAAROKDF7I&data=05%7C01%7CMALTENFORM%40chop.edu%7C60b675c1eee2417b628908dab830ee9f%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638024817555595593%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZfG6NZw88%2B75rkB49bBK3%2BYfB8ux5tfvQvzGEJvb3p8%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by maltenform** [comment]
Vivienne, if you're still putting up with me, I'm grateful.  

I put in a fixed factor and interaction that seemed to take care of the random effects variance, but I still run into the "infinite parameters" issue when I try to branch out to more groups than 1, always dying at iteration 0.

> vRE
            [,1]        [,2]        [,3]
[1,]  0.15803632 -0.03719324 -0.09974563
[2,] -0.03719324  0.01889831  0.02563912
[3,] -0.09974563  0.02563912  0.07257642
> det(vRE)
[1] 1.468538e-05

**Comment by maltenform** [comment]
OK, I think I found a fix that gets it running.

The original model was based on up to 12 years. I did a subset of years <=4 and now it runs. So this may be a consequence of not all classes being in all years (?)

**Comment by VivianePhilipps** [comment]
The model does not require that all classes have a 10 years follow up, but if you have too few observations at the latest time points, it can lead to unstable estimations and so you get parameters close to infinity when you draw initial values.

To have an idea of the generated initial values in the grid search, you can use : 

`Brandom(estimates(m), VarCov(m), w=c(0, 1, 1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9, 10), b0=0, chol=8:13)`

with m the 1 class model.

**Comment by maltenform** [comment]
I’ve added some factors to the model to get it to stabilize so the digits may be off.  I assume 8:13 are the values of best with the VarCov, but where do you get those w from?


From: VivianePhilipps ***@***.***>
Reply-To: CecileProust-Lima/lcmm ***@***.***>
Date: Friday, October 28, 2022 at 6:12 AM
To: CecileProust-Lima/lcmm ***@***.***>
Cc: "Maltenfort, Mitchell" ***@***.***>, Author ***@***.***>
Subject: [External]Re: [CecileProust-Lima/lcmm] "Error in chol.default(varcov) : the leading minor of order X is not positive definite" (Issue #139)


The model does not require that all classes have a 10 years follow up, but if you have too few observations at the latest time points, it can lead to unstable estimations and so you get parameters close to infinity when you draw initial values.

To have an idea of the generated initial values in the grid search, you can use :

Brandom(estimates(m), VarCov(m), w=c(0, 1, 1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9, 10), b0=0, chol=8:13)

with m the 1 class model.

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCecileProust-Lima%2Flcmm%2Fissues%2F139%23issuecomment-1294810531&data=05%7C01%7CMALTENFORM%40chop.edu%7Cc62c487eaed143e4032d08dab8ccf434%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638025487658885336%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TG5kXVZY%2FJ4plN5t%2BpjkMGZRNVE9IGQfoN8VShFToWE%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGQXDM2YDGIPXCNXDXD3BO3WFORJVANCNFSM6AAAAAAROKDF7I&data=05%7C01%7CMALTENFORM%40chop.edu%7Cc62c487eaed143e4032d08dab8ccf434%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638025487658885336%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2WUpgWEdpEh%2B3Bun77J6PJicKMTVqZM41v5lq6euJNY%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>
** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by VivianePhilipps** [comment]
You get w and b0 from the 2 class model :

`m2 <- hlme(Ydep1~Time+I(Time^2), random=~Time+I(Time^2), data=data_lcmm, subject="ID", verbose=FALSE, maxiter=0, ng=2, mixture=~Time+I(Time^2), B=m)`

`m2$wRandom`

`m2$b0Random`
