### ISSUE TITLE
Why don't we use successive ordinal thresholds when we build the  "Binit" vector (vector of initial values)?

### ISSUE THREAD

**Issue by ivonnerenteria** [CecileProust-Lima/lcmm#14]
Dear Dr. Proust,

When I replicated the following routine in the section 6.3 lcmm,
`mord0 <- lcmm(CESD ~ age65 * male, random =~ -1, subject = 'ID',
 data = paquid, link = 'thresholds')`
`binit <- NULL`
`binit[1:6] <- mspl$best[1:6]`
`binit[7:56] <- mord0$best[4:53]`
`mord <- lcmm(CESD ~ age65 * male, random =~ age65, subject = 'ID',
 data = paquid, link = 'thresholds', B = binit)`

the list of initial values for thresholds parameters is not strictly increasing `(mord0$best[4:53]).` Why don't we use something like that `binit[7:56] <- mord0$estimlink[i,2]?` 

with thanks for any guidance you can offer,

Ivonne Rentería

**Comment by CecileProust-Lima** [comment]
Dear Ivonne, 
I think this question is the same as your previous one (issue 13). The parameters considered for the threshold link are the square roots of the increments between two levels, not the thresholds themselves. As such, they can't be directly initialized to the threshold (obtained from estimlink). 
Best
Cécile

**Comment by ivonnerenteria** [comment]
Thanks a lot Dr. Proust for your answer.
