### ISSUE TITLE
Dyadic analysis?

### ISSUE THREAD

**Issue by miiroth** [CecileProust-Lima/lcmm#141]
Dear all

I am wondering if it is possible to run dyadic growth mixture models? I have couple data (hence dyadic) and so far I‘ve run the models separately for men and women but of course the gain in information when taking dyadic data into account would be great.  I would greatly appreciate to hear more about that.

Best and thank you in advance 
Michelle

**Comment by BiostatBPH** [comment]
Dear Michelle, 
I am sorry, we did not implement nested random effect models. Either you can define random effects at the individual level or at the dyad level, not both. 
Cécile

**Comment by CecileProust-Lima** [comment]
Dear Michelle, 
I am sorry, we did not implement nested random effect models. Either you can define random effects at the individual level or at the dyad level, not both. 
Cécile
