### ISSUE TITLE
hlme results - classmb

### ISSUE THREAD

**Issue by jeannes-mun** [CecileProust-Lima/lcmm#142]
Greetings! I am using the lcmm package to run hlme on 3 time points (n=~15k) using 5 different classmb covariates.
 
My question to you pertains to multiple covariates. Is it accurate that the class membership covariates are modelled together, holding the other covariates constant? In other words, when multiple classmb covariates are used, can we interpret the results assuming other covariates are held constant? Or is each classmb covariate modelled independently?
 
Sorry in advance if this is a naïve question. I appreciate your help!

**Comment by CecileProust-Lima** [comment]
Hi, 
the classmb statement defines a multinomial logistic regression for the class membership. All the covariates indicated are thus included in a single model and the estimates are adjusted for the others. 
Cécile

**Comment by jeannes-mun** [comment]
Thank you so much, Cécile!
