### ISSUE TITLE
In mpjlcmm, what does this error refer to? Error in rep(0, NPM * (NPM + 1)/2) : invalid 'times' argument

### ISSUE THREAD

**Issue by sw3554** [CecileProust-Lima/lcmm#145]
Hello, I have run into a problem with mpjlcmm, I hope I'm not making too many new issues too quickly.

I'm trying to run a model with mpjlcmm, but I get the error in the title.
```
mult_m1<-multlcmm(y1+y2  ~ age_tf, random=~age_tf,subject='newID', data = sl_dat_traj,  link = c("linear","3-quant-splines"),maxiter=150)

sl_dat_sub<-sl_dat_traj %>% filter(!is.na(y1) & !is.na(y2) & !is.na(y3))

m1S <- mpjlcmm(longitudinal=list(mult_m1),subject="newID",ng=1,data=sl_dat_sub,
survival=Surv(TTE_tf,y3)~ 1)
```
The first part, mult_m1 was able to converge. The Surv(TTE_tf,y3) part when run separately did not throw any error messages. A joint model with y1 and Surv(TTE_tf,y3) was able to run with error.

I also tried this but got the same error:
```
m1S <- mpjlcmm(longitudinal=list(mult_m1),subject="newID",ng=1,data=sl_dat_sub,
survival=Surv(init_age, event_age,y3)~ 1)
```

**Comment by CecileProust-Lima** [comment]
Hi, 
I don't know what could be the problem with this code. 
I tried to reproduce the code using the data in lcmm package. Is it what you intend to do?

paq <- paquid %>% mutate(time = age - age_init,
                         delai_dem = agedem - age_init)

m <- multlcmm(IST + BVRT ~ time, random=~time,subject="ID",data=paq)

paq2 <- paq %>% filter(!is.na(IST) & !is.na(BVRT))

m2 <- mpjlcmm(longitudinal=list(m),subject="ID",ng=1,data=paq2,
               survival=Surv(delai_dem,dem)~ 1)

Does this code work for you? 
Cécile

**Comment by sw3554** [comment]
Hi Cécile,

That code does work for me. So I tried to simplify things and tried this:

m_ic1<-lcmm(IC~age_tf+gender*age_tf+ci*age_tf, subject='ID_num', data=sl_dat_traj,link="beta",maxiter=50)
m_mo1_lin<-lcmm(Mobility_~age_tf+gender*age_tf+ci*age_tf, subject='ID_num', data=sl_dat_traj,link="3-equi-splines",maxiter=50)

mm1S <- mpjlcmm(longitudinal=list(m_ic1),subject="ID_num",ng=1,data=sl_dat_traj)
mm1S <- mpjlcmm(longitudinal=list(m_ic1,m_mo1_lin),subject="ID_num",ng=1,data=sl_dat_traj)


The two lcmm parts were able to run without error, but both the mpj parts gave a new error:

Error in str2lang(x) : <text>:2:0: unexpected end of input
1: ~ processK+outcomeM+age_tf + gender * age_tf + ci * age_tf+
   ^


However, using this code copied and adjusted from the help page works:

paquid$age65 <- (paquid$age-65)/10
mMMSE1 <- lcmm(MMSE~age65+I(age65^2)+CEP,random=~age65+I(age65^2),subject="ID",
link="5-quant-splines",data=paquid)
mCESD1 <- lcmm(CESD~age65+I(age65^2)+male,random=~age65+I(age65^2),subject="ID",
link="5-quant-splines",data=paquid)
mm1S <- mpjlcmm(longitudinal=list(mMMSE1),subject="ID",ng=1,data=paquid)
mm1S <- mpjlcmm(longitudinal=list(mMMSE1,mCESD1),subject="ID",ng=1,data=paquid)


If it helps, here are the two outputs from the univariate models I ran: 
First model:
General latent class mixed model 
     fitted by maximum likelihood method 
 
lcmm(fixed = IC ~ age_tf + gender * age_tf + ci * age_tf, subject = "ID_num", 
    link = "beta", data = sl_dat_traj, maxiter = 50)
 
Statistical Model: 
     Dataset: sl_dat_traj 
     Number of subjects: 6494 
     Number of observations: 10543 
     Number of observations deleted: 392 
     Number of latent classes: 1 
     Number of parameters: 11  
     Link function: Standardised Beta CdF  
 
Iteration process: 
     Convergence criteria satisfied 
     Number of iterations:  15 
     Convergence criteria: parameters= 2.2e-09 
                         : likelihood= 2.2e-07 
                         : second derivatives= 7.6e-11 
 
Goodness-of-fit statistics: 
     maximum log-likelihood: -22923.55  
     AIC: 45869.09  
     BIC: 45943.66  
 
     Discrete posterior log-likelihood: -22924.88  
     Discrete AIC: 45871.77  
 
     Mean discrete AIC per subject: 3.5319  
     Mean UACV per subject: 3.5323  
     Mean discrete LL per subject: -3.5302  

Second model:
General latent class mixed model 
     fitted by maximum likelihood method 
 
lcmm(fixed = Mobility_ ~ age_tf + gender * age_tf + ci * age_tf, 
    subject = "ID_num", link = "3-equi-splines", data = sl_dat_traj, 
    maxiter = 50)
 
Statistical Model: 
     Dataset: sl_dat_traj 
     Number of subjects: 6283 
     Number of observations: 10081 
     Number of observations deleted: 854 
     Number of latent classes: 1 
     Number of parameters: 12  
     Link function: Quadratic I-splines with nodes  
1 14 27  
 
Iteration process: 
     Convergence criteria satisfied 
     Number of iterations:  44 
     Convergence criteria: parameters= 1e-10 
                         : likelihood= 4.6e-06 
                         : second derivatives= 8.6e-05 
 
Goodness-of-fit statistics: 
     maximum log-likelihood: -24845.86  
     AIC: 49715.72  
     BIC: 49796.66  
 
     Discrete posterior log-likelihood: -23331.62  
     Discrete AIC: 46687.25  
 
     Mean discrete AIC per subject: 3.7154  
     Mean UACV per subject: 3.7157  
     Mean discrete LL per subject: -3.7135

**Comment by VivianePhilipps** [comment]
Hello,

thank you, there was indeed a bug in the function without random effect. The last commit on the master should correct it.

In the above example,  process 1 is the m_ic1 model and process 2 the m_mo1_lin model, so the warning refers to the "Mobility" variable.

Viviane
