### ISSUE TITLE
predictY with quadratic function error message

### ISSUE THREAD

**Issue by VSSchneider** [CecileProust-Lima/lcmm#149]
Hi,

Thank you so much for this fantastic package and all your help on here.
I am new to latent class trajectories, but have so far been able to run mixed effect and fixed models with linear and quadratic functions using the "threshold" link function for an ordinal outcome. For the linear shapes, I have also been able to use the predictY function. However, when applying this to my best fitting model which is one with 3 classes, random intercept and quadratic shape, I get the following error:

newdata should at least include the following covariates: Date T

This is despite the newdata being set up with "Date". Not sure what is denoted by T as my original model did not include any other covariate. What am I missing?

Model:

random3a_sq <- lcmm(Y~poly(Date, degree=2, raw=T), subject="ID", random=~1, ng=3, data=data_long, link="thresholds", mixture=~poly(Date, degree=2, raw=T), B=random(random1a_sq))

Predict:

data.random3a_sq<- data.frame(Date=seq(1,292,by=1))
y.pred <- predictY(random3a_sq, data.random3a_sq, var.time = "Date")

A second question is RE having orthogonal polynomials. When I try to enter raw=F, I get an error saying that missing values are not allowed in 'poly'. What am I doing wrong?

Many thanks in advance,
Verena

**Comment by VivianePhilipps** [comment]
Hi,

I think the function does not like the abbreviations T/F instead of TRUE/FALSE. Could you please try with raw=TRUE?

Viviane

**Comment by VSSchneider** [comment]
Hi Viviane,

Thanks for this super fast answer. Such an easy solution! I should have thought of trying this myself. raw=TRUE works, however, raw=FALSE still returns the above error message. 

Thanks,
Verena

**Comment by VivianePhilipps** [comment]
This is the behavior of the poly function. It does not allow missing values with raw=FALSE.
For orthogonal polynomials you will have to create first a dataset without any missing values in variable Date.

**Comment by VSSchneider** [comment]
Thanks, again! Got it.
