### ISSUE TITLE
Advice on running models with threshold link function

### ISSUE THREAD

**Issue by VSSchneider** [CecileProust-Lima/lcmm#152]
Hi,

Thanks again for all your help on this forum. 

I wondered if you could clarify your advice for running threshold functions in your paper in the Journal of Statistical Software (https://www.jstatsoft.org/article/view/v078i02) on p. 32.

You recommend “estimating the model first without random effects to obtain satisfactory initial values for the thresholds before any inclusion of random effects“. I see that these values have been used for vector B[7:56]. Where I feel I have missed something is why B[1:6] is using values of a model run with the spline link function. 

Apologies if this is a silly question. 

Many thanks in advance,
Verena

**Comment by VivianePhilipps** [comment]
Hi,

we need to provide initial values for all the parameters. The mod0 model gives us values for the thresholds, and we need values for the fixed and random effects. Either we give them some arbitrary values (for example 0 or 1), either we also get them from another model. As we already estimated the same model with splines and that the fixed and random effects estimated with two flexible enough link functions should be roughly similar, we can take these estimations as initial values to reduce the running time. 
 
Viviane

**Comment by VSSchneider** [comment]
Hi Viviane,

Many thanks again for your quick response.

That makes sense.

Best wishes,
Verena
