### ISSUE TITLE
Advice on model with multiple timepoint and binary outcome

### ISSUE THREAD

**Issue by idborquez** [CecileProust-Lima/lcmm#153]
Dear Cecile,

I wanted your advice on a model I am trying to estimate with the lcmm package. I have 8649 patients, and I am following them for 9 years with administrative data (108 months). I want to estimate their trajectories within the treatment system (in this case in substance abuse treatment). I have most cases with 1 treatment episode, which can be from 0 to 63 months (mean in around 9 months). Then, I have around 34% of patients that undertook more than 1 treatment in the 9 years I am following them through administrative data.

What I've been doing thus far is using the lcmm with the threshold link function, using just 21-time points/months (1,3,6,9,12,18,24,30,36,42,48,54,60,66,72,78,84,90,96,102,108). Nonetheless, I would like to use all the time points available (108 months), but I am not sure if the models will take longer time on estimating. Right now it has been really challenging getting the models to converge, and the amount of time it takes me to estimate one model can be more than 24 hours. In this case, what would be better, to give more or less information (in available time points of the outcome) to the model in order for it to converge?

Also, I was wondering if there might be another link function I could use to estimate the models. Rigorously speaking I have continuous time (e. i. the date they started/ended a treatment) and I've been calculating the duration of each treatment episode, and the duration between treatment episodes for those who have more than 1 treatment episode. Thus, I have 108 variables where 1=treatment and 0=no treatment for the 8649 subjects.

My ultimate objective is to test different trajectory model approaches to estimate latent trajectories of treatment usage in time, and one of the methods I am trying to use is Latent Class Growth Analysis with the lcmm package.  

Thanks in advance, and thanks for the amazing work you do with this package

**Comment by VivianePhilipps** [comment]
Hello,

In the lcmm package, we do not provide any other link function as "thresholds" for binary outcomes. 108 measures per subject for that kind of models is very difficult (computationally speaking). Maybe you will have to reduce the information by summarizing the treatment use by semester or trimester. 
With about 30 time points it will still be long but less than with 108.

Best,

Viviane
