### ISSUE TITLE
Advice to find the best link function in lcmm

### ISSUE THREAD

**Issue by SiPineau** [CecileProust-Lima/lcmm#154]
Hey,

I'm running lcmm and I'm trying to find the best link function. I've tried with the default function (linear, beta, 3-quant-splines, 4-quant-splines, etc) but often, the best fit is with a manual splines link function I find in multiple fails and tries. There is an example of a summarytable for one of my variables : (numbers after the "_" are those manually entered)
![2022-12-27 17_32_21-Projet_These_stat1 - RStudio](https://user-images.githubusercontent.com/115237647/209694868-5241bfd5-e371-4a95-9542-0ec96e84f392.png)

Do you have any advice that can help to find more quickly the best link function ?

In my example, the best fits are from the manual link function with knoks (1.01 and 4.99) very close to the maximum and minimum values of the variable (1 and 5). Do you think is because marginal residuals are very not normaly distribut as show below with "plot(Manualsplines4_1.01_4.99)" :

![2022-12-27 17_39_29-Plot Zoom](https://user-images.githubusercontent.com/115237647/209695694-b28eb3ef-9c18-417d-82a0-ca6dd53210ac.png)

Thank you for your help !

**Comment by SiPineau** [comment]
Additional note : is it a problem if some splines have negative values ? As in the example below :

Statistical Model: 
     Dataset: dfPemolongiFlong_compl 
     Number of subjects: 720 
     Number of observations: 2394 
     Number of observations deleted: 486 
     Number of latent classes: 1 
     Number of parameters: 10  
     Link function: Quadratic I-splines with nodes  
1 1.01 4.99 5  
 
Iteration process: 
     Convergence criteria satisfied 
     Number of iterations:  14 
     Convergence criteria: parameters= 8.8e-11 
                         : likelihood= 7.3e-09 
                         : second derivatives= 1.4e-15 
 
Goodness-of-fit statistics: 
     maximum log-likelihood: -528.98  
     AIC: 1077.96  
     BIC: 1123.75  
 
 
Maximum Likelihood Estimates: 
 
Fixed effects in the longitudinal model:

                              coef      Se    Wald p-value
intercept (not estimated)        0                        
TdM                       -0.02311 0.02524  -0.916 0.35984


Variance-covariance matrix of the random-effects:
          intercept     TdM
intercept   2.23438        
TdM        -0.36897 0.15971

Residual standard error (not estimated) = 1

Parameters of the link function:

               coef      Se    Wald p-value
I-splines1 -2.99056 0.10884 -27.476 0.00000
I-splines2  0.96114 0.02823  34.041 0.00000
I-splines3 -0.70971 0.06393 -11.101 0.00000
I-splines4  1.51307 0.04573  33.090 0.00000
I-splines5 -0.79432 0.05184 -15.324 0.00000
I-splines6  0.99228 0.02219  44.720 0.00000

**Comment by CecileProust-Lima** [comment]
Hi,
the two lines suggest that you have a lot of data at the boundaries. This may cause these changes in the likelihood you see. 
My recommendation would be to plot the link functions you obtain. You will probably see that the resulting link functions are very close so whatever the one you choose, your results will be very similar in terms of regression parameters. 
Cécile

**Comment by SiPineau** [comment]
Thank you for your answer. I tried to plot link functions and indeed, they are very close to each other.

Thank you again, have a good day.
