### ISSUE TITLE
Relating class membership with external binary outcome

### ISSUE THREAD

**Issue by VSSchneider** [CecileProust-Lima/lcmm#155]
Happy New Year and thanks again for your help in this forum!

I already posted this on a closed issue but realise I should probably have opened a new issue:

I am looking for ways to relate my identified classes (identified using lcmm with threshold link function) to a binary external outcome. I am trying to understand whether I can use the mpjlcmm function for that purpose but it seems this would only work on a continuous outcome? I have already run models with predictors of the latent classes by fixing parameters as explained in previous posts. Could the same work with a binary outcome in a separate model if interested in its association with latent classes (even though modelled as a predictor)?

I am aware the naive (3-step) approach would be to use predicted class membership in separate logistic regression models. However, I want to avoid this approach due to the classification error.

Many thanks!

**Comment by VivianePhilipps** [comment]
Hello,

a bivariate model would be the way to do, but the mpjlcmm function is not implemented for discrete outcomes.
In the literature other methods or corrections of the naive approach have been proposed, and they can be used outside the lcmm package, so it could be an alternative.

Best,

Viviane

**Comment by VSSchneider** [comment]
Hi Viviane,

Many thanks for this. While assessing my models I came up with a few more questions which I hope you can help me with.

1. When running models where I allow the variance-covariance matrix to be class-specific (nwg=TRUE), I find that my model fit is worse (i.e., higher BIC) and entropy is higher (compared to nwg=FALSE). I would intuitively expect the opposite for a more complex (but probably more realistic) model. Why is this the case?
2. When fixing class membership before adding a covariate there are a few things happening that I struggle to understand:
    a. A few of the models with just one covariate do not converge, even after playing around with maximum iteration or convergence parameters. Some of these covariates are very simple binary variables and I was surprised they would cause convergence issue of a model that converged well before adding them.
    b. When comparing the model without covariate and the one with, I am expecting to find no differences in BIC, entropy, and class% given I fixed parameters to avoid class shift. However, some shifts are happening. Why is this?

![image](https://user-images.githubusercontent.com/115980959/212496603-fb682887-c2a5-4878-965f-a0b023f92344.png)


Many thanks!
Verena

**Comment by VSSchneider** [comment]
Thanks, Viviane!
