### ISSUE TITLE
Interpretation of linear and quadratic slopes estimates

### ISSUE THREAD

**Issue by SiPineau** [CecileProust-Lima/lcmm#156]
Hello,
Some context about the study: I measured my longitudinal outcome at 4 time points and tried to study heterogeneity in my sample. I used lcmm function (as marginal residuals aren’t normal). As the "time" variable is code for 1 to 4, I centered it on the first time point to interpret intercepts as follows:
> df$Time.0<-df$Time-1

I want to study linear and quadratic slopes, so I specified my models as below. The best number of sub-group seems to be 6.
 
![image](https://user-images.githubusercontent.com/115237647/211193129-3015658f-7d11-41e4-a2b4-80316226e4b6.png)

However, I wonder how to interpret the linear slope estimate when quadratic slope estimate is significant. As you can see from the summary() bellow, linear slope estimate for class1 is significantly negative and quadratic slope estimate is significantly positive. But looking at the predY plot, class1 longitudinal outcome seems to increase over the all time points, and not decrease (see the black line in the figure).
How can I interpret this linear slope estimate? Graphically, it seems that the linear slope estimate refers to the first time and the second time points only (therefore a negative estimate), but how can I estimate the linear slope over the all time points?
> summary(visaMLCMMDout6)
 
![image](https://user-images.githubusercontent.com/115237647/211193137-78bbaa14-2e4c-4451-9576-e4d99654b7d4.png)

> predY <- predictY(visaMLCMMDout6,newdata=df,var.time="Time.0")
> plot(predY,shades=TRUE, ylim=c(1,5)) 
 
![image](https://user-images.githubusercontent.com/115237647/211193160-80cbf617-cbf0-4086-809f-c3b830f2607c.png)

Thank you!

**Comment by VivianePhilipps** [comment]
Hi,

the two parameters are difficult to interpret separately because they are very correlated. We usually just plot the resulting curves as you do and interpret the shape of the trajectories.  A numerical quantification of their differences is more tricky but a visual comparison is fine.

Best,

Viviane
