### ISSUE TITLE
What to do after pooling final parameters

### ISSUE THREAD

**Issue by sophieschneemelcher** [CecileProust-Lima/lcmm#157]
Dear Cécile and dear Viviane,

I have 10 multiple imputed datasets and did the estimation exemplary for my gmm with 2 classes for each of the imputed datasets. After that, I combined the replicate parameter estimates referring to your advice in https://github.com/CecileProust-Lima/lcmm/issues/120 (by the way - thank you very much for this helpful information). 

So right now, I have 
a) the mean of the estimates of 10 models (**_estim_pool_**) 
b) the variance-covariance matrix of 10 models (**_var_pool_**)

My question is: How do I continue right now with the final parameters? My primary aim is to compare the model with different classes (ng = 2, 3 and 4) and to choose the best model over 10 multiple imputed datasets. Would it be the right way to pool the fit indices (AIC, BIC, %class...) as well? Would it simply be the mean separately for AIC, BIC... over the 10 separately fitted models?

Any support is well appreciated 
Sophie

**Comment by sophieschneemelcher** [comment]
Dear Viviane, 

thank you very much for this helpful response! 

Let me just ask one little question: For the model with estim_pool as estimates you used data=data1, I did the same and used the first imputed dataset.

Would you advise me to use the first imputed dataset as the reference for my final hlme-object or how should it be done?

Thank you very much
Sophie

**Comment by CecileProust-Lima** [comment]
Dear Sophie, 
this is a tricky question!  We actually never used the method with multiple imputations for the moment. 
Selection based on ICL, BIC etc necessitates computing the likelihood and thus having complete data. You could indeed use one of the imputed dataset as a reference but this may not be completely satisfying. 
An alternative could be to compute differences in criteria in each imputed model (your 10 initial models) and then find a rule to select the number of class which appears as the optimal one most of the time for instance. Maybe even compute a mean of the selection criteria as they are supposed to correspond to the same global population? For the entropy I would go with that. For the BIC, ICL and AIC maybe too. 

One other tricky thing with MI method must have been the label switching across your 10 models. I hope you found a solution to prevent that (i.e., be quite sure that you did not have permutations between classes). 

Good luck with this complex but very motivating work! 
Cécile

**Comment by Diego-FB** [comment]
Regarding the 'trick' to get the outputs is there an easy way of replicating for mpjlcmm() with two latent processes. Modelized as mm2S <- mpjlcmm(longitudinal=list(mMMSE2,mCESD2),subject="ID",ng=2,data=paquid,
survival=Surv(age_init,agedem,dem)~CEP+mixture(male),classmb=~CEP+male)
