### ISSUE TITLE
lcmm/hlme function specification

### ISSUE THREAD

**Issue by pedreirajr** [CecileProust-Lima/lcmm#159]
Dear Cécile and Viviane,

First, thank you for this wonderful package, all the material shared and your efforts to keep improving it.
Sometimes I wonder if the model formulation I'm investigating corresponds to what I'm running on R. Could you please clarify whether these specifications below are correct? I have the slight impression that the hlme/lcmm parameters from Model 3 actually produces the formulation of Model 2.
![image](https://user-images.githubusercontent.com/22227304/217537494-304ccee0-e431-4456-ac2a-062cedceb454.png)

Cheers,
Jorge

**Comment by VivianePhilipps** [comment]
Hello Jorge,

your first model can be written $Y_{it} = \beta_{00} + \beta_{01} t + \beta_{02} t^2 + \mu_{0i}+ \varepsilon_{it}$.
In that formulation, the fixed effects are all variables without individual effect and the random effects are all variables with an individual effect (with an subscript $i$ in the associated coefficient).
Here you have a quadratic trend in the fixed effects (intercept, $t$ and $t^2$) and a random intercept ($\mu_{0i}$), so the lcmm specification is fixed=~poly(t, degree=2), random=~1.

In the same way, your second model is $Y_{it} = \beta_{00} + \beta_{10} t + \beta_{20} t^2 + \mu_{0i}+ \mu_{1i}t+ \mu_{2i} t^2+ \varepsilon_{it}$, so you specify fixed=~poly(t, degree=2), random=~poly(t, degree=2).

And the last one would define a degree 4 for the fixed effects and a degree 2 for the random effects.

Best,

Viviane

**Comment by pedreirajr** [comment]
Fantastic. Thank you very much for your response, Viviane.

Cheers,
Jorge
