### ISSUE TITLE
Time-varying covariates

### ISSUE THREAD

**Issue by pedreirajr** [CecileProust-Lima/lcmm#160]
Dear Cécile and Viviane,

I checked all open and closed issues and didn't find any topic related to this.
I have some time-varying covariates whose influence I would like to assess on a dependent variable. To be more specific, I'm modeling the change in the weekly frequency of telework, measured in an ordinal scale, throughout four time periods. However, for any given time, the nature of the individuals' occupation (how amenable to telework it is at the moment of measurement) and the interruption of in-person work due to the COVID-19 pandemic affect this outcome. I wonder if including these variables on the `fixed` argument of the `lcmm` function would make sense.

**Comment by pedreirajr** [comment]
To be more specific, is the parametrization of the lcmm function corresponding the path diagram of the image correct?
`lcmm(fixed = y ~ x + poly(time, degree = 1), random = ~ poly(time, degree = 1))`

![image](https://user-images.githubusercontent.com/22227304/217958412-bec995a8-dd42-467d-94f0-6933eea1a6de.png)

**Comment by CecileProust-Lima** [comment]
Hi,
indeed, you can include time-varying covariates in your longitudinal model. With a covariate X (time-varying), adding +X in the fixed statement will provide a beta parameter corresponding to the effect of X at time t on Y at time t. 
If you also model latent classes (with the mixture argument), you can also estimate this effect in each latent class by adding +X to the mixture statement. 

For your information -and for other users reading this post, what can't be done in lcmm package is adding time-varying variables in the survival model and in the class membership model. 

Cécile

**Comment by pedreirajr** [comment]
Hi Cécile,

Thank you for kind and detailed response. It helped me a lot!

Cheers,
Jorge
