### ISSUE TITLE
Dynamic predictions for a mpjlcmm

### ISSUE THREAD

**Issue by cforne** [CecileProust-Lima/lcmm#164]
Dear Cécile, dear Viviane,

The `lcmm` package is great. Thanks for your work!

I have been working with joint latent class models for multivariate longitudinal markers and time-to-event (`mpjlcmm`). 

Is there a way to get dynamic predictions for a `mpjlcmm`? (similar to `dynpred` for `Jointlcmm`)

Best,
Carles

**Comment by VivianePhilipps** [comment]
Hello Carles,

thank you for your message.
The dynpred function is not implemented for a mpjlcmm model. We reuse essentially existing functions (dedicated to hlme, lcmm, mlcmm or jlcmm objects) to deal with mpjlcmm models, but the dynamic predictions would require a greater investment, it is not straightforward.

Best,

Viviane

**Comment by cforne** [comment]
Thank you so much! I will be tuned to news in this regard.

Best,

Carles
