### ISSUE TITLE
Advice on predictor selection procedures within lcmm

### ISSUE THREAD

**Issue by noellevanbiljon** [CecileProust-Lima/lcmm#166]
Dear Cecile and Viviane

I am in the process of describing latent trajectories I have identified, and have a huge sample of predictors to consider. To reduce the number of predictor variables in the past (outside the lcmm framework) I have used various approaches such as stepwise selection (using stepAIC) or Lasso regression to identify the most important variables. 

Is there an approach you can suggest that cooperates with the lcmm output to perform predictor selection, or does one need to do this manually (or write your own function to automate this)?

Many Thanks for any help!

**Comment by VivianePhilipps** [comment]
Hi,

we have the externVar function that performs such latent class description, but it does not deal with variable selection.
We've never had any application with a large set of covariates within a latent class analysis, so the package doesn't automate the procedure.

Best,

Viviane

**Comment by TarandeepKang** [comment]
Hi both,

I hope it is okay to join this conversation if I have a similar question? A colleague came to me with a variable selection problem in latent class analysis. The only solution I have found uses the LCAvarsel package

https://cran.r-project.org/web/packages/LCAvarsel/index.html

It doesn't seem that model objects from your package can be subsequently used for variable selection here? I am absolutely not a programmer, just an end-user, so forgive me if this question is naïve: would it be possible at all to make model objects from your package compatible with this? Should I even be asking you, or the maintainer of this other package?

Again, apologies if the answers to these questions seem obvious to you!

Best,

Tarandeep

**Comment by VivianePhilipps** [comment]
Hi,

I've never used this package, so I can't tell you if it is compatible with lcmm.
I think mixing LCAvarsel and lcmm will require to call one of our functions within LCAvarsel, so to modify the source code of LCAvarsel. Depending ob how this package is constructed, it can be easy or not.

Best,

Viviane
