### ISSUE TITLE
Plot subject-level predicted trajectory

### ISSUE THREAD

**Issue by p-lemercier** [CecileProust-Lima/lcmm#167]
Hi, 
I am trying to visualize the subject-level trajectory based on the model predictions. Also, the predictions should be on the same scale as my dependent variable.
I have seen that the function `predictY` set up with `marg = FALSE` provide such predictions but this is available only for hlme object.

In the case of lcmm, is the following example correct or am I missing something?

``` r
library(dplyr)
library(ggplot2)
library(lcmm)

data(paquid)

paquid <- paquid %>%
  mutate(age65 = (age - 65)/10)

### Latent class mixed model with 1 classes
modSpline1 <- lcmm(CESD ~ age65, random =~ age65, subject = "ID", 
                   var.time = "age65", data = paquid, link = "5-quant-splines")

### Latent class mixed model with 2 classes
modSpline2 <- lcmm(CESD ~ age65, random =~ age65, subject = "ID", 
                   var.time = "age65", data = paquid, link = "5-quant-splines", 
                   mixture =~ age65, ng = 2, B = random(modSpline1))


### Subject-level predictions

# Posterior classification of each subject
predClass <- predictClass(modSpline2, newdata = paquid)

pred <- modSpline2$pred %>%
  left_join(predClass, by = "ID") %>%
  mutate(
    # Individual latent predicted values according to class-membership
    CESD_latent_pred = case_when(class == 1 ~ resid_m+pred_ss+pred_m1+pred_ss1,
                                 class == 2 ~ resid_m+pred_ss+pred_m2+pred_ss2),
    # Transform latent predictions to their natural scale
    CESD_pred = predictYcond(modSpline2, CESD_latent_pred)$pred[["Ypred"]],
    class = factor(class)
  )

### Visualization

ggplot(pred, aes(age65, CESD_pred, color = class)) +
  geom_point(aes(group = ID), alpha=.5, size = 1) +
  geom_line(aes(group = ID), alpha=.5) +
  theme_bw()
```

![](https://i.imgur.com/5I8xOit.png)

<sup>Created on 2023-03-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by VivianePhilipps** [comment]
Hi,

to get the same outcome as predictY(m, marg=FALSE), but with a lcmm model, you can indeed combine the $pred output and the predictYcond function.
With your modSpline2 model, the subject-specific predictions are get with
 `predictYcond(modSpline2$pred[,"pred_ss1"])` for class 1
and
 `predictYcond(modSpline2$pred[,"pred_ss2"])` for class 2. 

Note however that confidence intervals cannot be obtained directly with the draws argument. The whole procedure should be included in a parametric bootstrap to get correct CI.

Best,

Viviane

**Comment by p-lemercier** [comment]
Thank you very much for your answer.

Now I realize that the way I calculated `CESD_latent_pred` makes no sense. Using the example above, the script is simpler and I get nicer figures. 

``` r
### Subject-level predictions

pred <- modSpline2$pred %>%
  # Posterior classification of each subject
  left_join(modSpline2$pprob, by = "ID") %>%
  mutate(
    # Individual predictions to their natural scale according to class-membership
    CESD_pred = case_when(class == 1 ~ predictYcond(modSpline2, pred_ss1)$pred[["Ypred"]],
                          class == 2 ~ predictYcond(modSpline2, pred_ss2)$pred[["Ypred"]]),
    class = factor(class)
  )

### Visualization

ggplot(pred, aes(age65, CESD_pred, color = class)) +
  geom_point(aes(group = ID), alpha=.5, size = 1) +
  geom_line(aes(group = ID), alpha=.5) +
  theme_bw()
```

![](https://i.imgur.com/1XOeGzr.png)

<sup>Created on 2023-03-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
