### ISSUE TITLE
Is it possible to combine known and unknown classes?

### ISSUE THREAD

**Issue by ewancarr** [CecileProust-Lima/lcmm#168]
I have two questions related to the `prior` argument of `hlme` and `lcmm`:

### 1. Does setting a `prior` _fix_ latent class membership, like the `KNOWNCLASS` option in Mplus?

Or is it only a prior — and so, eventual class membership might differ from the prior?

### 2. Is it possible to combine known and unknown classes?

I'm interested in fitting "a growth mixture model with known classes", as shown in [this paper](https://ctri.wiscweb.wisc.edu/wp-content/uploads/sites/240/2017/06/Kim-Mun-Smith-Br-J-Math-Stat-Psychol-Using-mixture-models-14.pdf).

<img width="350" alt="image" src="https://user-images.githubusercontent.com/1553551/226843307-c96b5e22-a891-4cdb-85fc-02717db68e12.png">

With this approach, we identify latent classes within each level of the grouping variable. In my example, I have two levels of the grouping variable (i.e., the 'known class' or prior; `G`), and within each, I expect two latent classes:

* `G` = 1
  * Class 1.1
  * Class 1.2
* `G` = 2
  * Class 2.1
  * Class 2.2

I was trying something like this, where my prior `G` has two levels (1 and 2) and I'm trying to estimate two classes *within* each level (and so, `ng` = 4):

```{r}
m2 <- hlme(y ~ t,
           subject = "id",
           random = ~ t,
           ng = 4,
           prior = G,
           B = m1,
           mixture = ~ t,
           data = df)
```

Is this possible in `lcmm`?

***

Thank you so much for creating this package and your tireless work maintaining the repository. 

Best,

Ewan

**Comment by VivianePhilipps** [comment]
Hi Ewan,

the prior argument assigns a subject to a latent class, so this subject cannot switch to another class during estimation.
But you don't need to define a prior for each subject, it can be specified for some subjects only.

 For your second point, it is not possible in the lcmm package to specify relations between the classes. So, nesting 2 sub-classes in two main latent classes is not implemented.

Best,

Viviane

**Comment by ewancarr** [comment]
Hi Viviane,

Many thanks for the quick reply — very helpful.

Best,

Ewan
