### ISSUE TITLE
Latent class growth analysis/growth mixture modeling with large sample sizes

### ISSUE THREAD

**Issue by PaulMeijer** [CecileProust-Lima/lcmm#169]
Dear Cécile and Viviane,

I am a PhD student at the University Medical Center Utrecht in the Netherlands. I am currently working on a project that involves latent class growth modeling for which using the lcmm package in R. 

My project is about changes in neighbourhood greenspace around people’s home address over time. I am applying latent class growth analysis and growth mixture modeling to identify trajectories in neighborhood greenspace across 5 time points. I am using data from a national registry, which has a very large sample size of 3.5 million individuals. 
 
This is where I run into the problem that running the models on this large sample is very computationally intensive, especially when using random effects and more than 1 class. Models run for days on end with a high chance of R crashing somewhere during the process. 
 
Currently, plan B is to use a subsample of 10%. However, this sample of about 350,000 individuals still results in the same issues. Even though I am using a workspace with 128 GB of working memory to conduct the analyses in R. 

I was wondering whether you have any solutions or suggestions for working with such large sample sizes? Perhaps you have encountered similar issues before or know of others who have. 
 
Thanks in advance and I look forward to hearing from you.

Kind regards,
Paul

**Comment by VivianePhilipps** [comment]
Hello Paul,

we are not used to deal with so large sample sizes. I think it will definitely be an issue with our package, I have no workaround to suggest. Sorry for that.
Before version 2.0 of lcmm, the estimation task (in hlme, lcmm, mlcmm, jlcmm and mpjlcmm) was entirely written in Fortran, and we used R only as a wrapper. Maybe Fortran programs are more robust to large data. But the inputs are still handled in R, so I suspect the same problems will happen.

Best,

Viviane

**Comment by Gootjes** [comment]
@PaulMeijer Have you tried the nproc argument in for example hlme function? It enables using multiple processes which can speed up the analysis greatly. However, it also involves copying the dataset to each process. If your dataset object is really large, this can take some time too.
