### ISSUE TITLE
convergence  and test

### ISSUE THREAD

**Issue by rfluss** [CecileProust-Lima/lcmm#17]
Hello,
 i am trying to use your package, "lcmm" in R and will appreciate any  help here.

I find something strange. 
I started with a simple random effect model with one group/cluster:

y~t1+t2+t3  where 
t1=time, t2=t^2 and t3=t^3.
as follows:
hlme(y~t1+t2+t3,random=~t1+t2+t3,subject='id',ng=1,data=d)

and the model converges. But when I try it with the procedure lme in "nlme" package or lmer in "lme4" package the model does not converge.

In addition when I compare this model to a simpler model y~t1+t2 I get:
                G    loglik npm      BIC %class1
fit.g1.mlt.quad 1 -6405.571  10 12861.96     100
fit.g1.mlt.cub  1 -6389.833  15 12855.89     100

so the LRT would advocate that the cubic model is preferred (t3!=0) but when I use the summary of the cubic model I find it is not significant:
               coef      Se         Wald      p-value
int     37.03277 1.98134  18.691  0.00000
t           1.34681 1.09698   1.228    0.21954
t2         -0.19229 0.16652  -1.155  0.24819
t3          0.00799 0.00779   1.026  0.30498

How come?
Do you understand why?

Thank you!
Ronen

**Comment by CecileProust-Lima** [comment]
Dear Ronen, 

**1. why one function converges and not the other?**
lme, lmer and hlme do not use the same optimization algorithm. We use a Marquardt algorithm which we find very efficient. So it happens that my package converges when another might not converge (the reverse migh happen also). This is just a question of algorithm used. 
Anyway, this usually happen when the model is numerically complex to estimate. This might be the case here with your t^3 which must have very large values and thus be associated with very small parameter values. I can see it at the fixed effect level and the variance of the random effect associated is probably very very small. If you divide the time variable by 10 or 100, numerical issues should be reduced. 

**2. why is the cubic model better while the associated fixed effect is not?**
When you estimate a cubic model, you add a t^3 fixed effect (estimated at 0.00799) AND a random effect on t^3 with a variance and a covariance with the other random effects (that is 4 parameters). In total, the model has 5 additional parameters (15 versus 10 from your table). So in mean, the t^3 may not be significant but there are probably differences at the individual level. 

I hope this will help you. 
Best
Cécile

**Comment by rfluss** [comment]
thank you very much. for the helpful answer!
ronen
