### ISSUE TITLE
Variation accounted for by the model elements

### ISSUE THREAD

**Issue by pedreirajr** [CecileProust-Lima/lcmm#171]
Hi Cécile and Viviane,

Thank you again for your wonderful contribution with the lcmm package.
I know that this is a controversial topic in mixed models, but I was wondering if there is any straightforward way to compute how much variation is accounted for by each element in the model (e.g. covariates and latent class membership) as well as the residual variation not explained by the model.
I'm sorry if this question has been raised earlier, but I was not able to find anything regarding this topic.

Cheers,
Jorge

**Comment by CecileProust-Lima** [comment]
Hi Jorge, 
I have never thought about this. In multlcmm, we provide the % of explained variation as the percentage of variance (conditional to covariates) explained by the latent process (varExpl function). The numerator includes the random effects and correlation process, the denominator has in addition the measurement error. But not sure this is what you search for . 
best
Cécile

**Comment by pedreirajr** [comment]
Hi Cécile,

I understand. Thank you again!
