### ISSUE TITLE
GBTM with binary outcome?

### ISSUE THREAD

**Issue by iago-pssjd** [CecileProust-Lima/lcmm#174]
Hi, is it possible to make a Group-Based trajectory model for a binary outcome  with `lcmm`, like in SAS Proc Traj? If so, how should this be done?

Thank you!

**Comment by CecileProust-Lima** [comment]
Hi, 
a Group-Based trajectory model corresponds to a latent class mixed model without any random effect. So you should be able to estimate such model with lcmm for any type of outcome already handled in lcmm by specifying the argument: "random=~ - 1". 
For a binary outcome, the function to use will be lcmm function with the option link="threshold". That will define a latent class probit model. 
Cécile

**Comment by iago-pssjd** [comment]
Thanks!
