### ISSUE TITLE
Score test in jointlcmm

### ISSUE THREAD

**Issue by wy2020hku** [CecileProust-Lima/lcmm#175]
Dear Cécile and Viviane,

Thank you very much for the great lcmm package!
I am currently applying the jointlcmm model on my research and have some probelm with the score test. I always got significnat result in the score test indicating unsatisfied conditional independence assumption. After reading some examples using jointlcmm, I guess one reason should be the large size of my data (170,000 people with ~10 measurements for each people), I may need more groups due to the large size but models with too many classes (e.g. >10 classes) seem hard to converge. So I usually ended at 8 classes but get score test statistics around 100 which is undoubtedly significant.
May I seek your suggestion on any adjustment to improve the score test? Which part of the model should I adjust, different fixed model, different random effects, more survival model covariates, or even any adjustment on the dataset?

below is my model: (I have tried random effects to be either "1" or "1+time")

mod <- Jointlcmm(
  fixed = hba1c ~ ns(time, 3),
  mixture = ~ ns(time, 3),
  random = ~ 1,
  subject = "patient_id",
  ng = 6,
  data = data,
  survival = Surv(disease_time, disease) ~ hba1c_bl + disease_duration +
    age +
    sex +
    smoking_bl +
    systolic_bp_bl +
    diastolic_bp_bl +
    ldl_c_bl +
    bmi_bl +
    egfr_bl +
    charlson_index +
    insulin_b4 +
    dm_drug_b4 +
    ht_drug_b4 +
    lipid_drug_b4,
  logscale = FALSE,
  B = initmod,
  maxiter = 200,
nproc=16)

Thank you very much!

Best,
Yuan

**Comment by VivianePhilipps** [comment]
Hi Yuan,

this is effectively a consequence of the large sample size. Everything may be significant with huge data, so decisions can rely on other criteria/strategies.
In your case, you could for example compare the score test results of your different models (from 1 to 8 latent classes) and see if it stabilizes. The number of classes at which you see a stabilization may be considered as the number of classes from which the conditional independence is satisfied. 

Best,

Viviane

**Comment by wy2020hku** [comment]
Hi Viviane,

Thank you very much for your reply!
May I know if you have any recommandation on other criteria/strategies to test the contional independence assumption without affected by the large sample size?
I can find stable score test results in my models with >4 latent classes, but I am not sure whether I can directly say these models satisfy the conditional independence assumption. Is there any

**Comment by wy2020hku** [comment]
Hi Viviane,

Thank you very much for your reply!
May I know if you have any recommandation on other criteria/strategies to test the contional independence assumption without affected by the large sample size? (currently I only know, from your articles, that I can also use a Cox regression model to ensure the conditional independence with insignificant coefficient of the longitudinal variable when adjusted with the obtained latent clases, however, due to the large sample size, the coefficients are always significant)
I can usually find stable score test results in my models with >4 latent classes, but I am not sure whether I can directly say these models already satisfy the conditional independence assumption. Is there any reference that can support me to satisfy the conditional independence assumption using this way?

Best,
Yuan

**Comment by VivianePhilipps** [comment]
Hi,

I have no reference to suggest, I'm sorry. I'm not used to work with large datasets, so I don't know the literature about it.

Viviane

**Comment by wy2020hku** [comment]
Thank you very much Viviane!

Yuan

**Comment by wy2020hku** [comment]
> Hi Yuan,
> 
> this is effectively a consequence of the large sample size. Everything may be significant with huge data, so decisions can rely on other criteria/strategies. In your case, you could for example compare the score test results of your different models (from 1 to 8 latent classes) and see if it stabilizes. The number of classes at which you see a stabilization may be considered as the number of classes from which the conditional independence is satisfied.
> 
> Best,
> 
> Viviane

Hi Viviane,

Sorry for reopenning this question again. May I ask more about why we can consider the model with a stabilization of score test results as satisfying the conditional independence? 
Although the decline of score test statistics become slower or unobservable, it may still be possible to reach insignificant bound when we have many classes (like 200, 1000 classes). I noticed that this point was also mentioned in the vignettes for JointLcmm and sincerely hope to know the reason.
Thank you in advance for your help!

Yuan

**Comment by VivianePhilipps** [comment]
Hi,

if you look at the plot in the vignette, according to the shape of the curve, there is an asymptote at about 35. So, for any number of latent classes >4 you expect to have a score test of 35.
And latent class joint models assume that for a sufficient number of classes, the conditional independence is satisfied.
In the vignette's example, by extrapolation, the score test for this sufficient number of classes will be around 35. But you already reach this values with 4 classes. So, the 4 classes model is chosen, even if the significance level is not reached.

Viviane
