### ISSUE TITLE
`predictL` does not work without random effects (and is `predictY` output right?)

### ISSUE THREAD

**Issue by iago-pssjd** [CecileProust-Lima/lcmm#177]
Hi @CecileProust-Lima ,

Following your suggestion in https://github.com/CecileProust-Lima/lcmm/issues/174#issuecomment-1525788915, I tried a GBTM for a binary outcome without random effects. Then, I was looking for some plots and I got an error trying `predictL`:

```r
plot(predictL(m.ids, var.time = 'time', newdata = lcmmData, bty = 'l'))
Error in if (colnames(X_random)[1] == "(Intercept)") { : 
  argument is of length zero
```
Therefore, is seems `predictL` does not work if there are no random effects.

Beyond that,  output produced by `plot(m.ids, which = "linkfunction")` does not tell much, while the most interesting `plot(predictY(m.ids, var.time = 'time', newdata = lcmmData, bty = 'l'))` I do not know if it is correct (since (1) `predictY` "computes the predicted values of the longitudinal marker", (2) the longitudinal marker only takes values 0 and 1, and however (3) the plot shows predicted values between 0 and 1!!! (or are they probabilities?)).

Is there any other plotting option for such a model?

Thank you!

**Comment by VivianePhilipps** [comment]
Hi,

I corrected the predictL function, it should now work fine even without random effects.
The predictY function was already correct, we manage the model differently between predictL and predictY that's why you didn't get the same error.

Best,

Viviane

**Comment by iago-pssjd** [comment]
Thanks @VivianePhilipps 

> The predictY function was already correct, we manage the model differently between predictL and predictY that's why you didn't get the same error.

How should I interpret the next output, which is the same than for `predictL` except for the y axis title/label and scale, taking into account that in the dataset the outcome `X1` only takes values 0 and 1?

```r
m15<-lcmm(X1~Time+I(Time^2),random=~1,subject='ID',ng=1
,data=data_lcmm,link="thresholds",maxiter=100)
predictY(m15, var.time = 'Time', newdata = data_lcmm, bty = 'l') |> plot()
```
![image](https://github.com/CecileProust-Lima/lcmm/assets/40892925/597c52b6-0c5d-479e-b1dc-fcd34449ef17)

**Comment by VivianePhilipps** [comment]
The plot associated to the predictY function assumes that you have the values for a single subject. In your example you make the prediction for all the subjects in the sample, that's why you have this result.
It would rather be used for a single (fictive) subject :
 `plot(predictY(m15, newdata=data.frame(Time=seq(0,3,0.2))))`

This gives you the trajectory over time estimated by the model. Values are between 0 and 1 because we predict the expectancy of the outcome, not directly the binary response 0/1.

Viviane
