### ISSUE TITLE
plot for mean prediction

### ISSUE THREAD

**Issue by i2sunshine** [CecileProust-Lima/lcmm#18]
Dear Dr. Proust,

I am trying to partition patients' trajectories of a biomarker by using your LCMM package, and having a trouble with plotting mean predictions by command "plot".  

My dataset "testdata" includes longitudinal data for the biomarker for ~1000 patients coming from 2 different centers, where outcome "biomarker" is a continuous variable, dummy variable "center" is used to adjust center effect, and variable "interval_year" is time variable in the latent class model. Patient's trajectory is assumed a quadratic class-specific mixed model below.

Here are my R scripts:
`m1=hlme(fixed = biomarker ~ center + interval_year + I(interval_year^2), random = ~interval_year, subject = "Study_ID", ng = 1, idiag = FALSE, nwg = FALSE, cor = AR(interval_year), data = testdata)

#Number of latent class is assumed to be 4.
#Use grid search method to estimate parameters to avoid local maxima.
m=gridsearch(hlme(fixed = biomarker~ center + interval_year+ I(interval_year^2), mixture = ~ interval_year+ I(interval_year^2),  random = ~interval_year, subject = "Study_ID", ng = 4, idiag = FALSE, nwg = FALSE, cor = AR(interval_year), data = testdata),  rep=10, maxiter=50, minit=m1)

##I am able to plot residuals 
plot(m)

##Failed to plot mean predictions
plot(m, which("fit"), var.time="interval_year", ylab="biomarker", xlab="follow-up (by year)")
`
After running above plot for mean predictions, I got an error message **Error in data[, var.time] : object of type 'symbol' is not subsettable** 

Do you have any idea why plotting for prediction cannot work in my case? Thanks a lot!

**Comment by CecileProust-Lima** [comment]
Thank you for your feedback and sorry for this late response. Actually, we tried to replicate your problem but we did not encounter it in our tests. 
As the data are necessary to use the fit function. If you suppressed them from your session, that might induce those issues. 
Hope this will help, 
Cécile

**Comment by CecileProust-Lima** [comment]
You may also use the option returndata=TRUE in the latest version ...

**Comment by i2sunshine** [comment]
There is no problem after updating to the latest LCMM and changing "returndata=TRUE". Thanks a lot!
