### ISSUE TITLE
Interpreting coefficient classmb

### ISSUE THREAD

**Issue by gabrielle1441** [CecileProust-Lima/lcmm#180]
How do we interpret the coefficients in the fixed effects in the class-memberhsip model (see below for an example of the code we ran). 
Do we interpret those like coefficients in a multinomial logistic regression (meaning we use the exponent of -0.05 for age class 2 for example in the output pasted below, to produce odds ratio - and interpret it like a decreased likelihood of belonging to class 2 compared to class 3 for every one year increase in age)?
Or do we interpret that the fixed effects relate to the Y and not to the class membership like in a traditional model. So for example, the -0.05 age coefficient for class 2 would mean that compared to class 3, there is a 0.05 shift down in the trajectory when age increases by one year. 

Thank you very much for your time,
Gabrielle

lcmm(fixed = PainAvg ~ POD + POD2, mixture = ~POD + POD2,  

    subject = "id", classmb = ~Age + SexR + sxR2d + MAAS_Mean.1 +

        SCL90R_SOM.1 + SPTS_Total.1 + HADS_Anx.1 + HADS_Dep.1,

    ng = 3, idiag = T, data = trajp, maxiter = 100)

Fixed effects in the class-membership model:

(the class of reference is the last class)

 

                        coef      Se    Wald p-value

intercept class1    -4.01651 1.93209  -2.079 0.03763

intercept class2    -4.09935 1.74775  -2.345 0.01900

Age class1          -0.00888 0.01655  -0.536 0.59162

Age class2           -0.05791 0.01494   3.876 0.00011

SexR1 class1        -0.83704 0.60360  -1.387 0.16552

SexR1 class2         0.01780 1.01585   0.018 0.98602

sxR2d2 class1        2.14867 0.74239   2.894 0.00380

sxR2d2 class2        0.49489 0.36416   1.359 0.17415

sxR2d3 class1        3.24066 1.06888   3.032 0.00243

sxR2d3 class2        0.77410 0.86880   0.891 0.37293

sxR2d4 class1        2.18440 0.86682   2.520 0.01173

sxR2d4 class2        0.16909 0.54256   0.312 0.75530

MAAS_Mean.1 class1  -0.00858 0.27229  -0.032 0.97485

MAAS_Mean.1 class2  -0.10554 0.21093  -0.500 0.61684

SCL90R_SOM.1 class1  0.09603 0.03027   3.172 0.00151

SCL90R_SOM.1 class2 -0.06135 0.02792  -2.197 0.02800

SPTS_Total.1 class1  0.06207 0.02965   2.094 0.03628

SPTS_Total.1 class2  0.04972 0.02584   1.924 0.05435

HADS_Anx.1 class1   -0.04743 0.07811  -0.607 0.54372

HADS_Anx.1 class2    0.00280 0.04808   0.058 0.95348

HADS_Dep.1 class1   -0.00900 0.09941  -0.091 0.92783

HADS_Dep.1 class2    0.01022 0.07474   0.137 0.89129

 

Fixed effects in the longitudinal model:

 

                                     coef      Se    Wald p-value

intercept class1 (not estimated)        0                       

intercept class2                 -2.12447 0.51743  -4.106 0.00004

intercept class3                  1.15620 0.43161   2.679 0.00739

POD class1                       -0.06889 0.21110  -0.326 0.74417

POD class2                       -0.20469 0.17715  -1.155 0.24790

POD class3                       -1.63244 0.12041 -13.557 0.00000

POD2 class1                      -0.00368 0.02923  -0.126 0.89976

POD2 class2                       0.01477 0.02184   0.676 0.49884

POD2 class3                       0.16470 0.01606  10.256 0.00000

**Comment by Dr-BoBo** [comment]
> [CecileProust-Lima](/CecileProust-Lima)

Hi, Cécile,

Thank you for your response. I hope you would not mind if I follow up on the question.

My team is wondering whether there would be anywhere in the outcome Large LCMM file addressing the increment of the multinomial logistic mode.
For example, in OP's outcome, what's the increment of age? 

Thank you in advance.

**Comment by CecileProust-Lima** [comment]
Sorry for not answering earlier. I will answer directly in the #189
