### ISSUE TITLE
Strange behavior from predictY and predictL with Jointlcmm model--does the starting time of the survival submodel need to be the same as the longitudinal submodel?

### ISSUE THREAD

**Issue by sw3554** [CecileProust-Lima/lcmm#181]
Dear Cécile and Viviane,

Thank you very much for this great package and your help on these forums!

I have encountered an issue with a Jointlcmm model that confuses me. I have fit two models, model1 and model2. The two models have different survival endpoints, but the other parts of the model structures are the same. Model1 was fit on the whole study population, while model2 was fit on a subgroup ensuring the earliest start time of the survival submodel was the same as that of the longitudinal submodel. So in model1 the longitudinal data starts at time point 0, while some of the survival data starts at a negative timepoint.

Both models converged. Model2 does not have any problem with predictY and predictL. However when I use predictY with model1 it randomly gets stuck, even when draws=F. For example, I've tested using one row of newdata, sometimes the results are instant, and sometimes it gets stuck, even when I don't change anything. When I get results, it doesn't seem consistent with what I would expect form the coefficients. When draws=T it always gets stuck. Using predictL gives me the error "Error in newdata1[, k] : subscript out of bounds". (predictlink works normally)

It seems the biggest difference between the two models is whether the starting time of the survival data is negative, so I wondered if that might be the problem, although I'm not sure why it would affect predictL and predictY.

Thank you so much!

For reference, I've pasted the summaries for model1 and model2 below.

**Model1:**
Joint latent class model for quantitative outcome and competing risks 
     fitted by maximum likelihood method 
 
Jointlcmm(fixed = IC ~ age_tf + gender * age_tf + ci * age_tf, 
    mixture = ~age_tf, random = ~age_tf, subject = "ID_num", 
    ng = 3, survival = Surv(init_age_tf, event_age_tf, event) ~ 
        gender + ci, hazard = "3-quant-piecewise", hazardtype = "PH", 
    link = "beta", data = sl_dat_outcomes)
 
Statistical Model: 
     Dataset: sl_dat_outcomes 
     Number of subjects: 6750 
     Number of observations: 10900 
     Number of latent classes: 3 
     Number of parameters: 27  
     Event 1: 
        Number of events: 1699
        Proportional hazards over latent classes and 
        Piecewise constant baseline risk function with nodes 
        -0.4 0.6 2.7  
     Link function for IC: Standardised Beta CdF 
 
Iteration process: 
     Convergence criteria satisfied 
     Number of iterations:  4 
     Convergence criteria: parameters= 6.1e-14 
                         : likelihood= 5e-10 
                         : second derivatives= 1.3e-08 
 
Goodness-of-fit statistics: 
     maximum log-likelihood: -23015.61  
     AIC: 46085.22  
     BIC: 46269.29  
 
 
Maximum Likelihood Estimates: 
 
Fixed effects in the class-membership model:
(the class of reference is the last class) 

                     coef      Se    Wald p-value
intercept class1  2.34432 0.22883  10.245 0.00000
intercept class2  3.28221 0.29737  11.038 0.00000

Parameters in the proportional hazard model:

                               coef      Se    Wald p-value
event1 +/-sqrt(piecewise1)  0.51322 0.03765  13.631 0.00000
event1 +/-sqrt(piecewise2)  0.64051 0.04300  14.897 0.00000
event1 SurvPH class1        0.45341 0.05812   7.802 0.00000
event1 SurvPH class2        1.49155 0.09559  15.604 0.00000
gender2                     0.62015 0.06631   9.352 0.00000
ci1                         0.80587 0.12872   6.261 0.00000
ci2                         1.55702 0.11906  13.077 0.00000

Fixed effects in the longitudinal model:

                                     coef      Se    Wald p-value
intercept class1 (not estimated)        0                        
intercept class2                 -1.16730 0.10675 -10.935 0.00000
intercept class3                  1.73107 0.13287  13.028 0.00000
age_tf class1                    -1.09489 0.07277 -15.046 0.00000
age_tf class2                    -1.07664 0.09391 -11.464 0.00000
age_tf class3                    -1.20174 0.12683  -9.476 0.00000
gender2                          -0.83922 0.05884 -14.264 0.00000
ci1                              -0.62801 0.08086  -7.767 0.00000
ci2                              -1.37808 0.08853 -15.566 0.00000
age_tf:gender2                   -0.05755 0.05857  -0.983 0.32584
age_tf:ci1                        0.06502 0.07719   0.842 0.39965
age_tf:ci2                        0.13693 0.08069   1.697 0.08972

Variance-covariance matrix of the random-effects:
          intercept  age_tf
intercept   0.47076        
age_tf     -0.03031 0.00195

Residual standard error (not estimated) = 1

Parameters of the link function:

          coef      Se    Wald p-value
Beta1  0.02480 0.03701   0.670 0.50281
Beta2 -0.19346 0.06876  -2.814 0.00490
Beta3  0.65143 0.01458  44.691 0.00000
Beta4  0.08250 0.00346  23.845 0.00000

**Model2:**
Joint latent class model for quantitative outcome and competing risks 
     fitted by maximum likelihood method 
 
Jointlcmm(fixed = IC ~ age_tf + gender * age_tf + ci * age_tf, 
    mixture = ~age_tf, random = ~age_tf, subject = "ID_num", 
    ng = 3, survival = Surv(init_age_tf, event_age_tf, ADL_impair) ~ 
        gender + ci, hazard = "3-quant-piecewise", hazardtype = "PH", 
    link = "beta", data = sl_dat_sub)
 
Statistical Model: 
     Dataset: sl_dat_sub 
     Number of subjects: 2585 
     Number of observations: 6033 
     Number of latent classes: 3 
     Number of parameters: 27  
     Event 1: 
        Number of events: 443
        Proportional hazards over latent classes and 
        Piecewise constant baseline risk function with nodes 
        0 0.8 2.7  
     Link function for IC: Standardised Beta CdF 
 
Iteration process: 
     Convergence criteria satisfied 
     Number of iterations:  12 
     Convergence criteria: parameters= 1.2e-10 
                         : likelihood= 1e-06 
                         : second derivatives= 2.2e-05 
 
Goodness-of-fit statistics: 
     maximum log-likelihood: -12936.42  
     AIC: 25926.84  
     BIC: 26084.99  
     Score test statistic for CI assumption: 4.162 (p-value=0.1248) 
 
Maximum Likelihood Estimates: 
 
Fixed effects in the class-membership model:
(the class of reference is the last class) 

                     coef      Se   Wald p-value
intercept class1  1.21352 0.39482  3.074 0.00212
intercept class2  1.09287 0.61951  1.764 0.07772

Parameters in the proportional hazard model:

                               coef      Se   Wald p-value
event1 +/-sqrt(piecewise1)  0.23100 0.04989  4.630 0.00000
event1 +/-sqrt(piecewise2)  0.33829 0.07259  4.660 0.00000
event1 SurvPH class1        1.16051 0.45659  2.542 0.01103
event1 SurvPH class2        2.07293 0.41578  4.986 0.00000
gender2                     0.41092 0.11434  3.594 0.00033
ci1                         0.30772 0.14265  2.157 0.03099
ci2                         0.88359 0.13352  6.618 0.00000

Fixed effects in the longitudinal model:

                                     coef      Se   Wald p-value
intercept class1 (not estimated)        0                       
intercept class2                 -1.09211 0.17756 -6.151 0.00000
intercept class3                  0.91165 0.26027  3.503 0.00046
age_tf class1                    -0.87989 0.09368 -9.393 0.00000
age_tf class2                    -0.87074 0.13232 -6.581 0.00000
age_tf class3                    -0.59668 0.16166 -3.691 0.00022
gender2                          -0.43257 0.07733 -5.594 0.00000
ci1                              -0.25431 0.08788 -2.894 0.00380
ci2                              -0.83931 0.09245 -9.079 0.00000
age_tf:gender2                   -0.06105 0.08986 -0.679 0.49685
age_tf:ci1                        0.04762 0.10006  0.476 0.63411
age_tf:ci2                        0.13646 0.09999  1.365 0.17235

Variance-covariance matrix of the random-effects:
          intercept  age_tf
intercept   0.46647        
age_tf     -0.11951 0.03062

Residual standard error (not estimated) = 1

Parameters of the link function:

          coef      Se   Wald p-value
Beta1 -0.00095 0.03016 -0.032 0.97478
Beta2 -0.35330 0.07518 -4.700 0.00000
Beta3  0.61870 0.02094 29.548 0.00000
Beta4  0.09508 0.00412 23.086 0.00000

**Making newdata and using predictY and predictL** with the two models (age_tf is the age starting from 60 counted in decades):
min_age<-60
test_age<-60:85
test<-data.frame(age_tf=(test_age-min_age)/10,gender=1,ci=0)
predictY(x, newdata=test, draws=F,var.time="age_tf")
predictL(x, newdata=test, draws=F,var.time="age_tf")

**Comment by VivianePhilipps** [comment]
Hi,

sorry, I could not reproduce the error, so I won't be able to investigate it further. 
But I don't think it is related to the negative entry time. To check it you could put model2's estimates in model1 and see what happens on the predictL/Y functions : 

 z <- model1$call
 z$B <- model2$best
 z$maxiter <- 0
 m <- eval(z)

 predictY(m, newdata=test, draws=FALSE)

**Comment by sw3554** [comment]
Thank you, I tried this, predictL still gives the error Error in newdata1[, k] : subscript out of bounds.

PredictY no longer gets stuck, even with draws=T. However there is still something strange happening. Since this is using model2's parameters, the Y for the largest class should go from about 7 to 5, but the actual results are around 7 to 1. In addition, when I run predictY several times, more and more of the result values get replaced by 13 (the max value of Y). Could this be something going wrong with the link function transformation?

Here are the results I got when running predictY several times:
Ypred_class1 Ypred_class2 Ypred_class3
 [1,]     7.802615    6.0507826     9.223360
 [2,]     7.529098    5.7760084     9.005505
 [3,]     7.254215    5.5017900     8.785343
 [4,]     6.978278    5.2284278     8.562998
 [5,]     6.701608    4.9562264     8.338754
 [6,]     6.424514    4.6854989     8.112852
 [7,]     6.147301    4.4165670     7.885507
 [8,]     5.870272    4.1497656     7.656923
 [9,]     5.593729    3.8854647     7.427285
[10,]     5.317977    3.6240303     7.196787
[11,]     5.043328    3.3657597     6.965616
[12,]     4.770090    3.1110572     6.733956
[13,]     4.498580    2.8603718     6.501985
[14,]     4.229128    2.6142469     6.269882
[15,]     3.962077    2.3735831     6.037823
[16,]     3.697797    2.1383001     5.805986
[17,]     3.436708    1.9088195     5.574547
[18,]     3.179115    1.6859079     5.343684
[19,]     2.925430    1.4707428     5.113576
[20,]     2.676131    1.2659861     4.884408
[21,]     2.431811    1.0692139     4.656365
[22,]     2.193425    0.8808908     4.429635
[23,]     1.960832    0.7026162     4.204409
[24,]     1.734588    0.5391599     3.980888
[25,]     1.515606    0.3904662     3.759281
[26,]     1.305859    0.2506387     3.539809

      Ypred_class1 Ypred_class2 Ypred_class3
 [1,]     7.802615    6.0507826     9.223360
 [2,]     7.529098    5.7760084     9.005505
 [3,]    13.000000   13.0000000    13.000000
 [4,]     6.978278    5.2284278     8.562998
 [5,]     6.701608    4.9562264     8.338754
 [6,]     6.424514    4.6854989     8.112852
 [7,]    13.000000   13.0000000    13.000000
 [8,]     5.870272    4.1497656     7.656923
 [9,]     5.593729    3.8854647     7.427285
[10,]     5.317977    3.6240303     7.196787
[11,]     5.043328    3.3657597     6.965616
[12,]     4.770090    3.1110572     6.733956
[13,]    13.000000   13.0000000    13.000000
[14,]     4.229128    2.6142469     6.269882
[15,]     3.962077    2.3735831     6.037823
[16,]     3.697797    2.1383001     5.805986
[17,]    13.000000   13.0000000    13.000000
[18,]     3.179115    1.6859079     5.343684
[19,]    13.000000   13.0000000    13.000000
[20,]     2.676131    1.2659861     4.884408
[21,]     2.431811    1.0692139     4.656365
[22,]     2.193425    0.8808908     4.429635
[23,]    13.000000   13.0000000    13.000000
[24,]     1.734588    0.5391599     3.980888
[25,]    13.000000   13.0000000    13.000000
[26,]     1.305859    0.2506387     3.539809

      Ypred_class1 Ypred_class2 Ypred_class3
 [1,]    13.000000    13.000000    13.000000
 [2,]    13.000000    13.000000    13.000000
 [3,]    13.000000    13.000000    13.000000
 [4,]    13.000000    13.000000    13.000000
 [5,]    13.000000    13.000000    13.000000
 [6,]     6.424514     4.685499     8.112852
 [7,]    13.000000    13.000000    13.000000
 [8,]    13.000000    13.000000    13.000000
 [9,]    13.000000    13.000000    13.000000
[10,]    13.000000    13.000000    13.000000
[11,]    13.000000    13.000000    13.000000
[12,]    13.000000    13.000000    13.000000
[13,]    13.000000    13.000000    13.000000
[14,]    13.000000    13.000000    13.000000
[15,]    13.000000    13.000000    13.000000
[16,]    13.000000    13.000000    13.000000
[17,]    13.000000    13.000000    13.000000
[18,]     3.179115     1.685908     5.343684
[19,]    13.000000    13.000000    13.000000
[20,]    13.000000    13.000000    13.000000
[21,]    13.000000    13.000000    13.000000
[22,]    13.000000    13.000000    13.000000
[23,]    13.000000    13.000000    13.000000
[24,]    13.000000    13.000000    13.000000
[25,]    13.000000    13.000000    13.000000
[26,]    13.000000    13.000000    13.000000

**Comment by sw3554** [comment]
I finally found out what was wrong. It turns out model1$levels$levelsdata was all null, even though the summary shows different levels for ci and gender. So I did model1$levels$levelsdata<-model2$levels$levelsdata and now everything is fine. Weird but glad to have it fixed now.
