### ISSUE TITLE
Using Imports instead of Depends in DESCRIPTION

### ISSUE THREAD

**Issue by Gootjes** [CecileProust-Lima/lcmm#184]
I noticed that when loading lcmm, some packages are attached to the session.
Woult it be possible to change the DESCRIPTION to import the packages instead (using Imports: instead of Depends: )?
https://stackoverflow.com/questions/8637993/better-explanation-of-when-to-use-imports-depends

**Comment by VivianePhilipps** [comment]
Hi,

thank you for your message, I will look at it.

Vivane

**Comment by VivianePhilipps** [comment]
Hi,

the commit fbcfd1e7e344975f7e01e998ce8c878f7cf3c67a includes these changes.
Thanks

Viviane
