### ISSUE TITLE
JointLCMM applied to the number of abnormal values of a given biomarker

### ISSUE THREAD

**Issue by Magicsoso** [CecileProust-Lima/lcmm#186]
Dear Cecile and Viviane,

I'm contacting you because I've read your article on the subject (Joint latent class models for longitudinal and time-to-event data: a review) and would like to use this method to analyze my data. If possible, I'd also like to ask you for some expert advice.

Context: 

I would like to know whether it is possible (if this is correct and in line with the method) in a latent class joint model to model during the mixed regression step not the trajectory of a biomarker (e.g. CRP) directly, but rather the ratio of the number of times with an abnormal CRP value to the number of data available at time t. 
Obviously, this ratio varies over the follow-up of the patient (e.g.: at D1, the patient has 1 abnormal CRP value out of 1 measurement at D1; at D2, the patient still has only 1 abnormal CRP value out of 2 measurements (because at D2 the value obtained is normal); at D3: the patient has 2 abnormal values out of 3 measurements (because at D3 a new abnormal value is obtained); etc.).

Objective:
The ultimate objective would ideally be to obtain a hazard ratio corresponding to patients with a high ratio of abnormal CRP values associated with an increased risk of event, compared with patients with a lower ratio of abnormal CRP values.

I look forward to hearing from you,
Thank you in advance !

**Comment by CecileProust-Lima** [comment]
Hi, 
your analysis seems very specific. I am not sure this design really fits in the setting of lcmm. We intend to model data collected at a time t and not an accumulation up to time t ... Really sorry. 
Cécile

**Comment by CecileProust-Lima** [comment]
No, really sorry. 
Cécile

**Comment by Magicsoso** [comment]
Thank you again for your time
Sonia
