### ISSUE TITLE
Estimating fixed effects on the latent trait from multlcmm

### ISSUE THREAD

**Issue by chrisraynerr** [CecileProust-Lima/lcmm#187]
Hello,

I have a multlcmm model:
m <- multlcmm(item1+item2+item3+item4+item5 ~ age + cov1 + cov2,  random=~age, subject="ID", link="threholds")

I now want to estimate the effect of another variable (var1) on the latent trait. I suppose I have two options. The first is to re-run the model including var1. However, there are many individuals and observations. Previously this model took 6 days to run.

The other option I have been exploring is using the predicted values from m (m$pred$pred_ss or m$pred_pred_m). Would the correct approach be, to include the marginal or the subject specific predictions:

fsc <-  m$pred_pred_m
m2 <-  lme(fsc ~ var1, random = (age|ID)

Is this ok, or is it a silly idea?
Many thanks!
Chris

**Comment by VivianePhilipps** [comment]
Hello,

a two stage procedure is feasible, using the subject specific prediction from your multlcmm model.

But reestimating a model with a supplementary covariate may not be so long of you use the previous estimations as starting point. 
In the following code, I add the covariate 'cov3'. I used mm's parameters as starting value, except for cov3 for which the value is 0 :

`binit <- c(mm$best[1:3], 0, mm$best[4:length(mm$best)])
`
`mcov3 <- multlcmm(item1+item2+item3+item4+item5 ~ age + cov1 + cov2 + cov3, random=~age, subject="ID", link="threholds", B=binit)`

If you have multiple cores on your computer, you can also use a parallel setting with the argument nproc. This will speed up the estimation.

Best,

Viviane

**Comment by chrisraynerr** [comment]
Fantastic! Thank you so much!!
