### ISSUE TITLE
Accessing event free probabilities

### ISSUE THREAD

**Issue by KalongoHamusonde** [CecileProust-Lima/lcmm#188]
Dear Cecile and Viviane,
In the Jointlcmm function, when the event free probabilities are plotted using the plot(x, which = “survival”), how do I find the dataset with the probabilities for each class per time point ?
Thanks

**Comment by VivianePhilipps** [comment]
Hello,

the predSurv output of the Jointlcmm object is used to produce this graphe. The first column is the time, then the hazard and the cumulative hazard. To check it :

`mj <- jlcmm(Ydep1~Time, random=~1, subject="ID", data=data_lcmm, survival=Surv(Tentry,Tevent,Event)~X1)
`
`plot(mj, "survival")`
`lines(mj$predSurv[,1], exp(-mj$predSurv[,3]), lty=5, col=2)
`

Best,

Viviane
