### ISSUE TITLE
Interpreting coefficient classmb - the increment of the multinomial logistic model

### ISSUE THREAD

**Issue by Dr-BoBo** [CecileProust-Lima/lcmm#189]
Dear Cecile and Viviane,

In your kind response to a previous issue posted by another user at #180 , you answered, "_This is a multinomial logistic model with the classical interpretation in terms of odds (and odds ratios) comparing the probability of being in class g with the probability of being in the reference class (last one in the package)._"

Since my comment under #180 has not been answered for three weeks, I hope you would not mind me opening a new issue.

My team is wondering whether there would be anywhere in the outcome Large LCMM file addressing the increment of the multinomial logistic mode.
Taking below #180 as an example, what's the increment of age?

`lcmm(fixed = PainAvg ~ POD + POD2, mixture = ~POD + POD2, subject = "id", classmb = ~Age + SexR + sxR2d + MAAS_Mean.1 + SCL90R_SOM.1 + SPTS_Total.1 + HADS_Anx.1 + HADS_Dep.1, ng = 3, idiag = T, data = trajp, maxiter = 100)`
Fixed effects in the class-membership model:
(the class of reference is the last class)
                    coef      Se    Wald p-value
intercept class1 -4.01651 1.93209 -2.079 0.03763
intercept class2 -4.09935 1.74775 -2.345 0.01900
**Age class1 -0.00888 0.01655 -0.536 0.59162
Age class2 -0.05791 0.01494 3.876 0.00011**

Thank you in advance. 
Best Regards,
Bo

**Comment by CecileProust-Lima** [comment]
Dear Bo, 
I am sorry, I don't understand the sentence: "there would be anywhere in the outcome Large LCMM file addressing the increment of the multinomial logistic mode."
In your model, you have chosen a certain unit for Age variable. The coefficient associated with age in each class is interpreted for a unit increase of this variable. So -0.05791 means that those who are older are less likely to belong to class 2 compared to class 3 with an odds-ratio of exp(-0.05791) for each age unit increase. 
I am afraid we do not have any detailed documentation on this specific classmb interpretation. You could look though at multinomial models, this should be the exact same interpretation. 
Cécile
