### ISSUE TITLE
Generation of random starting values

### ISSUE THREAD

**Issue by hlennon** [CecileProust-Lima/lcmm#19]
Dear Dr Proust-Lima, 

I’ve been working with the lcmm package to derive latent class trajectories and your package is great and has been very useful and well-used! However, I have a question for which I could not find an answer in the documentation of the package. 

I would like to know more about the process behind the generation of random starting values. 

I cannot locate the function random() within base R or within your lcmm package which seems to be used within the gridsearch function, in the line 
```{r}
mc$B <- substitute(random(minit), environment())
```

An extract within the hlme function code that  I found is: 

```{r}
#gestion de B=random(mod)
        Brandom <- FALSE
        if(length(cl$B)==2)            {
                if(class(eval(cl$B[[2]]))!="hlme")
 stop("The model specified in B should be of class hlme")
                if(as.character(cl$B[1])!="random") 
stop("Please use random() to specify random initial values”) .......
```

Also I have read the reference provided of Biernacki et al., (2003) for variants of the EM algorithm and still it is not much clearer to me, how this is implemented, and accompanying vignette  discusses the iterative Marqardt algorithm for parameter estimation - pithing the Newton-Raphson family.

I’m not sure my question is clear enough. I can try to make it clearer if needed of course.

Thanks in advance for your help.

Best regards 
Hannah

**Comment by CecileProust-Lima** [comment]
Dear Hannah, 
the choice of initial values is explained in the companion paper of lcmm. you can download it at: [https://www.jstatsoft.org/article/view/v078i02](https://www.jstatsoft.org/article/view/v078i02)

Section 4.5 (page 17) should answer your question. random() is an internal function of lcmm which draws random initial values from the asymptotic distribution of the model under G=1.

I hope this will help,
Best
Cécile
