### ISSUE TITLE
Parallel process latent class growth analysis

### ISSUE THREAD

**Issue by Sumire0612** [CecileProust-Lima/lcmm#191]
Dear Cécile and Viviane,

Hello. I am a postdoc conducting a cohort study using a latent growth curve model.

I would like to use the "parallel process latent class growth analysis" method to classify clusters using several assessment items. Mplus seems to have a package that can use this method (Parallel process latent class growth analysis in Mplus version 7.11; Muthen, L. K., & Muthen, B. (1998-2007)). Can the LCMM package use this method? If so, do you have a description of the code?I would appreciate it if you could help me with the above. Thank you in advance.

Sincerely yours

**Comment by VivianePhilipps** [comment]
Hi,

the mpjlcmm function estimates multivariate models.  With mpjlcmm, you will be able to explore the latent classes related to multiple outcomes. However, this function only treats continuous outcomes, it will not deal with ordinal or binary  outcomes.
Please refer to the dedicated vignette : https://cecileproust-lima.github.io/lcmm/articles/multivariate_latent_class_model_with_mpjlcmm.html

Best,

Viviane

**Comment by Sumire0612** [comment]
Dear  Viviane,

Thank you for contacting us.
We appreciate your very valuable information. 
We will proceed with the analysis in this way.

Sincerely yours
