### ISSUE TITLE
Why the class-specific mean predicted trajectory plot is weird when including covariates in the models

### ISSUE THREAD

**Issue by KateLTran** [CecileProust-Lima/lcmm#192]
Hello,

First I'd like to thank you for your great package.

I'm working on a project where I try to get trajectories of General_SES (continuous outcome) over 3 timepoints (baseline, 1-year, and 2-year follow-up). In the models, I coded timepoints as 0, 1, and 2. I also included covariates (age, sex, race, ethnicity) and all of them are binary variables. 

I have several questions:
1. Why when I treat the timepoint variable as continuous or factor, I got similar (weird) results?
2. Why is the plot so weird (please see the attached plot)? This happen when I included covariates in the model.

These are my models:

`set.seed(2023)`

`lcga1_gen_classmb <- hlme(fixed = General_SES ~ Timepoint_numeric + age_year + sex_br + race_black + race_white + ethnicity_hisp,
                  random = ~1,
                  subject = "ID_num",
                  ng = 1,
                  nwg = FALSE,
                  data = data_train)`

`lcga3_gen_classmb <- hlme(General_SES ~ Timepoint_numeric + age_year + sex_br + race_black + race_white + ethnicity_hisp,
                          classmb = ~ age_year + sex_br + race_black + race_white + ethnicity_hisp,
                          subject = "ID_num", 
                          ng = 3, 
                          random = ~1,
                          data = data_train,
                          mixture = ~1,
                          B = lcga1_gen_classmb)`

`pred1 <- predictY(lcga3_gen_classmb, newdata = data_train)`
`plot(pred1, col=c("deeppink","deepskyblue"), lty=1, lwd=2)`

<img width="760" alt="image" src="https://github.com/CecileProust-Lima/lcmm/assets/93722899/1bd94201-2f95-4158-bde0-7502d861544f">

3. Why when I take the covariates out of the models and only keep in class membership, the plot looks different?
`lcga4_gen_classmb_tp <- hlme(General_SES ~ Timepoint_numeric,
                          classmb = ~ age_year + sex_br + race_black + race_white + ethnicity_hisp,
                          subject = "ID_num", 
                          ng = 4, 
                          random = ~1,
                          data = data_train,
                          mixture = ~1,
                          B = lcga1_gen_classmb_tp)`

![image](https://github.com/CecileProust-Lima/lcmm/assets/93722899/31d20da7-2669-4e66-a48a-3306dde02121)

I would like to thank you very much for your help.

Best regards,
Kate

**Comment by VivianePhilipps** [comment]
Hi,

this is because you compute and plot the predictions for all the subjects. The predictY function should be used with a single subject at once as explain in #177.

Viviane

**Comment by KateLTran** [comment]
Hi Viviane,

Thank you very much for your feedback.

Best regards,
Kate Tran
