### ISSUE TITLE
How to run a stratified hlme model?

### ISSUE THREAD

**Issue by KateLTran** [CecileProust-Lima/lcmm#193]
Hi Cécile and Viviane,

I have another question regarding my project on trajectories of a general factor (continuous outcome, General_SES, a factor score from a factor analysis). 

I need to run a hlme model stratified by race (Hispanic, non-Hispanic Black, non-Hispanic White), or sex (Male, Female). Could you please guide me if there is an argument to run stratified analysis in one model (like in MPlus) as I don't want to run separate models among each group (like one model for Male and another for Female)? 

I had another issue with my model, but I assume that this is the model I want to stratify:
`set.seed(2023)`
`lcga4_gen_classmb_tp <- hlme(General_SES ~ Timepoint_numeric + age_year + sex_br,
                          classmb = ~ age_year + sex_br,
                          subject = "ID_num", 
                          ng = 4, 
                          random = ~1,
                          data = data_train,
                          mixture = ~1,
                          B = lcga1_gen_classmb_tp)`

Thank you in advance for any of your help!

Best regards,
Kate

**Comment by VivianePhilipps** [comment]
Hi,

the package doesn't include any option for stratification, but by putting manually all the needed interactions in the fixed effects you can get longitudinal trajectories specific to each of the 6 profiles.

Viviane

**Comment by KateLTran** [comment]
Hi Viviane,

Could you please give me an example of how to plot the interaction/the 6 profiles?

Thank you!

Best,
Kate Tran

**Comment by VivianePhilipps** [comment]
Hi,

to plot the 6 trajectories, you call 6 times the predictY function.

I don't know the range of your covariates, but suppose you want to plot first the trajectory for profile "race=1 and sex=0" 

dnew1 <- data.frame(Timepoint_numeric=seq(0, 10, length.out=100), # if the observation time is from 0 to 10
                                    age_year=50, # for a subject aged 50
                                    race=1, sex=0) # the first profile
pred1 <- predictY(model, newdata=dnew1) # predictions for this first profile


Then, a second profile "race=2, sex=0"

dnew2 <- data.frame(Timepoint_numeric=seq(0, 10, length.out=100), 
                                    age_year=50, 
                                    race=2, sex=0) # the second profile
pred2 <- predictY(model, newdata=dnew2) # predictions for the second profile

And so on.

Then you can plot them, all together or not.

plot(pred1, var.time="Timepoint_numeric") # first profile in black
plot(pred2, var.time="Timepoint_numeric", col=2, add=TRUE) # second profile in red on the same graphe


Best,

Viviane

**Comment by KateLTran** [comment]
Hi Viviane,

Thanks so much for your quick response!

Best,
Kate Tran
