### ISSUE TITLE
Error with running gridsearch - Error in do.call

### ISSUE THREAD

**Issue by vfjn2** [CecileProust-Lima/lcmm#194]
Hi Cécile and Viviane,

Using this code from a paper (modified for my variables): 
```r
lcga1 <- lcmm::hlme(NFL_log ~ Days, random = ~1, ng = 1, subject ='subjectId_new',  data = biom)
lcga2 <- lcmm::gridsearch(rep = 100, maxiter = 10, minit = lcga1, m=lcmm::hlme(NFL_log ~ Days, subject ='subjectId_new', ng = 2, data = biom, mixture =~ Days))
```
I get the error:
Error in do.call(as.character(mc[[1]]), as.list(mc[-1]), envir = parent.frame()) :
'what' must be a function or character string

I can not find what mc is/should be. Is there a new version of lcmm that is causing the issue? If so how do I modify the code so it works. 

Thank you for you help!

**Comment by VivianePhilipps** [comment]
Hi,

I will look at that, but removing lcmm::  for the m argument in the gridsearch call seems to solve the problem :

`lcga2 <- lcmm::gridsearch(rep = 100, maxiter = 10, minit = lcga1, m=hlme(NFL_log ~ Days, subject ='subjectId_new', ng = 2, data = biom, mixture =~ Days))`

Viviane

**Comment by vfjn2** [comment]
Thank you Viviane - very much appreciated
