### ISSUE TITLE
Covariate adjustment in joint latent class models

### ISSUE THREAD

**Issue by thomas-vogt** [CecileProust-Lima/lcmm#196]
Dear all, 

Thank you for the lcmm package. I have a question on covariate adjustment in joint latent class models, for which I am struggling to find an answer. 

By “adjustment”, I mean something akin to fitting a survival model in the following example: 
1.	Some individuals are enrolled in a study, where some baseline covariates (X, age, sex, HbA1C, smoking status, etc.) are measured.
2.	The outcome of interest (Y) is a time-to-event outcome.
3.	The researchers want to know if variable X could be used as a prognostic factor, and be useful to predict time-to-outcome Y, beyond covariates already used in clinical practice (age, sex, HbA1C, smoking status, etc.).
4.	They fit a survival model with time-to-Y as the outcome, and X as exposure, adjusted for age, sex, HbA1C, smoking status, etc. For example: 
coxph(Surv(time, status) ~ X + age + sex + HbA1C + smoking_status, data = some_dataset)
5.	To assess whether X can be a useful prognostic factor for outcome Y, they use the model coefficient of X, the confidence interval, and perhaps the AU-ROC comparing a model without and a model with X to draw conclusions.

(By “prognostic factor”, I mean “any personal attribute that can be used to make more reliable predictions about future risk of medical conditions”, quote from [this paper](https://www.bmj.com/content/355/bmj.i6536)).

My question is: is there something similar that could be done with Joint latent class models? 
1.	Some individuals are enrolled in a study, where some baseline covariates (age, sex, HbA1C, smoking status, etc.) are measured, but other covariates are measured on several occasions over time (and this is the case for covariate X), and those occasions are different from individual to individual (both in number and in frequency).
2.	The outcome of interest (Y) is still a time-to-event outcome.
3.	We want to know if trajectories of a variable X could be used as a prognostic factor, and be useful in clinical practice to identify individuals at high risk of Y, beyond covariates already used in clinical practice (age, sex, HbA1C, smoking status, etc.).
4.	We would like to fit several Joint Latent Class Models (trying different number of classes) with time-to-Y as the survival outcome, and X as the longitudinal outcome. However, we are not sure how to adjust for age, sex, HbA1C, smoking status, etc.  in a way that would allow us to:
5.	assess whether trajectories of X can be used as prognostic factor to identify individuals at high risk of Y (above and beyond age, sex, HbA1C, smoking status, etc.)

For example, the paper “The GRoLTS-Checklist: Guidelines for Reporting on Latent Trajectory Studies” ([link](https://www.tandfonline.com/doi/full/10.1080/10705511.2016.1247646)) states that:
“Predictors (or covariates) can be added to the model at three different places […] ; (2) on the level of the growth parameters to find latent classes that cannot be explained by individual differences on the covariates (like age, food intake, socioeconomic status)”.

Does it mean that (in Jointlcmm), including covariates in the fixed and survival formulas would achieve covariate adjustment similar in spirit to the 1st scenario above, and allow to extract latent classes that are net of those covariates?

Or is it impossible? And other modelling choices should be explored? (joint modeling with shared random-effect, or landmarking, etc.? )

Sorry for a long message, I hope the question is clear.

Kind regards,
Thomas Vogt.

**Comment by VivianePhilipps** [comment]
Hello Thomas,

if you are only interested in the predictions, it can be done with any model (joint shared random effect, latent classes, random forests, etc). 
In lcmm we provide the dynpred function to make predictions, so it is possible.

Where the covariates are included will highly affect the interpretation of the classes. And it is less easy to interpret the model if covariates are included in 'fixed' and in 'survival'. But if you focus on prediction, it is not an issue.

However, with joint latent class models, there is no parameter reflecting the association between the longitudinal covariate and the survival. If quantifying the association is important for you, the shared random effect models are more appropriate.

Hope this helps

Viviane

**Comment by thomas-vogt** [comment]
Hello Viviane,

Thank you for your answer!

Kind regards,
Thomas Vogt.
