### ISSUE TITLE
Numerical problem by computing fn 

### ISSUE THREAD

**Issue by BvnHU** [CecileProust-Lima/lcmm#199]
Hello, 

Firstly i would like to thank you for the great package you've developed! 

At the moment i'm experiencing an issue. When running the following analysis, i get the error message shown below. I have tried to change the maxiter and rep number, but the error message remains. 

lcgaGB1 <- lcmm(GB~Time,
                  subject='Resp',
                  ng=1,
                  data=data)
 
 lcgaGB2 <- gridsearch(lcmm(GB~Time, subject='Resp',
                            ng=2, data=data, mixture=~Time),
                       rep=100, maxiter=10, minit=lcgaGB1)
 Numerical problem by computing fn 
          value of function is : NaN** 

When i don't use gridsearch, i don't get the error message, like in the example below:

lcgaGB_1 <- lcmm(GB~Time,
                subject='Resp',
                ng=1,
                data=data)

lcgaGB_2 <- lcmm(GB~Time,
                 subject='Resp',
                 ng=2,
                 data=data,
                 mixture=~Time,
                 B=random(lcgaGB_1))

Do you have any suggestions on how to deal with the error message when using gridsearch?

**Comment by VivianePhilipps** [comment]
Hello,

sorry, I don't know why you get only the error with gridsearch, it just makes multiple models with B=random(minit).
Do you have any results in lcgaGB2? If the error happens only for a few models over your 100 replicates, you can ignore the message, this will not affect the final model.

Viviane
