### ISSUE TITLE
Adding legend = NULL to the plot of the baseline hazard disrupts sequencing of the dots

### ISSUE THREAD

**Issue by sambrilleman** [CecileProust-Lima/lcmm#2]
This bug is pretty obscure, and it took me a while to work out exactly what was producing the error. But basically, when I specify `legend = NULL` in the plotting argument, then any `...` arguments specified after that are incorrectly sequenced (i.e. their position in the matched call is incorrect). 

This means that the use of the `match.call` function [here](https://github.com/CecileProust-Lima/lcmm/blob/master/R/plotbaselinerisk.R#L27) - and in the subsequent lines of code below that - returns either an error or the incorrect output.

I think the better approach might be to use `dots` instead of `match.call()`. I will submit a pull request to that effect.

----------- start reprex ------------
```
library(lcmm)

m3 <- Jointlcmm(fixed= Ydep1~Time*X1,mixture=~Time,random=~Time,
                classmb=~X3,subject='ID',survival = Surv(Tevent,Event)~ X1+mixture(X2),
                hazard='3-quant-splines',hazardtype='PH',ng=3,data=data_lcmm,
                B=c(0.7576, 0.4095, -0.8232, -0.2737, 0, 0, 0, 0.2838, -0.6338, 
                    2.6324, 5.3963, -0.0273, 1.3979, 0.8168, -15.041, 10.164, 10.2394, 
                    11.5109, -2.6219, -0.4553, -0.6055, 1.473, -0.0383, 0.8512, 0.0389, 
                    0.2624, 1.4982))

# returns an error
plot(m3, which = "hazard", legend = NULL, col = rep(1,3))

# works ok
plot(m3, which = "hazard", col = rep(1,3), legend = NULL)
```
----------- end reprex ------------

**Comment by CecileProust-Lima** [comment]
Thanks a lot Sam. We will look at it seriously. 
Cécile
