### ISSUE TITLE
Lo-Mendell-Rubin tests and bootstrap likelihood ratio tests

### ISSUE THREAD

**Issue by AnneKrogh** [CecileProust-Lima/lcmm#20]
Dear Dr Proust-Lima,

Thank you for making the r package lcmm – It is great work!  I’m using the lcmm package to study latent classes of treatment response in a longitudinal study. 
I would like to use Lo-Mendell-Rubin tests and bootstrap likelihood ratio tests to determine the optimale number of classes, but the tests are not implemented in the current package. Is there a way that I can make the tests using other libraries, or do I have to code them myself?

Best regards, 
Anne

**Comment by CecileProust-Lima** [comment]
Dear Anne, 
thank you for your feedback. I don't use those tests in my practice so I did not implement them in the package. And I don't know whether you could use another package to compute them (I doubt that actually). 
Sorry for this lack of help. Hopefully, maybe someone in the community will have an answer ... 
Best
Cécile
