### ISSUE TITLE
lcmm - Iteration process - number of iterations equals 1

### ISSUE THREAD

**Issue by Tina-Kb** [CecileProust-Lima/lcmm#200]
Hi,

I've been fitting models with an increasing number of groups using the lcmm function. I'm using the gridsearch function to specify the start values (100 random sets of start values, maximum number of iterations = 15). 
Even though I haven't encountered any convergence error, the number of iterations is 1 according to the iteration process described in the summary of some of the models fitted.

Here are the results from the iteration process described in the summaries : 
1  class -> 30 iterations                                                   
2 classes -> 1 iteration                                                              
3 classes -> 1 iteration                                                                 
4 classes -> 2 iterations                                                                  
5 classes -> 6 iterations                                                              
6 classes -> 2 iterations                                                                  
7 classes -> 18 iterations 

Is this normal? If not, what could be the cause and how can I fix it?

Here's an example :

mvpa_f3 = gridsearch(rep = 100, maxiter = 15, minit = mvpa_f1,
                     m=lcmm(MVPA_TOTAL ~ poly(temps, degree = 3, raw =  TRUE), 
                            subject = "ID", ng = 3, data = subset(traj_long, sex == 2), 
                            mixture = ~ poly(temps, degree = 3, raw =  TRUE),
                            link = "splines"))

summary(mvpa_f3)

General latent class mixed model 
     fitted by maximum likelihood method 
 
lcmm(fixed = MVPA_TOTAL ~ poly(temps, degree = 3, raw = TRUE), 
    mixture = ~poly(temps, degree = 3, raw = TRUE), subject = "ID", 
    ng = 3, link = "splines", data = subset(traj_long, sex == 
        2))
 
Statistical Model: 
     Dataset: subset(traj_long, sex == 2) 
     Number of subjects: 417 
     Number of observations: 1925 
     Number of observations deleted: 160 
     Number of latent classes: 3 
     Number of parameters: 20  
     Link function: Quadratic I-splines with nodes  
0 630 1260 1890 2520  
 
Iteration process: 
     Convergence criteria satisfied 
     Number of iterations:  1 
     Convergence criteria: parameters= 4.9e-10 
                         : likelihood= 2.3e-08 
                         : second derivatives= 6.8e-11 
 
Goodness-of-fit statistics: 
     maximum log-likelihood: -12573.54  
     AIC: 25187.07  
     BIC: 25267.73  
 
 
Maximum Likelihood Estimates: 
 
Fixed effects in the class-membership model:
(the class of reference is the last class) 

                     coef      Se    Wald p-value
intercept class1 -0.62025 0.22123  -2.804 0.00505
intercept class2  0.22320 0.18744   1.191 0.23373

Fixed effects in the longitudinal model:

                                     coef      Se    Wald p-value
intercept class1 (not estimated)        0                        
intercept class2                 -0.87336 0.18545  -4.709 0.00000
intercept class3                 -0.88685 0.18597  -4.769 0.00000
poly(...)1 class1                 0.38050 0.15048   2.529 0.01145
poly(...)1 class2                -0.35057 0.09571  -3.663 0.00025
poly(...)1 class3                -0.56156 0.10686  -5.255 0.00000
poly(...)2 class1                -0.04445 0.04768  -0.932 0.35125
poly(...)2 class2                -0.12670 0.03114  -4.068 0.00005
poly(...)2 class3                 0.12100 0.03505   3.452 0.00056
poly(...)3 class1                -0.04540 0.04176  -1.087 0.27698
poly(...)3 class2                 0.10347 0.02667   3.880 0.00010
poly(...)3 class3                 0.01050 0.02985   0.352 0.72496

Residual standard error (not estimated) = 1

Parameters of the link function:

               coef      Se    Wald p-value
I-splines1 -2.14396 0.15362 -13.956 0.00000
I-splines2  1.68205 0.01965  85.621 0.00000
I-splines3 -0.28973 0.15774  -1.837 0.06624
I-splines4  1.15731 0.05537  20.902 0.00000
I-splines5  0.00026 0.02622   0.010 0.99214
I-splines6  1.20111 0.12707   9.453 0.00000
I-splines7  0.55176 0.26419   2.089 0.03675

Thanks!

Tina

**Comment by VivianePhilipps** [comment]
The number of iterations you see is the number of iteration needed to converge after the initial 15 iterations (maxiter=15). If you have only 1 iteration, it means that the model had already converged within 15 iterations, which is good news.
