### ISSUE TITLE
Perform splines on link function and splines function of time

### ISSUE THREAD

**Issue by tinaty** [CecileProust-Lima/lcmm#205]
Hi, I tried to use different link functions and different functions of time when fitting latent class mixed models on continous outcomes. I wonder what is the difference between` link='splines' `and  splines function of time by using `splines::ns(time)`? Can I use splines link function and in the meantime use `splines::ns(time)`, i.e.`m3 <- lcmm(fixed = y ~ splines::ns(time), random=1+time, mixture= splines::ns(time), link='splines', ng=3, subject='id', data=mydata)`? 
Thank you for your advice.

**Comment by tinaty** [comment]
@VivianePhilipps Hi Viviane, 

Thank you for your advice. 

As I have a non-Gaussian outcome, I first tried a splines link and splines function of time simultaneously, i.e. `m3Splines <- lcmm(fixed = y ~ splines::ns(time), random=1+time, mixture= splines::ns(time), link='splines', ng=3, subject='id', data=mydata)`. 

I also tried a model with a linear link and splines function of time, i.e. `m3Linear <- lcmm(fixed = y ~ splines::ns(time), random=1+time, mixture= splines::ns(time), ng=3, subject='id', data=mydata)`. 

However, `m3Splines` shows much worse entropy (0.77) than the entropy of `m3Linear` (0.90). I have enclosed the subject specific residuals of `m3Splines` and `m3Linear`below. Could you kindly advise if I should choose the model `m3Linear` given that the primary goal of Latent Class Mixed Modeling is to capture heterogeneity in longitudinal trajectories, so the focus should be on the interpretation of the latent classes themselves despite the non-normality? 

<img width="226" alt="image" src="https://github.com/CecileProust-Lima/lcmm/assets/26419409/ce351b30-b79b-421b-88c9-e8dfb94ecc75">

<img width="226" alt="image" src="https://github.com/CecileProust-Lima/lcmm/assets/26419409/1d071cb8-6806-4eec-9c6a-ab48cb9dd07c">

**Comment by VivianePhilipps** [comment]
Hi,

we usually choose the link function in one class models. We estimate the several models differing only by the link function and choose the "best one", for example the one with better AIC.
Then, we add latent classes and keep always the same link.

Best,

Viviane

**Comment by tinaty** [comment]
Thanks a lot Viviane for your kind advice
