### ISSUE TITLE
How to get smooth curves for the group-specific mean predicted trajectories

### ISSUE THREAD

**Issue by Tina-Kb** [CecileProust-Lima/lcmm#206]
Hi,

I was wondering why I don't get smooth curves when I plot the group-specific mean predicted trajectories with predictY. Even when I use splines (example 2) for the shape of the trajectories, I don't get smooth curves.

Example 1 : 

mvpa_f4 = gridsearch(rep = 100, maxiter = 15, minit = mvpa_f1,
                     m=lcmm(MVPA_TOTAL ~ poly(temps, degree = 3, raw =  TRUE), 
                            subject = "ID", ng = 4, data = subset(traj_long, sex == 2), 
                            mixture = ~ poly(temps, degree = 3, raw =  TRUE),
                            link = "3-manual-splines", intnodes = c(10)))

predY = predictY(mvpa_f4, newdata=subset(traj_long, sex == 2), var.time="age")
par(mar=c(10, 4, 3, 2))
plot(predY, shades=TRUE, ylab= "MVPA (minutes per week)", xaxt = "n",
     xlab= "" , xpd=TRUE, ylim=c(0,1200),
     legend.loc = "top", inset=c(1,1.2),
     main = "Group-specific mean predicted trajectory \n MVPA - Women", 
     lwd = 1.8, legend = c("Group 1 (10.1%)", "Group 2 (18.2%)", "Group 3 (59.5%)",
                           "Group 4 (12.2%)"), ncol=2,
     col = c("purple","darkblue", "deeppink","yellowgreen"),
     lty=1)
title(xlab="Median age (years)", line=2.2, cex.lab=1)
axis(side = 1, at=c(20.3, 24.1, 30.3, 33.6, 35.3))

![image](https://github.com/CecileProust-Lima/lcmm/assets/140769525/2910c106-8818-4521-9970-7188f44168e2)

Example 2 :
mvpa_f4_ns = gridsearch(rep = 100, maxiter = 15, minit = mvpa_f1_ns,
                       m=lcmm(MVPA_TOTAL ~ ns(temps, knots = c(-0.93, 0.93, 1.73)), 
                              subject = "ID", ng = 4, data = subset(traj_long, sex == 2), 
                              mixture = ~ ns(temps, knots = c(-0.93, 0.93, 1.73)),
                              link = "3-manual-splines", intnodes = c(10)))

predY = predictY(mvpa_f4_ns, newdata = subset(traj_long, sex == 2), var.time="age")
par(mar = c(10, 4, 3, 2))
plot(predY, shades = TRUE, ylab = "MVPA (minutes per week)", xaxt = "n",
     xlab= "" , xpd=TRUE, ylim=c(0,1200),
     legend.loc = "top", inset=c(1,1.2),
     main = "Group-specific mean predicted trajectory \n MVPA - Women", 
     lwd = 1.8, legend = c("Group 1 (10.1%)", "Group 2 (12.2%)", "Group 3 (59.7%)",
                           "Group 4 (18.0%)"), ncol=2,
     col = c("purple","darkblue", "deeppink","yellowgreen"),
     lty=1)
title(xlab="Median age (years)", line=2.2, cex.lab=1)
axis(side = 1, at=c(20.3, 24.1, 30.3, 33.6, 35.3))

![image](https://github.com/CecileProust-Lima/lcmm/assets/140769525/3ea0aaba-64c8-4bc3-8860-b922e70d34f9)

Thanks for the help!

Tina

**Comment by CecileProust-Lima** [comment]
Hi, 
predictY computes and plots the expected level of your outcome (MVPA_TOTAL) at all the time points specified in your newdata. This newdata should have the same form as the data you used for the estimation (it seems to be the case for you). But in your case, the vartime specified in predictY (age) is different from the timevar specified in your lcmm model. I think your issue comes from there.  
In the vignettes, you will see, we rarely use a subset of the data but rather construct a newdataset (fake on) with a sequence of time inside. That way, you can choose the level of smoothness. 
I hope this helps.
Cécile

**Comment by Tina-Kb** [comment]
Thank you Cécile, I was able to plot smooth curves with your technique.
