### ISSUE TITLE
lcmm function: scaling and entropy

### ISSUE THREAD

**Issue by sedasacu** [CecileProust-Lima/lcmm#207]
Dear Cecile and Viviane,

First of all, many thanks for the open source package! I have recently started using the lcmm for trajectory modelling. I am using psychopathology symptoms (e.g., internalizing symptoms, externalizing symptoms, total problems) as dependent variable to model trajectories from age 8 to age 33 (irregularly intervaled: 8, 11, 15, 19, 22, 23, 25,33). I am modelling linear, quadratic, and cubic forms with random intercept and random slope.

My dependent variables are continious and  not normally distributed but it doesn't seem too bad as well. I have started with hlme function. Then used the lcmm function. I assummed that they might give the same results if I keep the link function default. However, I realized that hlme function always gives the same score range (compatible with raw scores) in my dependent variable but I see always different ranges in y axis with lcmm function (e.g., 0-5, -1-6 etc.). They are the same models  with different number of class.

You can see this in the following figures:

model estimated with hlme():
![Bild1](https://github.com/CecileProust-Lima/lcmm/assets/109088742/61c849d5-9e7c-4aa9-a528-015f3b419887)

model estimated with lcmm()
![Bild2](https://github.com/CecileProust-Lima/lcmm/assets/109088742/9ad2b703-a25f-4d23-97a5-63ce75bd905b)

My first question is, does lcmm function scale the dependent variable? Because we prefer to use raw scales. If yes, is there any setting for turning this off.

My second question is about entropy. Generally, a model is considered good enough if entropy > 0.8. So far, I am getting always entropy values lower than 0.8 when I use a single dependent variable. However, when I use two dependent variables in the one model (e.g., externalizing and internalizing symptoms) using multpjlcmm function, entropy values were higher than 0.8. Do you have any explation for this? Is it about my data/model or do you also generally find low entropy values?

Many thanks in advance!

Best wishes,
Seda

**Comment by sedasacu** [comment]
Sorry, I am still running some analyses and new questions just came up. When I say my dependent variable is roughly normal, I mean that it is roughly normally distributed at each time point. When I check the normality using a column vector of my dependent variable (internalizing symptoms) containing all time points for all participants together (2536 observations through 317 participants and 8 time points), this is not the case. Then I normalized my dependent variable using square root transformation. The distribution seemed fine but I am not sure if it is still enough to use hlme().

I also came across one post shared here. You suggest using lcmm function to compare a model with linear link function with a model with splines link function before using hlme(). I have tried this using both non-transformed and sqrt transformed dependent variables. In both cases, models with splines link function had lower AIC and BIC. However, when I use lcmm function with splines link function, AIC and BIC are always lowest for the one class solution. It doesn't matter which variable I use or which form (linear, quadratic etc.). This is against my hypothesis and does not seem to me possible that all participants followed the same trajectory across 8 assessment waves (around 25 years). Here is my example code (int=internalizing symptoms):

m1_int <- lcmm(int ~ age_scaled, random= ~ age_scaled, subject="ID", data=MARS_data, link="5-quant-splines")
m2_int <- gridsearch(rep = 100, maxiter = 30, minit = m1_int, 
                     lcmm(int ~ age_scaled, subject = "ID", random= ~ age_scaled,
                     ng = 2, data = MARS_data, link="5-quant-splines", mixture = ~ age_scaled , nwg=T)) 
m3_int <- gridsearch(rep = 100, maxiter = 30, minit = m1_int, 
                     lcmm(int ~ age_scaled, subject = "ID", random= ~ age_scaled,
                      ng = 3, data = MARS_data, link="5-quant-splines", mixture = ~ age_scaled , nwg=T)) 

Thank you in advance!

Best,
Seda

**Comment by VivianePhilipps** [comment]
Hi,

the lcmm model with linear link is exactly the same as hlme, expect that there is a rescaling in lcmm. This parametrization is used in order to compare estimations of a lcmm model with linear link and a lcmm model with splines link for example. If you don't want this rescaling, you should use hlme.
Note that if you use splines link, the outcome variable should not be transformed before (with sqrt), otherwise you will have a double transformation, which is even less interpretable.

Did you look at other criteria as BIC to chose the number of classes? BIC is a usual choice, but many other criteria are possible. 

Best,

Viviane

**Comment by ShabnazS** [comment]
Implementation: LCGA
```{r}
# open package
library(lcmm)
# set the seed for random number generator, so results can be
# reproduced:
set.seed(2002)

# run models with 1-4 classes, each with 200 random starts,
# using the 1-class model to set initial start values:
lcga1 <- hlme(logMBZP1 ~ trimester1, subject = "CHEAR_id", ng = 1, data = phthalate_MBZP)
lcga2 <- gridsearch(rep = 200, maxiter = 10, minit = lcga1,
m=hlme(logMBZP1 ~ trimester1, subject = "CHEAR_id",
 ng = 2, data = phthalate_MBZP, mixture = ~ trimester1))
lcga3 <- gridsearch(rep = 200, maxiter = 10, minit = lcga1,
 m=hlme(logMBZP1 ~ trimester1, subject = "CHEAR_id",
 ng = 3, data = phthalate_MBZP, mixture = ~ trimester1))
# make table with results for the 3 models:
summarytable(lcga1, lcga2, lcga3)


Error in gridsearch(rep = 200, maxiter = 10, minit = lcga1, m = hlme(logMBZP1 ~  : 
  The model minit did not converge


How do I solve this error?

**Comment by VivianePhilipps** [comment]
The one class model needs to converge properly to use gridsearch.
See here to solve convergence issues : https://cecileproust-lima.github.io/lcmm/articles/usual_problems.html
