### ISSUE TITLE
hlme vs. lcmm function for non-Guassian outcomes

### ISSUE THREAD

**Issue by hildebtb** [CecileProust-Lima/lcmm#208]
Is it possible to utilize a non-Guassian link for Y outcomes using the hlme() function.  I see in the vingette the link='splines' for lcmm().  However, if there were known floor effect in your MMSE example that emerged over time, I am not sure how to capture this distribution (or even if possible) in gridsearch(hlme()) approach.

**Comment by CecileProust-Lima** [comment]
lcmm is a version of hlme that is appropriate for Gaussian outcomes (as hlme) and non-Gaussian outcomes. It thus has a larger scope than hlme. If you have an issue of departure from normality, you choose use lcmm. Note that the specification is exactly the same, except you have to add this link argument. 
lcmm has been initially motivated to account for floor and ceiling effects of outcomes so this should be great for you. 

The girdsearch is something unrelated to the distribution of the outcome. This is a grid of runs to apply in the case where you assume different latent classes in your data. You should find details in the vignette. 

Cécile

**Comment by hildebtb** [comment]
Cécile,

Thank you for the clarification.  I am wondering if it is possible to
specific different trajectories (linear vs. quadratic) within the same
model.  For example, a two class solution where one class represents a
linear stable change over time and a second class indicates a quadratic
change.  I can estimate the model where all classes are either linear or
quadratic, but not the combination.

Thank you,
Tom

**Comment by CecileProust-Lima** [comment]
If you want to specify a linear and a quadratic trajectory depending on the class, you will have to do this by fixing parameters (the t^2 parameters for the classes desired as linear) at 0 in posfix argument. 
Cécile

**Comment by p1981thompson** [comment]
How is a parameter estimate from the longitudinal model interpreted from lcmm(... ,link="**thresholds**") if I have a 3 category outcome variable? Say for example I have an estimated parameter est =-0.30, se=0.12, wald=-2.60, p=.01. Is this converted to an odds ratio or interpreted directly?
