### ISSUE TITLE
Error in get(name, envir = envir) : first argument has length > 1

### ISSUE THREAD

**Issue by dayull** [CecileProust-Lima/lcmm#209]
I'm trying to run ```gridsearch()```  on R version 4.3.1 and lcmm version 2.0.2. I'm using an 2023 M2 chip from MacOS Ventura 13.5. 

when specifying the ```cl``` parameter, using either an integer or a cluster defined using the ```makeCluster``` function from parallel, I get the following error:

```Error in get(name, envir = envir) : first argument has length > 1.```

**Comment by VivianePhilipps** [comment]
Sorry, I can't replicate the error.
Could you give me your call to the gridsearch function?
