### ISSUE TITLE
Switching problem for latent classes

### ISSUE THREAD

**Issue by ivonnerenteria** [CecileProust-Lima/lcmm#21]
Dear Dr. Proust: I hope you are well. I write you in this opportunity because I have some questions about switching problem for latent classes. I have simulated a database (covariates, fixed effects, random effects, latent process, measurement error, intercept associated with class-specific probability, two latent classes, ordinal markers and thresholds), then I estimated the parameters using lcmm function with the goal to recover the parameters used to create the database. In approximately 30 percent of simulations, I detected different order in classes and the intercept of class-specific probability results with similar magnitude but changed sign.
Dr. Proust, does the internal code of lcmm manage this problem? If there was a switching problem, does it affect only multinomial logistic model? Or does it affect too measurement model? Particularly, parameters associated with class-specific fixed effects. (for example for 2 classes, the parameters of class 1 correspond to class 2 and the parameters of class 2 correspond to class 1)

thank you so much for your help,

Ivonne Rentería

**Comment by CecileProust-Lima** [comment]
Dear Ivonne, 
you are right, if you estimate the same latent class model twice, the latent classes can be switched. But this is not a "problem" and does not have to be handled in applications, so internally in lcmm. The switching problem has to be taken care of only in simulations when looking at summary statistics and this can be easily done by exchanging the class-specific parameters when the switch appears (after convergence). One way is to systematically consider the lowest intercept or slope, or the smallest probability in class 1.
I hope this helps you. 
Cécile
