### ISSUE TITLE
Simplifying spline equation

### ISSUE THREAD

**Issue by Tina-Kb** [CecileProust-Lima/lcmm#211]
Hi,

To simplify/refine a spline equation, is it ok to eliminate basis functions that aren't significant (by forcing the corresponding coefficients to be equal to zero)? I'm used to simplifying polynomial equations by removing higher order terms that aren't significant and I would like to know if there's an equivalent simplification that can be done for splines.

For example:

mvpa_f4_ns = gridsearch(rep = 100, maxiter = 15, minit = mvpa_f1_ns,
                       m=lcmm(MVPA_TOTAL ~ ns(temps, knots = c(-0.93, 0.93, 1.73)), 
                              subject = "ID", ng = 4, data = traj_long_f, 
                              mixture = ~ ns(temps, knots = c(-0.93, 0.93, 1.73)),
                              link = "3-manual-splines", intnodes = c(10)))

summary(mvpa_f4_ns)

![Screen Shot 2023-09-02 at 8 09 22 AM](https://github.com/CecileProust-Lima/lcmm/assets/140769525/4e25f5ca-974f-4bba-a995-c441f950006a)

BIC = 22608.56

binit = mvpa_f4_ns$best
binit[c(10, 13, 14, 17, 18)] = 0

mvpa_f4_ns_final = lcmm(MVPA_TOTAL ~ ns(temps, knots = c(-0.93, 0.93, 1.73)), 
                     subject = "ID", ng = 4, data = traj_long_f, 
                     mixture = ~ ns(temps, knots = c(-0.93, 0.93, 1.73)),
                     link = "3-manual-splines", intnodes = c(10),
                     B = binit, posfix = c(10, 13, 14, 17, 18))
summary(mvpa_f4_ns_final)
)
![Screen Shot 2023-09-02 at 8 07 53 AM](https://github.com/CecileProust-Lima/lcmm/assets/140769525/ceab7854-4dc7-4aba-ac8f-ee70884f2025)

BIC = 22589.48

Thanks for the help!

Tina

**Comment by CecileProust-Lima** [comment]
Hi 
it is not usual to fix the parameters of spline functions but it might be done indeed. You may need to mention it when describing the model specification in your paper though to be transparent.
Cécile

**Comment by Tina-Kb** [comment]
Thank you Cécile!
