### ISSUE TITLE
Difference hlme and lcmm

### ISSUE THREAD

**Issue by ElliotPS1992** [CecileProust-Lima/lcmm#212]
Dear authors, 

Thank you for creating the lcmm package! I am starting to you use it and I was wondering today if it is correct that running the lcmm function without a link function is exactly the same as using the hlme function? 

edit: The reason I am asking this is that when I am estimating my model using lcmm I get an error, which I do not get while running it with hlme:
m0 <- hlme(y ~1 +x , random = ~1 + x, subject = 'id', maxiter = 1000, data = df) 
converged
m1 <- lcmm(y ~1 +x , random = ~1 + x, subject = 'id', maxiter = 1000, data = df) 
Numerical problem by computing fn 
    value of function is : NaN 

I have read that this numerical problem is caused by initial values in the wrong area. Therefore I decided to use the initial values of the hlme model:

m1 <- lcmm(y ~1 +x , random = ~1 + x, subject = 'id', maxiter = 1000, data = df, B= model0['best']$best )
This gives: Error in chol.default(varcov) : 
  the leading minor of order 1 is not positive
 
Hence, I was wondering if hlme estimates the same as the lcmm function does with no link function specified and if I can therefore use the hlme function

                      

Thank you in advance!

**Comment by VivianePhilipps** [comment]
Hi,

the models are the same, but the parametrization is different, so you can't use directly hlme estimates as initial values of a lcmm model.
This particularity is addressed in the vignette : https://cecileproust-lima.github.io/lcmm/articles/latent_process_model_with_lcmm.html

Viviane

**Comment by ElliotPS1992** [comment]
Thank you!
