### ISSUE TITLE
less stringent convergence thresholds

### ISSUE THREAD

**Issue by Tina-Kb** [CecileProust-Lima/lcmm#213]
Hi,

I read in a previous post that to overcome model convergence problems, we can use a less stringent value (e.g. 0.01 instead of 0.0001) for the three convergence thresholds. Since I still have model convergence issues after using a 0.01 threshold (and after trying other tricks described in the following post : https://github.com/CecileProust-Lima/lcmm/issues/8) I would like to know what would be the least stringent threshold that can be used and that wouldn't lower too drastically the quality of convergence?

Thank you!

Tina

**Comment by VivianePhilipps** [comment]
Hi,

for the 3 convergence criteria, the lower the better. We provide by default a value of 0.0001. The last criterion can be relaxed to 0.001, or even 0.01 in complex settings. I would not recommend higher values, but we've never checked formally what is the maximum acceptable value to obtain correct inference in latent class models.

Viviane

**Comment by Tina-Kb** [comment]
Thank you Viviane
