### ISSUE TITLE
Distribution of variable 

### ISSUE THREAD

**Issue by BvnHU** [CecileProust-Lima/lcmm#215]
Hello,

I want to use latent class growth analysis, but my dependent variable is distributed like this:
![image](https://github.com/CecileProust-Lima/lcmm/assets/139464686/89441ce0-2bdb-4b99-9dc5-3ff5c356e8a5). 

Another variable we want to use is distributed as followed:

![image](https://github.com/CecileProust-Lima/lcmm/assets/139464686/782c75eb-7119-4cc6-a999-ee6499f59ec2)

Based on the information from the vignettes and articles, i'm not quite sure if lcmm can handle this kind of data. Can you tell me whether this is possible and if not, what would be a solution?

Thanks in advance, 

Bas

**Comment by VivianePhilipps** [comment]
Hello Bas,

I'm not sure, by looking at your first histogram, if your outcome is ordinal. If you have only 8 modalities, it's a bit small to consider it as a continuous variable. So, the lcmm function with link="thresholds" should be preferred.
For the second, it is asymmetric, but it is close to the MMSE's distribution in the paquid sample (look at hist(paquid$MMSE)), so you can try with splines link. You won't be able to capture all variations as in your pink density, but according to the context it may be sufficient.

Best,

Viviane

**Comment by BvnHU** [comment]
Thanks @VivianePhilipps! I managed to perform the analysis. What i don't understand from the output, is that there is no intercept for class 1 under the Fixed effects in the longitudinal model overview. When i use predictY and plot the model, class 1 is represented, but based on which intercept? So my question is: How can i determine the intercept for class 1? 

Maximum Likelihood Estimates: 
 
Fixed effects in the class-membership model:
(the class of reference is the last class) 

                     coef      Se    Wald p-value
intercept class1  0.11220 0.22408   0.501 0.61658
intercept class2  2.08575 0.16005  13.032 0.00000
intercept class3 -1.07169 0.27167  -3.945 0.00008

Fixed effects in the longitudinal model:

                                     coef      Se    Wald p-value
intercept class1 (not estimated)        0                        
intercept class2                 -5.47246 0.36667 -14.925 0.00000
intercept class3                 -0.20171 0.60383  -0.334 0.73834
intercept class4                 -6.06015 0.45287 -13.382 0.00000
Time class1                      -1.43401 0.13921 -10.301 0.00000
Time class2                       0.01049 0.03193   0.329 0.74250
Time class3                       0.14260 0.20109   0.709 0.47824
Time class4                       1.42951 0.12765  11.199 0.00000


Variance-covariance matrix of the random-effects:
          intercept    Time
intercept   0.12302        
Time        0.01760 0.00252

Residual standard error (not estimated) = 1

Parameters of the link function:

                         coef      Se    Wald p-value
Linear 1 (intercept) 54.09246 2.65251  20.393 0.00000
Linear 2 (std err)    7.90029 0.18885  41.834 0.00000

**Comment by CecileProust-Lima** [comment]
Hi, 
because you use lcmm function (rather than hlme) function, a transformation is included (last part linear1 linear2). To make the model identifiable given this transformation, we add 2 constraints on the underlying level (after transformation): 
- the intercept of the first class is 0
- - the variance of the error is 1.
this transformation is useful when you do not have a Gaussian outcome. here you assume a linear transformation which corresponds exactly to the Gaussian case (linear 1 replaces intercept not estimated, linear 2 replaces the standard error not estimated). So if this is what you want to do, then use hlme, it will be easier. 
Cécile
