### ISSUE TITLE
BIC calculation

### ISSUE THREAD

**Issue by sr456** [CecileProust-Lima/lcmm#22]
Dear Dr Proust-Lima,

I used the lcmm package recently and found it is very useful. But I noticed that when calculating the BIC using the lcmm package, the number of subject was used as n rather than the number of observations. Is there a reason for this? 

Best regards,
Kate

**Comment by CecileProust-Lima** [comment]
Dear Kate, 
I have always used the number of independent units in the computation of BIC. As far as I know, this is quite classical in mixed models although some discussion exists on whether the total number of observations or the total number of independent units should be considered. 
In all our tests by simulations, the behaviour of this BIC based on independent units was satisfying (to select the optimal number of latent classes). 
I hope this will help,
Best,
Cécile
