### ISSUE TITLE
B initial values in HLME

### ISSUE THREAD

**Issue by pitina244** [CecileProust-Lima/lcmm#221]
Hi

Trying to figure it out 

HLMEmodel <- hlme(loglevels~ age + sex + educ + year + TotalYears + baselinelevels, random=~ year, subject='IID', data=mydata)
run without any problem!

HLMEmodel2 <- hlme(loglevels~ age + sex + educ + year + TotalYears + baselinelevels, random=~ year, fixed=~ age + sex + educ + year + TotalYears + log10Ab40BA + year*TotalYears, subject='IID', ng=2, data=mydata, B=random(HLMEmodel))

Error in hlme(loglevels~ age + sex + educ + year + TotalYears + log10Ab40BA,  : 
  B is not correct

any idea?

**Comment by CecileProust-Lima** [comment]
Hi, 
you seem to have duplicated the fixed= part (the first part loglevels ~ .... is a fixed= part). If the second is kept, then the structure is different and B is incorrect. 
Cécile
