### ISSUE TITLE
Cause-specific individual predictive cumulative incidences for mpjlcmm

### ISSUE THREAD

**Issue by Yeqian227** [CecileProust-Lima/lcmm#222]
Dear Cécile, dear Viviane,

I am using your `lcmm` package, and it is wonderful! Thank you very much for providing this work to the public. While using the `mpjlcmm` function, I have encountered some issues.

I noticed in issue #164  you mentioned the dynpred function is not implemented for a mpjlcmm model. However, in your paper :
> Joint modeling of repeated multivariate cognitive measures and competing risks of dementia and death: a latent process and latent class approach.” Statistics in medicine vol. 35,3 (2016): 382-98. doi:10.1002/sim.6731

I observed that in **section 4.7 'Individual dynamic predictions,'** you calculated and plotted **'cause-specific individual predictive cumulative incidences'** for **'an ApoE− man who graduated from primary school and entered the cohort at 68 years old up to a horizon of 5 years.’**

Would appreciate any suggestions on how to calculate **'cause-specific individual predictive cumulative incidences'** using repeated multivariate measures (such as **IST15** and **WST**) in conjunction with baseline fixed variables (like **sex**, **EL**, and **E4**) for a `mpjlcmm` using `lcmm` package or function in other package in R, because I want to compute them, as mentioned in issue #118 , to calculate **time-ROC** and **Brier scores** and then I could compare `mpjlcmm `with other survival models.

Thank you very much!

Best,
Qian Ye

**Comment by VivianePhilipps** [comment]
Hi,

the analysis of this paper was not done in R. It uses a Fortran program, which is available on request, but is not as user-friendly as the R package.

Viviane

**Comment by Yeqian227** [comment]
Dear  Viviane,

I apologize for my delayed response. Thank you very much for your reply, and I look forward to further updates from your team on this research. Once again, I appreciate your contribution in providing the lcmm program to the public.

Best regards,
Qian
