### ISSUE TITLE
random intercept and random slope - selection of the best model

### ISSUE THREAD

**Issue by MaryWaterloo** [CecileProust-Lima/lcmm#23]
Dear Dr. Proust-Lima,

Thank you for your very helpful lcmm package!

I am running your lcmm model on a sample of 500 older adults with up to 12 longitudinal assessments that created 4-level ordinal outcome.  My first model does not have any covariates. I used one of the codes in your article and I only added age. The model with 8 latent classes has the smallest BIC. Question 1: I am not sure how to use average posterior probabilities to improve my model selection. The latent classes in the model with 8 latent classes do not make lots of clinical sense and the average posterior probabilities are between 0.65 and 0.88. Is there a cut-point for the average posterior probabilities where the probabilities can be considered too small for the model to create robust latent classes? For example, the model with three latent classes has much higher average posterior probabilities (0.93, 0.93, 0.93). However, I believe there is more variability in my data set that can be captured with only 3 latent classes. 

Question 2: I also have a question about implementing both random intercept and random slope into my model. Would you please check my model below and see whether I am considering both random intercept and random slop? If not, how would I modify my model to do so? Also, how do I decide whether both these random effects are needed to model my data set?
m <- lcmm(4 level ordinal outcome ~ age75, mixture = ~age75, random = ~ -1, subject = "ID", data = long, link = "thresholds", ng=8)
where long$age75 <- (long$age-75)/10   (youngest participants of my study are 75 years old)

Question 3: Would you please help me to understand what does random = ~ -1 mean? I ran the model with random = ~ +1 to figure out what is going on. The model took much longer to run and it assigned all participants into 7 latent classes and the 8th class remained empty.

Please let me know if my questions are not clear.

I greatly appreciate your input and looking forward to hearing from you.

Best regards,
Maryam

**Comment by CecileProust-Lima** [comment]
Dear Maryam, 

Regarding question 1: 
There are many indicators that can be used to select the optimal number of latent classes, and in addition to statistical considerations, clinical ones are also important. 
In you example, if discrimination is important, you could look at the entropy which gives a summary of the posterior probabilities (entropy computed in summarytable with which option). You could also discuss that the 3 class model provides a better discrimination based on the posterior probabilities (with or without entropy computation). 
On possibility for selection such a high number of latent classes is that you do not properly account for inter-individual variability (see question 2).

Question 2: 
In next code, 
m <- lcmm(4 level ordinal outcome ~ age75, mixture = ~age75, random = ~ -1, subject = "ID", data = long, link = "thresholds", ng=8)

random = ~ -1 means that you assume there is NO random effect. That might explain why you find so many classes + you assume a linear trajectory according to age, this is not necessarily flexible enough. 

To add random effects: 
random = ~ 1 for random intercept, random = ~ age75 for random intercept and slope (correlated by default). 


Question 3: 
Much longer is normal with random =~ 1: a model for ordinal outcome with random effects involves a numerical integral to solve. 
In addition, I am not surprised the model with 8 classes converged to 7 classes. This happens. See examples in the paper at the jointlcmm section. This is a question of initial values + here, probably a too high number of latent classes. 

Best
Cécile
