### ISSUE TITLE
How to interpret the output of jointlcmm?

### ISSUE THREAD

**Issue by tiandiheyujunjue** [CecileProust-Lima/lcmm#230]
Thank you, teacher, for your dedication and efforts! I believe that, like many beginners, including myself, I still struggle to fully grasp the detailed interpretation of the output from the jointlcmm function. It involves two parts, and it seems that the accompanying explanatory PDF overlooks this aspect.
For example:
summary(mj4b)
#> Joint latent class model for quantitative outcome and competing risks 
#>      fitted by maximum likelihood method 
#>  
#> Jointlcmm(fixed = normMMSE ~ age65 + I(age65^2) + CEP, mixture = ~age65 + 
#>     I(age65^2), random = ~age65 + I(age65^2), subject = "ID", 
#>     ng = 4, survival = Surv(age_init, agedem, dem) ~ CEP + male, 
#>     hazard = "Weibull", data = paquidS)
For example, in the output results of the aforementioned model, how to obtain the coefficients and 95% confidence intervals for the CEP of each of the four categories in the longitudinal model? And in the survival model, how to obtain the coefficients and 95% confidence intervals for the CEP of each of the four categories as well as the male factor？
I hope you can help me solve this problem! Thank you very much!

**Comment by VivianePhilipps** [comment]
Hi,

in the longitudinal submodel, the CEP covariate doesn't appear in the mixture formula, so you assume a common effect of CEP over the latent classes. The estimated effect of CEP, which is about 12.8 in this model, applies to all classes. Subjects with CEP=1 have the same shape of trajectory, except that it is 12.8 points higher.

In the same way, CEP and male has a common effect over the latent classes in the survival model.
To get the confidence intervals, you specify draws=TRUE in the predictY and cuminc functions.

Viviane
