### ISSUE TITLE
Estimating a binomial logistic lcmm?

### ISSUE THREAD

**Issue by JacobElder** [CecileProust-Lima/lcmm#232]
Hi,

I was wondering if there is support or a possibility of implementing a binomial logistic lcmm (logit link) for this package? Is there a way to model binary outcomes?

**Comment by VivianePhilipps** [comment]
Hi,

in the lcmm package, binary outcomes are modeled with a probit model using argument link = "threholds". This options is available in the lcmm and multlcmm functions.

Viviane
