### ISSUE TITLE
Binary multivariate analysis with multlcmm()

### ISSUE THREAD

**Issue by 1151k** [CecileProust-Lima/lcmm#236]
First, thank you very much for this fantastic package! I've had much benefit from it.

I wonder, however, how does one use multlcmm() for multivariate binary outcome data? On [this page](https://cecileproust-lima.github.io/lcmm/articles/lcmm.html) it is stated that multlcmm() supports binary data, but on the documentation page for the function, only ordinal (and continuous) data is mentioned. Is binary data in fact supported? And if so, which link value is suitable for this type of data? Finally, how does one plot such data (I get an error that plot() with which="fit" is not applicable...)

Best regards,
Daniil

**Comment by CecileProust-Lima** [comment]
Dear Daniil, 
thank you for your positive feedback :). 
multlcmm handles binary data, considering these data are 2-level ordinal data. So the link would be "thresholds". 
Best,
Cécile

**Comment by 1151k** [comment]
Dear Cécile,

Thank you very much for the confirmation! 

Now, I attempted again with the "thresholds" link value, and it works indeed. However, when later trying to plot the different indicator variables with the following piece of code:

`plot(m2, outcome="asthma_medication")`

I get the following error message: "Residual and prediction plots are not available yet for threshold mixed models"

Is there any workaround I can use at the moment? I assume it may take a while for the functionality to be added to the package (?)

Best regards,
Daniil

**Comment by CecileProust-Lima** [comment]
Sorry for this. Indeed, we have not worked around these plots. If you want to have the predicted trajectories, I recommend in general to use predictY function. The plot is only meant to check the goodness-of-fit, not presenting results. 
Cécile
