### ISSUE TITLE
Estimating hazard ratios from JLCMM output

### ISSUE THREAD

**Issue by law852** [CecileProust-Lima/lcmm#238]
I'm looking for some guidance on estimating hazard ratios from a JLCMM object with class-specific Weibull hazard curves (e.g. jlcmm(fixed = y ~ x, mixture = ~time, random = ~1,    subject = "pid", ng = 4, survival = Surv(time, event2) ~   b1 + b2, hazard = "Weibull",    hazardtype = "Specific", link = "3-equi-splines", data = data).

Thank you!

**Comment by Oliviapng** [comment]
Hi, thank you for the code!  I would like to know how to calculate the 95% CI of HR. Could you please provide some guidance or an example code on how to obtain se? Thanks!
