### ISSUE TITLE
Follow up on: Group-Based Multi-Trajectory Modeling with lcmm Package #119

### ISSUE THREAD

**Issue by zyddmn** [CecileProust-Lima/lcmm#240]
Hi! I have the same question when using this package for multi-trajectory modeling. When I use mpjlcmm for my outcomes with no survival part in the model, a warning will pop out: "No time-dependant variable should appear in survival nor in classmb". The code I use looks like this: mms1 <- mpjlcmm(longitudinal = list(mcrp1, mfac1), subject = "ID", ng = 1, data = df_long_new)

**Comment by VivianePhilipps** [comment]
Hi,

sorry, I can't answer this issue without more details.
Does a similar example with the paquid data work? If you have a reproducible code, this would help.
Please make sure that :
 - you are using the latest lcmm version (commit [14af85a])
 - your data are stored in a data frame (not a tibble)
 - your subject variable is numeric
(These are the usual reasons why lcmm fails...)

Viviane
