### ISSUE TITLE
Residuals normality assumption of LCMM

### ISSUE THREAD

**Issue by DanielGlorieux** [CecileProust-Lima/lcmm#242]
I am a student in the third year of a bachelor's degree. As part of a study I use the lcmm model, but the qq-plot graph of the residuals of my model are not normal. This is confirmed by Shapiro's test as well. What could be the consequences of the violation of this assumption on my study ? Thank you.

**Comment by VivianePhilipps** [comment]
Hi,

as any parametric model, the results are valid only if all assumptions are met. The violation of an hypothesis can lead to biased results, meaning that the estimations you get are not reliable. On real data, you can't know how far the true value is from your estimation, but you know that your results may be wrong.

Viviane

**Comment by DanielGlorieux** [comment]
Thank you for your  reply dear Viviane. 

Taking the example of simple linear regression where certain assumptions may not be verified but do not prevent the use of the model (with some reservations), for example the hypothesis of homoscedasticity which when not  respected leads to a loss of efficiency of the model. Still regarding simple linear regression, I saw [here](https://www.bookdown.org/rwnahhas/RMPH/mlr-normality.html) that violating the assumption of normality of residuals would lead to incorrect inferences for models with small samples but would not have much impact on model inference with large sample sizes. I was wondering if it would be the same for the lcmm model ?

As part of my study, I just use the lcmm model for the classification of my individuals, should I take all the hypotheses into account?

Thank you.

**Comment by CecileProust-Lima** [comment]
Hi, 
sorry for the delay, I had not seen this issue. As Viviane wrote, this is a parametric model and it thus relies on assumptions. However, there is a certain robustness to slight deviations to the assumptions, as you mention for the linear model. 
We have not specifically evaluated the accuracy of classification under this type of misspecification. This could be done though. 
What we looked at is the issue of curvilinearity which led to the use of link functions in lcmm function : [https://doi.org/10.1093/aje/kwr243](https://doi.org/10.1093/aje/kwr243). 
Cécile
