### ISSUE TITLE
predictY with ordinal outcomes

### ISSUE THREAD

**Issue by caterinagregorio** [CecileProust-Lima/lcmm#244]
Dear Prof. Proust-Lima and lcmm team,

I am using the function lcmm with an ordinal outcome ( the variable is an interger), "thresholds" as link function and computeDiscrete = T. When using predictY, I expected to obtain intergers but I obtain predictions as my variable was continuous. Is that normal? If so, why? Is there a workaround that I am missing? Should I have specified some argument in predictY for the discrete case?

Thank you so much,
best,
Caterina

**Comment by VivianePhilipps** [comment]
Hi,

to predict your outcome, whatever its type (continuous or ordinal), you use the expectancy of the estimated distribution.
The expectancy of a binary (0/1) variable is not 0 or 1, but a value between 0 and 1. In the same way, the expectancy of an ordinal outcome is not necessarily an integer, so it is normal that the predictY functions returns real values and not integers.

Viviane
