### ISSUE TITLE
trajectory plot using the fixed-model intercept 

### ISSUE THREAD

**Issue by strawberry07** [CecileProust-Lima/lcmm#246]
Hi I was trying to plot the trajectories across time of different latent classes so I need to use the intercept and slope of each class in the fixed model, I should've used the second lcga3_results[["best"]][["intercept class1"]] which is 10.31 instead of the first one 1.12. The first one is class-membership model instead of fixed-model of time change. But the two numbers share the same index in the code so my trajectory plot is wrong. 
![Screenshot 2024-03-17 at 9 30 05 AM](https://github.com/CecileProust-Lima/lcmm/assets/35809146/400a6177-c973-4e42-b350-1203bede3c50)

**Comment by VivianePhilipps** [comment]
Hello,

indeed, different parameters can have the same name. You can either change the names, or you use the predictY function (and the associated plot) that does the computations for you.

Viviane
