### ISSUE TITLE
Number of latent classes not matching up to defined 'ng'

### ISSUE THREAD

**Issue by joexu05** [CecileProust-Lima/lcmm#25]
Dear Doctor Proust-Lima,
I am currently conducting research for a telephone health coaching service, which seeks to improve health outcomes 

I am looking to use the multlcmm function (from lcmm package) to classify participants based on their difference across 2 time points on a collection of outcomes measures (bmi, physical activity, waist circumference, fruit/vegetable consumption). Outcome variables are all continuous. 

When running this model:
`GHS_LCM5 <- multlcmm(bmi + pa + waistc + fruit + veg  ~ 1 + time , random = ~ 1 + time, mixture = ~ 1 + time, ng = 5,
                     subject="enrolment_id", data = GHS_LPA4, link = "linear", B = GHS_LCM1)`
 
The summary from this model is:
G | 5
loglik | -115063
npm | 30
BIC | 230375.6
%class1 | 10.53021
%class2 | 85.67201
%class3 | 0
%class4 | 0
%class5 | 3.797781

Class 3 and 4 do not seem to have any cases assigned, which is not something that I've encountered with other clustering packages such as mclust. 

I'm unsure if the issues arise from my model specifications, setup of data, or even choice of function, so any advice would be much appreciated.

Many thanks,
Joe

**Comment by CecileProust-Lima** [comment]
Hi Joe, 
it happens that a model converges to a (local) maximum which actually corresponds to a smaller number of latent classes, here it seems that is 3 classes. This comes from the multimodality of the likelihood (presence of local maxima) and this is not specific to the program but to mixture models in general. 
The solution is to run many different models from random initial values. This is provided in gridsearch function (please refer to the companion paper for that : https://www.jstatsoft.org/article/view/v078i02). 
I hope this helps, 
Cécile
