### ISSUE TITLE
Minimum number of samples for class

### ISSUE THREAD

**Issue by zandarina1** [CecileProust-Lima/lcmm#252]
Hello

I was wondering if there is any possibility to add a minimum number of samples per cluster in lcmm. As when I increase the number of clusters or it disappears one cluster or there are very few cases in some of the clusters. 

Thank you

**Comment by VivianePhilipps** [comment]
Hi,

we don't include such constraints in the estimation, sorry. It is true that very small classes are sometimes not relevant, but this is something that can on be checked after the estimation.

Viviane
