### ISSUE TITLE
multlcmm documentation unclear

### ISSUE THREAD

**Issue by barneyricca** [CecileProust-Lima/lcmm#253]
One section in the Details section of the multlcmm documentation, "B. THE VECTOR OF PARAMETERS B" is unclear. There are two errors.

First, the part that reads "(2)....When ng=1, the intercept is not estimated and no parameter should be specified in B. When ng>1, the first intercept is not estimated and only ng-1 parameters should be specified in B;" should probably read something like "(2)....When ng=1, the intercept is not estimated and no intercept parameter should be specified in B. When ng>1, the first intercept is not estimated and only ng-1 intercept parameters should be specified in B;". Otherwise, people might think that, for 
"fixed = CSE + PTG ~ 1 + time + I(time^2)" and ng = 3, no parameters would be specified for time or I(time*time), when 3 should be specified for each.

Second, in the enumeration of the parameter types, (5) is used twice. It should only be used once (and hence, what are now (5), (5), (6), (7), (8), and (9) should be (5) through (10).

**Comment by CecileProust-Lima** [comment]
thank you for identifying this. We will correct it. 
Cécile
