### ISSUE TITLE
Question about three level model or two level GMM model?

### ISSUE THREAD

**Issue by caitlin-ma** [CecileProust-Lima/lcmm#256]
Dear Cecile,

I am trying to fit a three level model or two level GMM model, that is the school as level 1, students as level 2 and different visits for the same students as level 3. And assume there are two latent groups. 

However, it looks like there is no option for me to fit this model. Would you mind telling if the package can handle this model? Thanks!

Best,

Caitlin

**Comment by CecileProust-Lima** [comment]
Hi Caitlin, 
sorry, we have not implemented the three-level model. You can only have two levels (i.e., subject=student and then repeated visits) within lcmm. 
Cécile
