### ISSUE TITLE
Wide Predicted Intervals for a Specific Subgroup in LCMM

### ISSUE THREAD

**Issue by cwhung0307** [CecileProust-Lima/lcmm#265]
Dear Prof. Proust-Lima  (@CecileProust-Lima, @VivianePhilipps)

First of all, thank you so much for this amazing package!

I am currently working with the `lcmm` function in R, using the thresholds link function for a binary outcome, to analyze patterns in my data. I decided on a model with 5 trajectory groups based on criteria such as BIC, entropy, and the proportion of group sizes.

However, I've encountered an issue with plotting these trajectories. Specifically, the predicted interval for one subgroup (class 2, red line in the screenshot, comprise about 27% of our population) spans almost the entire range of the panel. Upon examining the predicted values (using `predG5$pred` from `predictY()`), I noticed that the `Ypred_2.5_Class2`  and `Ypred_97.5_Class2` for this subgroup (class2) are almost exclusively close to 0 or 1.
![plot_G5_v00](https://github.com/user-attachments/assets/1ae3c573-fde4-43e6-8d96-52da4d46f229)

I suspect this issue might be due to the observed non-events(0) for this subgroup being concentrated within a narrow time span, which might be causing the confidence bands to be unusually wide, especially since most proportions are near the extremes of 0 and 1.

Could this be due to a limitation in calculating the confidence intervals when dealing with proportions near 0 or 1? If so, what steps would you recommend to address this issue and obtain more interpretable confidence intervals? (e.g. Clopper-Pearson interval? but how?)

I appreciate your guidance on how to resolve this matter.

Thank you for your assistance.

Best regards,

Ivy

**Comment by CecileProust-Lima** [comment]
Hi, 
I'm sorry for not getting back to you sooner. This is indeed weird, the first time for me. I suspect you have huge variance(s) for the parameter(s) associated with time. For instance, if all the individuals are concentrated in a short time frame in this class while you consider a splines basis for the time function, then probably some of the splines have an extreme variance. 
Given the problem is only for this specific class, it is very likely that the issue of huge variance is for this class-specific parameters. Check the summary with the parameter estimates. 
Cécile

**Comment by cwhung0307** [comment]
Dear Cécile, 

Thank you for taking the time to answer my question!

As you suspected, the variance for this particular class is quite large (please refer to the screenshot below):
![summary_class5](https://github.com/user-attachments/assets/e0904509-19cc-4488-bfc0-491e1219eb54)

I opted for 5 classes based on the selection criteria (i.e., lowest AIC, BIC, and entropy closer to 1). From the raw data, it appears that this particular subgroup (class 2) represents a unique trajectory.

![summaryplot](https://github.com/user-attachments/assets/7b7a3b07-f196-455a-882d-9de4ee0061f0)

However, given the large variance, do you think it would be better to select 4 classes instead of 5? What would you recommend?

Best regards,

Ivy

**Comment by CecileProust-Lima** [comment]
Well, you could either present the 4 class model or argue that the variance is wide for this specific class given the unique trajectory. This has to be discussed with your colleagues, and in any way, it is always a good thing to present the concordance of the results you have when assuming different numbers of classes (in supplementary). 
Cécile
