### ISSUE TITLE
Analyze time-missing data using the Lcmm

### ISSUE THREAD

**Issue by amaooo-wo** [CecileProust-Lima/lcmm#268]
Hi [@CecileProust-Lima](https://github.com/CecileProust-Lima), [@VivianePhilipps](https://github.com/VivianePhilipps),

Thank you very much for developing package.
I am using the lcmm package to identify latent classes. I encountered one problem.
I am currently doing a trajectory analysis related study with a sample size of 380 people. I want to use the hlme function in the lcmm package to predict the trajectory of exposure indicators over time. I have 7 time points, from T1 to T7, but the exposure indicators corresponding to each sample will be missing in some of these 7 time points, and the missing data structure is as follows. May I also directly fit the model with the hlme function in the lcmm package? If not, what do I do with the missing data (e.g. fill in?)

![8721724144555_ pic](https://github.com/user-attachments/assets/e9ea1f65-0e15-4dd2-9e5a-39b31f2e8e42)

I would most appreciate any guidance / support / additional resources that you can provide.

Thank you for your consideration of my (long winded) question.

Regards
linsey

**Comment by VivianePhilipps** [comment]
Hi,

you can have missing data on the outcome, it is not a problem. It is not required that all subjects/units have the same number of measurements.
Note however that the estimates are robust to missing at random data but not to missing not at random data (like any mixed model estimated in the maximum likelihood framework).

Best,

Viviane
