### ISSUE TITLE
LCMM vs HLME for BMI trajectories

### ISSUE THREAD

**Issue by shirine97** [CecileProust-Lima/lcmm#271]
Hello! Thank you so much for your work on this package. 

I am a PhD student using this package for the first time and I am learning a lot. I am currently working on identifying latent classes trajectories for BMI over the life course 3-58 years old. The BMI in my data is right skewed (skewness=1.170246), as BMI usually is. Please see the image below. 
![BMI Distribution](https://github.com/user-attachments/assets/e4c35b31-7806-42a4-82ec-30bfa498cb9b)

Should I be using the lcmm function instead of hlme? I have seen some other papers use hlme when it comes to BMI data. 

Furthermore, even after fitting a model, my qq plot does not look normal as we can see below:
<img width="382" alt="Screenshot 2024-08-31 at 12 08 42 PM" src="https://github.com/user-attachments/assets/b70abc97-06dd-47ae-a999-e4067c1bae19">

It is not normal regardless of me using hlme or the lcmm package. Is this problematic?

Thank you very much for your time. It is really appreciated.

**Comment by VivianePhilipps** [comment]
Hi,

the BMI's distribution is often symmetric in a general population. Maybe your sample in slightly selected and exhibits therefore a skewness. According to your histogram, the link function seems necessary.
I the qqplot doesn't look fine, you can try a more flexible link (splines, higher number of knots, different location of knots).

Best,

Viviane
