### ISSUE TITLE
spline prediction with hlme and predictY

### ISSUE THREAD

**Issue by hugues-sj** [CecileProust-Lima/lcmm#28]
Dear Dr Proust-Lima, 

I am exploring heterogeneity in response to a treatment using a spline within the 'hlme' function. I encountered an issue when computing the prediction of the model for a new set of 'x' values. For simplicity, I illustrate here the issue using simulated data without response heterogeneity (ng=1), i.e., this permit to fit the model using both 'lmer' and 'hlme' and then to compare the predictions (see the reproducible example 'lcmm_test2.txt' attached):

![prediction_issue](https://user-images.githubusercontent.com/52541194/60710810-cdf39b00-9f13-11e9-834e-6c69f2eede04.jpeg)

On this plot we have:
- In grey: the simulated data
- In red: the  the predictions obtained using the function predict.merMod from the lmer package
- In blue: the predictions obtained using the predictY function 
- In yellow: the sample means

You suggested in an offline discussion that this might be due to the definition of the range of the spline and thus to explicitly define it when calling the spline function 'ns'. I thus tried to explicitly provide knots and Boundary.knots:

_kk <- quantile(dt$x, prob=seq(0,1,len=5))[2:4]
rr <- range(dt$x)
hm1 <- hlme(y~ns(x,knots=kk, Boundary.knots=rr),subject="id",ng=1,data=dt)_

but I get the following error:
Be patient, hlme is running ...
**Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  :
  arguments imply differing number of rows: 500, 3, 2**

Then I tried  to explicitly provide the basis. This worked for the call to the 'hlme' function but I finally get an error with the predictY function when trying to predict for a new set of 'x' values: 

_mybasis<- ns(dt$x,knots=kk, Boundary.knots=rr)
hm1 <- hlme(y~mybasis,subject="id",ng=1,data=dt)
mynewbasis <- predict(mybasis, newdt2$x)
predictY(hm1, newdata=mynewbasis, var.time="x")_

but get the following Error:
**newdata should at least include the following covariates:
mybasis NA
Error in predictY.hlme(hm1, newdata = mynewbasis, var.time = "x") :
  see above**

It seems that there are two problems here. First, the predictY does not find the expected variable and second, it is not clear for me what should be provided as 'var.time' because here we longer have a time variable such as 'x'.

Can you please advise on how we should parametrize the 'hlme' and 'predictY' functions when using spline as a covariate (see the reproducible example 'lcmm_test2.txt' attached) to obtain the correct predictions ?

Thank you in advance for your time, 

Kind regards,

Hugues.

[lcmm_test2.txt](https://github.com/CecileProust-Lima/lcmm/files/3362646/lcmm_test2.txt)

**Comment by VivianePhilipps** [comment]
Dear Hugues,

there is effectively a problem with the definition of the splines basis when using the df option. In predictY, the splines basis is recreated with the new prediction data. So it will not be the same basis as for the estimation, unless the time points are identical. You can check that if you define newdt2 like dt, the plot will be correct.

The solution is to use knots and Boundary.knots as you suggested, but without putting them in variables : 

 hm1 <- hlme(y~ns(x,knots=c(0.2222,0.5,0.7778), Boundary.knots=c(0,1)),subject="id",ng=1,data=dt)

This way, your basis will be the same whatever the time points you are defining in newdt2.
This will also avoid false results if you redefine accidentally the rr and kk variables.

Regards,

Viviane

**Comment by hugues-sj** [comment]
Dear Viviane, 

Thank you for your feedback and for providing this workaround. I hope it can be solved in a future release of the package. In the meantime I wrote a wrapper  function `hlme2` (source code in attached file hlme2.txt) that feeds the `hlme` function according to your approach. 

```
## hlme2 usage examples
hm1 <- hlme2(y~ns(x,df=5),subject="id",ng=1,data=dt)
hm2 <- hlme2(y~bs(dt$x,df=5),subject="id",ng=1,data=dt)
hm3 <- hlme2(y~ns(x,df=5),subject="id",ng=2, mixture=~ns(x,df=5),data=dt)
```

Continuing example of the original post:
```
hm1 <- hlme2(y~ns(x,df=5),subject="id",ng=1,data=dt)
newdt2$phm1 <- as.numeric(predictY(hm1, newdt2, var.time="x")$pred)
(pp + geom_line(data=newdt2, aes(x=x, y=plm1, color="a"), size=2, show.legend=TRUE)
    + geom_line(data=newdt2, aes(x=x, y=phm1, color="b"), linetype=2, size=2, show.legend=TRUE)
    + geom_point(data=newdt2, aes(x=x, y=smeans, color="c"), size=2, show.legend=TRUE)
    + ylab("y")
    + scale_color_manual(name = "",
                         values = c("a" = "darkblue", "b" = "red", "c"="yellow"),
                         labels=c("predict.merMod(lme4)","predictY(lcmm)","Sample means"))
    + guides(colour = guide_legend(override.aes = list(linetype = c(1,2,0), shape=c(NA,NA,19)))))

```

![hlme2](https://user-images.githubusercontent.com/52541194/61462501-031bd680-a973-11e9-81f1-e60da84f9d17.jpeg)

[hlme2.txt](https://github.com/CecileProust-Lima/lcmm/files/3406776/hlme2.txt)


Kind regards,

Hugues.

**Comment by CecileProust-Lima** [comment]
Thank you for your feedback. 
Cécile
