### ISSUE TITLE
error running permut function 

### ISSUE THREAD

**Issue by reneelipka** [CecileProust-Lima/lcmm#282]
Dear authors, 

thank you so much for your great package and all the help on the issues page! 

I am relatively new to R and programming overall, so I hope I am providing all the relevant information. I have run 1-4 class models trying to extract latent cortisol classes with hippocampus variables (activation, thickness) as class-mb predictors. I am trying to permut the 3-class model to use a more sensible reference class, but get an error message: 

m3_hippo_allpred_perm <- permut(m3_hippo_allpred, order=c(2,3,1))

Error in .Contlcmm(fixed = fixed, mixture = mixture, random = random,  : 
  Vector B should be of length 31
  
Indeed, length(m3_hippo_allpred$best)
[1] 25

This error does not occur in the 4-class model. But I don't see an issue with the 3-class model: it met convergence criteria and all parameters were estimated:

summary(m3_hippo_allpred)
General latent class mixed model 
     fitted by maximum likelihood method 
 
lcmm(fixed = formula_fixed, mixture = formula_mixture, random = formula_random, 
    subject = subject, classmb = formula_classmb, ng = ng, link = link, 
    data = data_long)
 
Statistical Model: 
     Dataset: data_long 
     Number of subjects: 281 
     Number of observations: 2486 
     Number of observations deleted: 43 
     Number of latent classes: 3 
     Number of parameters: 25  
     Link function: Quadratic I-splines with nodes  
0.51 6.5975 12.685 18.7725 24.86  
 
Iteration process: 
     Convergence criteria satisfied 
     Number of iterations:  2 
     Convergence criteria: parameters= 3e-06 
                         : likelihood= 2.9e-06 
                         : second derivatives= 4.7e-08 
 
Goodness-of-fit statistics: 
     maximum log-likelihood: -4616.37  
     AIC: 9282.74  
     BIC: 9373.7  
 
 
Maximum Likelihood Estimates: 
 
Fixed effects in the class-membership model:
(the class of reference is the last class) 

                                      coef      Se    Wald p-value
intercept class1                   3.11119 0.78395   3.969 0.00007
intercept class2                  -2.36106 2.15528  -1.095 0.27331
hippocampus_var2_avg class1       -0.00885 0.41034  -0.022 0.98278
hippocampus_var2_avg class2        2.57094 1.07919   2.382 0.01721
hippocampus_delta_var2_avg class1  0.18823 0.40375   0.466 0.64107
hippocampus_delta_var2_avg class2  0.96435 0.80509   1.198 0.23099
hippocampus_vol_avg class1        -0.80984 0.38612  -2.097 0.03596
hippocampus_vol_avg class2         0.59206 0.83712   0.707 0.47941

Fixed effects in the longitudinal model:

                                     coef      Se    Wald p-value
intercept class1 (not estimated)        0                        
intercept class2                  1.34027 0.55522   2.414 0.01578
intercept class3                 -1.03610 0.51051  -2.030 0.04240
time_n class1                     0.00280 0.00124   2.263 0.02364
time_n class2                    -0.02179 0.00574  -3.795 0.00015
time_n class3                     0.03780 0.00816   4.632 0.00000
sex1                             -0.59975 0.16189  -3.705 0.00021
age                              -0.01051 0.01027  -1.024 0.30602

Variance-covariance matrix of the random-effects:
          intercept  time_n
intercept   1.40163        
time_n     -0.00042 0.00012

Residual standard error (not estimated) = 1

Parameters of the link function:

               coef      Se    Wald p-value
I-splines1 -5.97874 0.33925 -17.623 0.00000
I-splines2  2.30883 0.04229  54.590 0.00000
I-splines3  1.44808 0.05391  26.863 0.00000
I-splines4  1.31109 0.07194  18.224 0.00000
I-splines5  0.98535 0.14621   6.740 0.00000
I-splines6  0.84604 0.24562   3.445 0.00057
I-splines7  0.68615 0.28333   2.422 0.01545

Could you point me to how I can fix this problem? 

Thanks so much in advance and kind regards, 
Renée

**Comment by VivianePhilipps** [comment]
Hi Renée,

I guess it is because you put the arguments (fixed, random, ng, etc) in variables instead of write them explicitly in the call. Could you please try it without variable, for example
`
lcmm(fixed = Y ~ t * x, mixture = ~ t, random = ~ 1, subject = "ID",  ng = 3, data = data_long)`

instead of

```
formula_fixed <- Y ~ t * X
formula_random <- ~ 1
formula_mixture <- ~ t
ng <- 3
lcmm(fixed = formula_fixed, mixture = formula_mixture, random = formula_random, subject = "ID",  ng = ng, data = data_long)
```

Viviane

**Comment by reneelipka** [comment]
Ah yes, I did because I was running multiple models as a loop over night.
That fixed the problem - thank you so much for your help and the swift response :)
