### ISSUE TITLE
Aberrant predicted trajectories in plot due to limited follow-up

### ISSUE THREAD

**Issue by sveldka3** [CecileProust-Lima/lcmm#285]
Hello, thanks very much for creating this package.
I have a 3-class lcmm model with Galectin-9 as longitudinal marker over time and I want to plot the predicted trajectories with the marker values on the y-axis. 

I log-transformed the Galectin-9 variable because it had a skewed distribution.
```r
data_biom$log_gal9 <- log(data_biom$Galectin9)
``` 

Final LCMM model (tp.months = months since diagnosis):
```r
gal9_log_qf_spl_3 <- lcmm(log_gal9 ~ poly(tp.months, degree = 2, raw = TRUE),
                            mixture = ~poly(tp.months, degree = 2, raw = TRUE), 
                            random = ~poly(tp.months, degree = 1, raw = TRUE), 
                            subject = "id", 
                            ng = 3, 
                            data = data_biom, 
                            link = "splines",
                            B = gal9_log_qf_spl_1,
                            verbose = FALSE)
```
The output of postprob():
Posterior classification: 
  class1 class2 class3
N   12.0     40  108.0
%    7.5     25   67.5
 
Posterior classification table: 
     --> mean of posterior probabilities in each class 
        prob1  prob2  prob3
class1 0.7995 0.0002 0.2003
class2 0.0037 0.8117 0.1846
class3 0.0745 0.0998 0.8258
 
Posterior probabilities above a threshold (%): 
         class1 class2 class3
prob>0.7  58.33   70.0  71.30
prob>0.8  58.33   62.5  60.19
prob>0.9  50.00   42.5  41.67

When I plot the weighted subject-specific predictions with which = 'fit', I get the latent process scale on the y-axis (right?). Class 2 goes up slightly but has limited follow-up, which can also be seen in the spaghetti plots of the observed values in the different classes.
```r
plot(gal9_log_qf_spl_3, which = "fit", var.time = "tp.months", bty="l", marg=F, shades = TRUE, legend.loc = "topright")
```
![image](https://github.com/user-attachments/assets/ff6063da-e1ef-4be7-90ca-89bb3d99e113)
```r
# Create the spaghetti plot of log Gal9 by class
ggplot(data_biom, aes(x = tp.months, y = log_gal9, group = id, color = gal9_lcmm3_class)) +
  geom_line(alpha = 0.5) +  
  facet_wrap(~ gal9_lcmm3_class) +      
  labs(title = "Spaghetti Plots of log(Galectin-9) by Class",
       x = "Time (Months)",
       y = "log(Galectin-9)") +
  theme_minimal() +
  theme(legend.position = "none")  

# Create the spaghetti plot of original Gal9 by class
ggplot(data_biom, aes(x = tp.months, y = Galectin9, group = id, color = gal9_lcmm3_class)) +
  geom_line(alpha = 0.5) + 
  facet_wrap(~ gal9_lcmm3_class) +     
  labs(title = "Spaghetti Plots of Galectin-9 by Class",
       x = "Time (Months)",
       y = "Galectin-9") +
  theme_minimal() +
  theme(legend.position = "none")
``` 
![image](https://github.com/user-attachments/assets/97bcf3dd-90bb-49b6-98be-2be596c6cbaa)
![image](https://github.com/user-attachments/assets/a4b7d45e-34b8-41eb-8bbd-4f2b670be602)

However, when plotting the predicted values (the log values and back-transformed original values) using PredictY and plot(), the predicted trajectory of class 2 continues with a very sharp increase:

```r
newdata <- data.frame(tp.months = seq(min(data_biom$tp.months), max(data_biom$tp.months), length.out = 100))

gal9_log_qf_spl_3_pred <- predictY(gal9_log_qf_spl_3, newdata = newdata, var.time = "tp.months", draws = TRUE) 

gal9_log_qf_spl_3_predexp <- gal9_log_qf_spl_3_pred
gal9_log_qf_spl_3_predexp$pred <- exp(gal9_log_qf_spl_3_pred$pred)

plot(gal9_log_qf_spl_3_pred, lty=1, xlab="Months", ylab="Galectin-9 (log)", legend.loc = "topleft", cex=0.75) #logvalues

plot(gal9_log_qf_spl_3_predexp, lty=1, xlab="Months", ylab="Galectin-9", legend.loc = "topleft", cex=0.75) #original values
```
![image](https://github.com/user-attachments/assets/54248bfb-8c28-4733-8efa-abdcf2b94a01)
![image](https://github.com/user-attachments/assets/2e7f811c-1785-4d76-ba64-e8cb3e73aebf)

I think this prediction is based on the final few observed values in class 2 (1 patient in which Galectin9 increases), but I don't think the predicted trajectory is representative of this class, as it suggests that the values have an enormous increase in this class and remain very high. The plot with weighted subject-specific predictions seems much more representative of the data, but is difficult to interpret with the latent process on the y-axis.

So my question is: how to get a representative plot of the trajectories with Galectin9 on the y-axis in its original scale (either log or backtransformed)?
Can I truncate the follow-up in the plot of the PredictY values?
Can I place Galectin9 in its originale scale on the y-axis in the plot with weighted subject-specific predictions? (like in the vignette [https://cecileproust-lima.github.io/lcmm/articles/joint_latent_class_model_with_Jointlcmm.html](url) section 4.3, where normMMSE is in its original scale on the y-axis rather than the latent process?)

Thank you very much.

**Comment by VivianePhilipps** [comment]
Hello,

here you have two transformations of your outcome : the log and the splines.
You log transformed the Galectin to be closer to the Gaussian distribution, so you could use the hlme function. Indeed, the link function in lcmm is used to transform the outcome so that the Gaussian assumption holds. So either you use hlme on the log(Galectin) or you use lcmm with splines link function on the original Galectin.
Please note that in your analysis (log + splines), you can't back transform the predictions. The prediction of the Galectin is not the exponential of the prediction of the log(Galectin). Specific computation has to be done to go back to the original scale. In the lcmm package, this back transformation is implemented for hlme models (but not for lcmm models) in the predictYback function. 

For the plot, in you want to truncate one trajectory, you have to remove the values in the predictY output (in one column of gal9_log_qf_spl_3_pred$pred in your case). Sorry, there is no automatic implementation for now.

Best,

Viviane

**Comment by sveldka3** [comment]
Dear Viviane,

Thank you very much for your response, it was very helpful. Two small follow-up questions:
- can I directly compare the BIC value of a hlme() model with log-transformed variable with the BIC of an lcmm() model with original variable with splines link?
- I cannot find the predictYback function in the lcmm package? 

Best,
Saskia

**Comment by VivianePhilipps** [comment]
No, the two models consider different outcomes (log(Galectin) versus Galectin), so you can't compare the BIC (or likelihood, or AIC, ...)

The predictYback function is for now only available in the github version, no in the CRAN version. To install it you can do :
`
remotes::install_github("https://github.com/CecileProust-Lima/lcmm.git")`

Best,

Viviane

**Comment by sveldka3** [comment]
Thank you, it worked!
