### ISSUE TITLE
Questions about plotting 

### ISSUE THREAD

**Issue by jenellong-IHDP** [CecileProust-Lima/lcmm#291]
Thanks for this package. Apologies if these are basic questions, but I can't seem to find an answer. 

1. When plotting predictions versus observed data, how do I make the legend box background transparent? Currently, the legend is blocking the plotted lines.

2. How can I make a plot showing both the predicted mean trajectory for each class and observed trajectories of individuals? I would like to do this to visualise the extent to which the class trajectories reflect the observed data, as recommended by van de Schoot et al. ([2016](https://www.tandfonline.com/doi/full/10.1080/10705511.2016.1247646)). I understand that `geom_smooth(method = "loess")` is not suitable (#225). How should I accomplish this instead? 

Thank you!

**Comment by VivianePhilipps** [comment]
Hi,

the option bg = "transparent" should do that. You can also move the legend with legend.loc = "top" or "bottomleft" for example.

For the plot, you will have to merge the data and model$pprob so that you have the assigned class along with the observations. Then, you can add the prediction. Here is an example :

assume you have estimated a 2 class model "model2" on data "dsim".
```
  model2 <- hlme(Y1 ~ t, random = ~t, subject = "ID", data=dsim, ng=2, mixture= ~t, B=model1)
  d <- merge(dsim, model2$pprob)
  pred2 <- predictY(model2, newdata=data.frame(t=seq(0,10,0.2)), var.time="t", draws=TRUE)

## for class 1
  plot(0, col = "white", xlim = range(pred2$times), ylim = range(pred2$pred, d$Y1), main = "class 1") # initialize the window
  for(i in 1:length(unique(d$ID))) # loop over the subjects to plot the observations
  {
      di <- d[which(d$ID == i),]
      if(di$class[1] != 1) next
      lines(di$t, di$Y1, col = "grey")
  }
   plot(pred2, col = c("black", "transparent"), shades = TRUE, add = TRUE, lty = 1) # add the predicted trajectory

## the same for class 2
  x11() # new window
  plot(0, col = "white", xlim = range(pred2$times), ylim = range(pred2$pred, d$Y1), main = "class 2")
  for(i in 1:length(unique(d$ID)))
  {
      di <- d[which(d$ID == i),]
      if(di$class[1] != 2) next
      lines(di$t, di$Y1, col = "grey")
  }
   plot(pred2, col = c("transparent", "red"), add = TRUE, shades = TRUE, lty = 1)

```

Best,

Viviane

**Comment by jenellong-IHDP** [comment]
Thanks so much for this clear and concise explanation Viviane!
