### ISSUE TITLE
Question about the package lcmm  

### ISSUE THREAD

**Issue by Ruoyu-Miao** [CecileProust-Lima/lcmm#30]
I used your R package "lcmm" to ran the code in the "Estimation of Extended Mixed Models Using Latent Classes and Latent Processes: The R Package lcmm" in Rstudio of Mac, Windows system and Rstudio Server, web terminal client (Minerva). The R code I ran is in chapter 6.5 Jointlcmm examples. I am sure the code I ran in different servers was same as what you have shown. But the results of summarytable(mj4b) were different. The results from R software in Mac and Windows were the same as yours in page 43 while the result of  summarytable(mj4b) from Minerva was different. Please see the attachment for the different result of summarytable(mj4b).  I think there may be some computational issues in this package when the conversion happens between C++ and R language. Could you please check it for this issue? Thank you very much.
![results](https://user-images.githubusercontent.com/53627529/62400324-b80ae180-b576-11e9-9119-05fbbf6a9302.jpeg)
[lcmm.pdf](https://github.com/CecileProust-Lima/lcmm/files/3462980/lcmm.pdf)

**Comment by CecileProust-Lima** [comment]
Thank you for your feedback. What you find seems to be a local maximum: the model converged toward the 3 class model (see the same likelihood as in mj3b and one class at 0 probability). I have no experience with Minerva but the iterative algorithm might have gone in a slightly different direction and thus did not converge to the same maximum. 
This is not a problem of the model specification: convergence to local maxima happens and this is why multiple initial values need to be tested. 
Cécile
