### ISSUE TITLE
Error in multlcmm with prior latent class

### ISSUE THREAD

**Issue by BochaoJ** [CecileProust-Lima/lcmm#32]
Hi,

It works good for me using some prior latent class under the function "hlme", However, if I want to use the same prior information on the multlcmm function, it doesnot work. The function does not return any error, but it does not use the prior information given in the function.  The prior covariates are 1,2,3 (if I assume 3 clusters) and 0 (for impute). However, the function multlcmm imputed the subject's label with given prior =1,2,or 3, instead of the the subject's label with given 0. 

Could you please check ? Thank you so much !

Bochao Jia

**Comment by BochaoJ** [comment]
Hi,
I also found that the  prior latent class option does not work in Jointlcmm function. Could you please check that as well? Thanks.

Bochao

**Comment by VivianePhilipps** [comment]
Hi Bochao,

thank you for you feedback. I have corrected the 2 functions, the prior option should now work fine. Could you please check with this updated version?

Best,
Viviane
