### ISSUE TITLE
Question about finding the best link function

### ISSUE THREAD

**Issue by JsabelHodel** [CecileProust-Lima/lcmm#34]
Dear Dr. Proust-Lima and lcmm-team,

I would like to use the R package lcmm to find classes of trajectories in longitudinal data with up to 4 repeated unstructured measurement time points of an outcome measuring people’s performance in activities of daily living. The outcome is a sum score of several items and its ranging from 0 to 100. Within a previous analysis, the sum score was transformed from an ordinal into an interval/continuous sum score using Rasch Measurement Model theory. Still, I am unsure if I should fit a Latent Class Linear Mixed Model (hlme function) or a Latent Process Mixed Model (lcmm function). As I found in your work, the lcmm function is used for ordinal, bounded or curvilinear outcomes or outcomes with non-Gaussian random effects and errors. Could you explain what you mean by curvilinear? And is there a way to know if random effects and errors are Gaussian or not? 

Since my outcome is at least bounded, I tried to go on using the lcmm function and find the best link function by comparing the discrete AICs that should be provided in the respective model summaries (as described in your paper Estimation of Extended Mixed Models Using Latent Classes and Latent Processes: the R package lcmm). Unfortunately, this discrete AIC values do not show up in my model summaries no matter which link function I test (I am using the lcmm package version 1.8.1). Could you advise me on how to solve this problem? 

Thank you very much for your support!
Best regards, Jsabel

**Comment by CecileProust-Lima** [comment]
Dear Jsabel, 
the discrete AIC will be output as soon as your dependent variable is discrete. Maybe this is not the case in your example. For instance, it appears in the example below:
lm <- lcmm(IST ~ I(age-age_init), random=~ I(age-age_init), subject="ID",data=paquid)
lm
summary(lm)

The curvilinearity is linked to the problem of unequal interval scaling you were trying to address with the Rasch model. It more generally account for a departure from the normality of the dependent variable. 
Regarding the errors and random effects, they are Gaussian (or mixture of Gaussian) in the package but only in the normalized scale of the outcome, once curvilinearity is dealt with using the link function.

**Comment by JsabelHodel** [comment]
Dear Cecile
Thank you very much for your feedback! 
Indeed, my dependent variable is not discrete. 
Regarding the testing of the link functions: Since I used the Rasch Model to transform my dependent variable into an interval-scale beforehand, I think I don’t need to  test the threshold link function. And in this case, in order to find the best fitting link function I could compare the remaining ones (beta, splines) via the usual AIC. Is this the correct approach? (I think it still makes sense to test the best link function even though I Rasch-transformed my dependent variable, because it could still be non-normal or prone to flooring/ceiling effects)
Thanks again for your support!
Best wishes, 
Jsabel

**Comment by CecileProust-Lima** [comment]
Dear Jsabel, 
I am really sorry I did not answer your last comment. If you want to consider your dependent outcome as a continuous outcome then you can use the standard AIC or other criterion based on the reported likelihood. The discrete information criteria are only reported when the user wants to compare the fit of a model based on a Lebesgue measure with the one of a model that relies on a counting measure. 
Cécile
