### ISSUE TITLE
How is lcmm different from latent growth curve modeling?

### ISSUE THREAD

**Issue by MaryWaterloo** [CecileProust-Lima/lcmm#37]
Dear Professor Proust-Lima,

I wonder how is lcmm different from latent growth curve modeling and what are the advantages of lcmm over  latent growth curve modeling for analyzing longitudinal ordinal data?

Thanks,
Mary

**Comment by CecileProust-Lima** [comment]
Latent growth curve modeling is relatively similar to mixed models. They are both methods for longitudinal data that capture correlation within repeated measures using random effects. There are some differences though between the techniques regarding measurement error or data structure. One of them is that mixed models naturally handle visit times that can be different from one subject to the other. 
LCMM builts on the theory of mixed models to model repeated data.

**Comment by MaryWaterloo** [comment]
So, latent growth curve modeling cannot handle different measurement times for longitudinal data collection? and that is the only advantage?

Thanks,
Mary
