### ISSUE TITLE
How to specify mixture in models with multiple classes?

### ISSUE THREAD

**Issue by Aquariusquintini** [CecileProust-Lima/lcmm#4]
One of the model parameter in case of multiple classes is ‘Mixture’. From the manual of the package and a google search, it did not became clear to me what this parameter does exactly and how to specify it.

In the examples in the manual, this parameter is always the same as the ‘Random’ parameter, but I wonder if this is always the case? When I want to create a model with ( heart rate ~ measurementNr + age + gender + hasDiabetes ), with measurementNr (time variable as integer), age (integer) and gender (male/female), hasdiabetes (y/n). Should I include measurementNr as mixture or also any of the other parameters?

Could you please clearify what the 'mixture' parameter does/means?

**Comment by CecileProust-Lima** [comment]
Mixture parameter specifies the formula for the fixed effects that are different from one class to the other (class-specific). Most of the time, the time variables are put in mixture and also put in random. But this is not a requirement. You could in some context consider a covariate effect (other than a time function) with a class-specific effect. In this eventuality, the covariate would have to be specified in mixture formula. 
Cécile
