### ISSUE TITLE
Interpretation of output - # parameters, df for max. log-likelihood, best goodness of fit statistic

### ISSUE THREAD

**Issue by lydiantoinette** [CecileProust-Lima/lcmm#41]
Dear Dr. Proust-Lima,

We are currently trying to classify participants on daily mood questionnaires using lcmm (thank you so much for creating such a helpful tool for analysis).

As we are relatively new to this type of analysis, we had a few quick questions regarding our output:

1. Is there a way to find out the number of degrees of freedom that the model used? Or what is the best way to interpret the significance of maximum log-likelihood statistic? 
2. What do the “number of parameters” refer to in the statistical model output? (Is this in any way related to the number of levels in our dependent categorical variable?)
3. Is there any methodological best practice for which Goodness-of-fit statistic to use for choosing the appropriate number of classes per model (i.e. AIC vs BIC vs Log-likelihood)?

Thank you in advance!

**Comment by CecileProust-Lima** [comment]
Dear lydiantoinette, 
1. When you compare two (nested) models with the log-likelihood ratio test (LRT), the difference in the number of parameters between the two parameters defines the number of degrees of freedom in you Chisquare distribution (with exception for two nested models with a different number of classes - the LRT does not follow a Chisquare distribution anymore under the null hypothesis). 
2. The number of parameters in the output is the total number of parameters that are estimated in the model (fixed effects, variance-covariance parameters, link functions parameters, etc). This is very classic when estimating any parametric model. 
3. All methods have been criticized but BIC has shown better performances in simulations over the years (in all mixture contexts, not only lcmm). After that, choosing the number of latent classes is always a tricky question. The recommendation is to consider various indicators: BIC, size of classes, discrimination, etc. Please refer to this vignette of the package : 
[https://cran.r-project.org/web/packages/lcmm/vignettes/usual_problems.html#how-to-choose-the-number-of-latent-classes](https://cran.r-project.org/web/packages/lcmm/vignettes/usual_problems.html#how-to-choose-the-number-of-latent-classes)

Cécile

**Comment by lydiantoinette** [comment]
Thanks very much for your response, Dr. Proust-Lima!
