### ISSUE TITLE
Release your package to R CRAN

### ISSUE THREAD

**Issue by BochaoJ** [CecileProust-Lima/lcmm#43]
Hi,

I wonder could you update your packages to R CRAN? Currently, the Version 1.8.1 has some errors in some functions such as: the prior option is not correct in jointlcmm and multilcmm. So If you could upload a new verion of package to CRAN, our collegues can use it more easily. Thanks.

**Comment by CecileProust-Lima** [comment]
On the current version on the CRAN, the main functions calculations are not incorrect. You are right that a bug on the name of the prior argument has been identified but this does

**Comment by CecileProust-Lima** [comment]
We plan the release on cran of a new version in the next weeks.

**Comment by BochaoJ-Lilly** [comment]
Hi Professor,
I wonder did you update your "lcmm" package on R cran? Many Thanks!

**Comment by CecileProust-Lima** [comment]
Hi, 
I am happy to announce that the new version of lcmm is now on cran : version 1.9.1. 
It includes the changes with prior but also other interesting new features such as a gridsearch with parallel computations or the estimation of latent class models for multiple longitudinal markers in mpjlcmm function. 
Best
Cécile
