### ISSUE TITLE
R package: Latent Class Growth Analysis or Growth Mixture Modeling

### ISSUE THREAD

**Issue by jwiehn** [CecileProust-Lima/lcmm#44]
Dear Cécile,

within the framework of my PhD Programme, I'm doing research on the development and course of depressive symptoms in children and adolescents. 

In one of my research projects I aim to identify differences in longitudinal change among unobserved groups according to their developmental trajectory of depressive symptom severity (CES-DC). For this purpose, I'm looking for an R package applying Latent Class Growth Analysis (LCGA) or Growth Mixture Modeling (GMM) (Jung & Wickrama, 2008; Nagin, 1999). 

Other packages such as the k-means longitudinal clustering approach (R package kml) are highly flexible and easy to administer, but I'm looking for a model-based approach to classifiy my sample into distinct trajectory groups. Are you aware of an LCGA or GMM R package, or is your R package 'LCMM' suitable for the research interest as described above?

Best wishes from Berlin
Jascha

**Comment by CecileProust-Lima** [comment]
Thanks Jascha for the question. 
lcmm R package can fit both GMM and LCGA:
1) Latent class mixed model and growth mixture model are the same approach. It's just that latent class mixed model come from the mixed model theory (in biostatistics) and growth mixture model comes from the latent growth models (in psychometrics) but they do the same : a regression at the population level (fixed= in the hlme, lcmm, multlcmm or jointlcmm functions) with possibly class-specific effects (mixture= in the same functions) and at the individual level with random effects (random= and subject= in the functions). 
2) LCGA is exactly the same as a GMM/LCMM model EXCEPT THAT (this difference is very important) there is no regression at the individual level, i.e. no random-effects. As such, it is assumed that within a latent class all the observations (especially the repeated measures of the same individual) are independent. This is why this method usually finds more latent classes than GMM. See the chapter of Muthen, section 6.5.1 in which both methods are compared : [https://www.statmodel.com/download/ChapmanHall06V24.pdf](https://www.statmodel.com/download/ChapmanHall06V24.pdf)

Anyway, you can fit LCGA with lcmm R package : you just need to specify no random effect! This is done with random=~-1 in lcmm or hlme. 

Cécile
