### ISSUE TITLE
Is it possible to have a link equal to 'cnorm' in Stata 'traj' pkg?

### ISSUE THREAD

**Issue by huangmozhilv** [CecileProust-Lima/lcmm#47]
Hi,

I'm trying to implement Group-based multi-trajectory modelling (Nagin et al 2016) with `multlcmm` function in `lcmm` pkg, because I want to use the constructed model to predict new cases. However, I find the data were better fitted Stata pkg `[traj](https://www.andrew.cmu.edu/user/bjones/index.htm)`(Nagin et al 2016), 

The code was:
`traj, multgroups(4) ///
var1(bio1*) indep1(log_days*) model1(cnorm) min1(0) max1(100) order1(2 2 2 2) ///
var2(bio2*) indep2(log_days*) model2(cnorm) min2(0) max2(100) order2(2 2 2 2)`

The output graph is as below:
![image](https://user-images.githubusercontent.com/26662685/83144423-e53c0800-a125-11ea-88e9-9fd8d55332e1.png)
Fig Notes: colored lines showed the observed trajectories for each patient. The black smoothed lines were the predicted trajectories for each group and were plotted with the estimates from 'multtrajplot'. 

I tried to use link='3-quant-splines' in `multlcmm` function. 
The code is: 

```
formula <- 'I(log_days) + I(log_days^2)'
link <- '3-quant-splines'
m1 <- multlcmm(as.formula(paste0("bio1 + bio2~", formula)),
           random=as.formula(paste0("~", formula)),
           ng=1,
           subject = 'numID',
           data=dat,
           link = c(link, link))
m <- multlcmm(as.formula(paste0("bio1 + bio2", formula)),
               random=as.formula(paste0("~", formula)),
               mixture=as.formula(paste0("~", formula)),
               ng=4,
               subject = 'numID',
               data=dat,
               link = c(link, link),
               B = random(m1))
```

However, the output figure is:
![image](https://user-images.githubusercontent.com/26662685/83147979-f2a7c100-a12a-11ea-8d6d-661e2ccedfeb.png)

There are two questions with the above result:
1. The output 4 groups were not that different from each other visually.
2. The estimated trajectories for each group did not fit the data well, especially for Group1.

**Therefore, my question is, is it possible to have a `multlcmm` model with the link same to `cnorm` in Stata pkg `traj`?**

**Comment by CecileProust-Lima** [comment]
Hi, 
a possible reason for this lack of fit is that you used a quadratic function of time. is it really plausible given the pikes you have? You could try any function of time, or approximations using natural splines for instance (ns function in splines package). 
Another point; with multlcmm, you assume both bio1 and bio2 measure the exact same underlying variable. Is it your assumption? Otherwise, there is a new function in version 1.9.1 on cran which fits latent class models for multivariate longitudinal markers that do not measure the same variable. 
For the link function, I did not include "cnorm" because, in my experience, I have never encountered a situation where it is a good choice compared to the flexible splines link function. When a variable is bounded, it usually has a non-Gaussian distribution in the range of plausible levels. 
Best
Cécile

**Comment by huangmozhilv** [comment]
> Hi,
> a possible reason for this lack of fit is that you used a quadratic function of time. is it really plausible given the pikes you have? You could try any function of time, or approximations using natural splines for instance (ns function in splines package).
> Another point; with multlcmm, you assume both bio1 and bio2 measure the exact same underlying variable. Is it your assumption? Otherwise, there is a new function in version 1.9.1 on cran which fits latent class models for multivariate longitudinal markers that do not measure the same variable.
> For the link function, I did not include "cnorm" because, in my experience, I have never encountered a situation where it is a good choice compared to the flexible splines link function. When a variable is bounded, it usually has a non-Gaussian distribution in the range of plausible levels.
> Best
> Cécile

Thanks very much for the reply.  But what do you mean 'measure the same underlying variable'? 'bio1' and 'bio2' are two measures for a same outcome (i.e. they are HDL and LDL, both are lipids). Besides, which function do you mean in the version 1.9.1 for 'multiviriate markers that do not measure the same variable'?

**Comment by CecileProust-Lima** [comment]
If you want to think of HDL and LDL as two measures of lipids, this is fine. However, I think HDL and LDL are in opposite directions so you might have to reverse one of them. 
The other function is mpjlcmm. you can have a look at the help. 
Best
Cécile
