### ISSUE TITLE
linear growth mixture model 

### ISSUE THREAD

**Issue by D4nielaD** [CecileProust-Lima/lcmm#48]
Dear all, 

I am very new to LCMM, so I want to apologize in advance if my questions are silly or this is not the right place to ask. 

My goal is to fit a (linear) growth mixture model, with the restriction that one class has a fixed mean growth of zero. 

I followed the recently published working paper by Wardenaar (2020) and unfortunately, I could not find answers to some questions and encountered some problems. 

I used the code as follows: 
gmm1 <- hlme(y~ time, subject = "ID", random=~1, ng = 1, data = data)
gmm2 <- gridsearch(rep = 100, maxiter = 10, minit = gmm1, hlme(y ~ time, subject = "ID", random=~1, ng = 2, data = data , mixture = ~ time, nwg=T))
gmm3 <- gridsearch(rep = 100, maxiter = 10, minit = gmm1, hlme(y ~ time, subject = "ID", random=~1, ng = 3, data = data, mixture = ~ time, nwg=T))
summarytable(gmm1, gmm2, gmm3)
Some remarks: 
-My data is on long format
-time is coded from 0 to 3 as I have 4 measurement points and assume a linear growth. 
-Y is the outcome variable measured on a 5-point Likert Scale via several items (there are missing values)
-ID is numeric ranging from 1 to 243 

1. I get the following error message: 
Error in hlme(ITL_STEM ~ Index1, subject = "ID", random = ~1, ng = 1, : 
  The argument subject must be numeric
My ID variable is numeric. I uploaded the data in R via SPSS. Is there anything else that needs special attention here? Sorry if this is a silly question, but I don't understand what I'm missing. 

2. How can I add an argument so that one class has a fixed growth of zero?

3. How can I get the information which subject is in which latent class? 

I’m sorry for taking your time. Any help is much appreciated. 
Very best
Daniela

**Comment by D4nielaD** [comment]
Hello again, 

suddenly after closing and opening the R-script the error message was actually gone :) Maybe I forgot to save it and that led to the error message? Anyway, the specified model is running fine. And I was also able to get the subject-specific information regarding class membership. 

I'm still struggling to add an argument so that the class has a fixed growth of zero.  So if anyone has any insights on this, it would be a great help. 

Sorry for my initial confusion. 

Very best

**Comment by CecileProust-Lima** [comment]
Dear Daniela, 

if you want to fix some parameters, you can do that with posfix argument when the initial vector of parameters is specified. Have a look at the paper in Journal of Statistical Software. 
In your case, you want to fix the parameters for the fixed effects of the first class. Note however that this solution requires to really understand the model, how the vector of parameters is specified, and you might find it not straightforward. 

Regarding the posterior classification, this is in pprob output argument. 

best
Cécile
