### ISSUE TITLE
How to evaluate the model accuracy for a specific outcome?

### ISSUE THREAD

**Issue by Aquariusquintini** [CecileProust-Lima/lcmm#5]
I am working on a model for patient deterioration based on repeated measures of vital signs. I am trying to discover trajectories in these vital signs that would indicate deterioration / risk of deterioration. One option is to use jointlcmm and use deterioration as time to event parameter. However, I would also be interested to leave the outcome (deterioration) out of the model to see if the classes/trajectories identified by the lcmm function are a good indication of deterioration. Or would that be a wrong use of the model?

**Comment by CecileProust-Lima** [comment]
This would not be wrong. I would say that the objective is different:
- the joint latent class model is useful to retrieve latent classes that are both explained by the repeated marker and the time-to-event. Their purpose is double: take into account the heterogeneity and the correlation between the time to event and repeated outcome. 
- if the objective is to summarize the trajectories of a repeated marker into latent classes (indeendently of the event) and then evaluate if this latent class structure predicts well the event, then the two step approach seems the right thing to do. However, you should be careful: subjects are classified into classes with uncertainty (posterior probas) and I think you should take into account this uncertainty in the second step (time to event model according to latent classes). 
I hope it will help. 
Cécile
