### ISSUE TITLE
Using LMER fixed effects in LCMM

### ISSUE THREAD

**Issue by nikarjunagi** [CecileProust-Lima/lcmm#51]
Hello Dr. Proust-Lima and lcmm-team,

I am building a LCMM model, and trying to understand how to select the covariates for the model. Is it feasible to first use LMER with Anova (add critical parameter, measure loglikelihood between models, retain if significant) to select the covariates, and then use the same covariates for constructing the LCMM model?

I would be very grateful for any advice or links on covariate selection. The examples that I find online do not go into detail on how the covariates are selected, but are focused on the definition and usage of the covariates. Thank you.

Regards,
Nikhil.

**Comment by CecileProust-Lima** [comment]
Covariates may intervene at different levels of the model: 
- in adjustment for the longitudinal (and or survival model in joint models). In that case, the heterogeneity is the residual heterogeneity after having taken into account covariates. In that case, you can use your traditional way of selecting covariate (model with LMER, DAG, etc).
- in the explanation of the latent class membership. In that case, the covariates will directly link with the latent class structure. The objective is different, and can be done either a priori with a few covariates (indeed, this is very demanding in terms of parameters) or in two steps: first no covariates, then explanation of the classes according to the covariates and finally rerun the model with the chosen covariates. 
But all these are proposals, there are many works and questions regarding the inclusion of covariates in latent class models in general. 
Best
Cécile
