### ISSUE TITLE
The plot issue with plotting all the data points

### ISSUE THREAD

**Issue by zdhjeff** [CecileProust-Lima/lcmm#53]
Dear Dr. Proust,

I was doing a project of estimating a latent class mixed model and found your R package lcmm quite handy and useful by using hlme function. Everything is fine except that when ploting both observed values and predicted values, the last data points are always missing in the plot. My dataset is quite simple and the time point is 0,1,2,3,4,5,9,17, and each time point has around 42 observations.

The R code:
plot(lcsleep, which="fit", var.time="time", marg=FALSE, shades = TRUE, break.times=c(-0.5,0.5,1.5,2.5,3.5,4.5,5.5,12.5,21.5))​

![image](https://user-images.githubusercontent.com/42054875/91605059-b3089500-e924-11ea-89c7-bc29649d04f3.png)

As shown in the plot above, I should have data points at time=17, but it did not show on the plot. I have tried many ways but still failed to do this..

By the way, May I ask how can I extract the values (such as the y values of the observed and the predicted) from the function? Thank you very much!

**Comment by zdhvincent** [comment]
Hello again,

I successfully extracted the data from the output and plot it. It seems the shape and pattern is quite different from the one plotted above. Not sure why, maybe I understood wrongly with the meaning of some parameters..

**Comment by VivianePhilipps** [comment]
Hello,

there was a mistake in the function's code, thank you for your feedback. For the last time interval, the observations at the maximum time measurement were not systematically included.
I corrected the function at the master branch.

All plotted values are returned by the function, so if you store the results you should be able to draw again the same plot.
For example : 

fit_lcsleep <- plot(lcsleep, which="fit", var.time="time", marg=FALSE, shades = TRUE, break.times=c(-0.5,0.5,1.5,2.5,3.5,4.5,5.5,12.5,21.5))​

matpoints(fit_lcsleep[,1], fit_lcsleep[,2:3]) # should overlap the points (=predictions)
matpoints(fit_lcsleep[,1], fit_lcsleep[,4:5], pch=3) # should overlap the lines (=observations)

**Comment by zdhjeff** [comment]
Thanks. I noticed that the observations data-points are not consistent with the one on the plot..Say I have 2 subgroups then the values of each group at a given time point should be the same with the mean values of the two groups at that time point.. I calculated them based on the classification. The values I got are quite different from the plot showed... Do you have any ideas about that?

**Comment by CecileProust-Lima** [comment]
Hi, 
I think the misunderstanding comes from the fact that in the plots, the observations are weighted by the posterior probabilities. So we do not expect the mean observation to be the same in the two groups since the posterior probabilities are not the same. 
I hope this answers your question. 
Best
Cécile
