### ISSUE TITLE
LRT for LCGA

### ISSUE THREAD

**Issue by rempegp** [CecileProust-Lima/lcmm#56]
Hello, thank you for this excellent package. I am conducting an LCGA and would like to test the differences in log-likelihood values between my various solutions. I am wondering if it would be acceptable to use a BLRT for this, and if so, do you have a recommended r package to run the test through? 
Thank you!

**Comment by CecileProust-Lima** [comment]
We have not implemented tjhe BLRT in our package, and don't plan do to so. We rely on various criteria such as BIC, entropy, ICL, classification table. 
Cécile

**Comment by rempegp** [comment]
Thank you!
