### ISSUE TITLE
Reference category question 

### ISSUE THREAD

**Issue by DLSmith8** [CecileProust-Lima/lcmm#57]
I cannot find, in any of the documentation how to change the reference category for exploring predictors of class membership (classmb ~...). The program always seems to choose the last category as the reference category, but can this be changed to explore predictors across different categories in the program?

**Comment by CecileProust-Lima** [comment]
Hi, 
indeed, we forgot to give this information but this can be done easily with permut. This function changes the order of the classes. See how it works below:

library(lcmm)

mhlme <- hlme(IST ~ I(age-age_init),random=~ I(age-age_init),subject="ID",data=paquid)

set.seed(1234)
mhlme2 <- hlme(IST ~ I(age-age_init),random=~ I(age-age_init),subject="ID",data=paquid,ng=2,mixture=~ I(age-age_init),classmb =~ CEP , B=random(mhlme))
summary(mhlme2)

mhlme2perm <- permut(mhlme2, order=c(2,1))
summary(mhlme2perm)

Cécile
