### ISSUE TITLE
Residual standard error and posterior class membership probability on new data based on fitted data MLEs

### ISSUE THREAD

**Issue by ujdang** [CecileProust-Lima/lcmm#59]
Dear Cécile,

Following up on our email communication, I am posting the questions my collaborator and I had here: 
1) Regarding the residual standard error outputted from a multlcmm function run; we are not sure if we are missing something simple or misinterpreting the output. We fit a two-component latent class linear mixed model with three outcomes simultaneously using the function multlcmm(). After fitting the model, we look into the estimation using summary.multlcmm(). The second last chunk of the output provides the residual standard error for the three outcomes. We also notice that, there are also marginal residuals and subject specific residuals stored in the output (object$pred). If we extract the subject specific residuals for each outcome using object$pred[,"resid_ss"], and compute the standard deviation of the three vectors of residuals. We were expecting to see the same result as what we see in the summary. However, it’s not. Could you show us how the standard error of residuals that’s included in the summary is calculated? Or if we are interpreting this wrong, it should not be the same as the standard error of the subject specific residual. If we misinterpret these two, could you point to the correct meaning of the standard error of residuals included in the summary?

2) Is it possible to estimate the matrix of posterior class-membership probabilities through the package for new data (use some training data, get some estimates from a model fit -> use on new test data like a discriminant analysis to get prob) but based off the MLEs found for the best fitting model.  As much of the code is written in fortran, we were unable to find the function that could do this for an multlcmm() model and source it in R?

Thank you,
Utkarsh Dang

**Comment by CecileProust-Lima** [comment]
Dear Utkarsh, 

thank you for your feedback. Here are responses to your two points: 

question 1. Indeed, the estimated residuals do not have the same variance as the MLE obtained from the model. The variance of the predicted residuals is more complex as involving the estimation of the random effects. This is part of the linear mixed model theory. Please refer to any book on mixed models for that. I can advertise the book of my team for instance :) : Commenges D, Jacqmin-Gadda H. Dynamical Biostatistical Models. CRC Press; 2015. Chapter 4 for the mixed models!
All the parameters provided in the summary are the MLEs of the model, i.e., the point estimates of all the parameters defined in the model equations and obtained by maximum likelihood. 

question 2. Yes, it is possible! You can compute the posterior probabilities for any new data by using a trick in the function call: 
With maxiter=0 option, you can do the posterior computations of the program (including the posterior probabilities) without estimating the parameters. It will be done at the parameter value provided as initial values in B.
So the steps are: 
1. fit your model on the training sample (object name mtrain for instance)
2. use the same call of the function to make external computation BUT (i) change the dataset for your external dataset (same variable names indeed);(ii) specify B=mtrain$best (this will use the MLE as initial values) and (iii) specify maxiter=0 (no likelihood maximization). 
By naming this new object mvalid, you should obtain the posterior probabilities for the external dataset in mvalid$pprob. 

I hope this helps,
Cécile

**Comment by ujdang** [comment]
Excellent, thanks so much for the follow-up. Much appreciated.
