### ISSUE TITLE
The argument subject must be numeric

### ISSUE THREAD

**Issue by mhowland621** [CecileProust-Lima/lcmm#60]
I am receiving the following error message:

Error in hlme(epdssum ~ ppmonths, subject = "subid", ng = 1, data = blues.long) : 
  The argument subject must be numeric

The "subid" variable is specified as numeric in my dataframe, so I am not sure what is happening. Any advice would be appreciated. Thank you!

**Comment by mhowland621** [comment]
I have also tried specifying the subid variable as an integer, and I get the same error message

**Comment by CecileProust-Lima** [comment]
Dear Mariann, 
indeed subject variable must be numeric in all the functions. I reproduced the error by defining a character variable for ID. But when I respecified my variable into numeric, then the problem disappeared... see the bold part below.

> dat <- data.frame(ID=c("AB","AB","AB",
+                        "CD","CD","CD",
+                        "EF","EF","EF",
+                        "GH","GH","GH"),time=rep(0:2,length=3),Y=rnorm(12))
> head(dat)
  ID time          Y
1 AB    0  1.4245811
2 AB    1 -2.4854626
3 AB    2  1.1783060
4 CD    0  1.2751130
5 CD    1 -0.4816777
6 CD    2  1.0908144
> is.numeric(dat$ID)
[1] FALSE
> 
> library(lcmm)
**> m <- hlme(Y ~ time,subject="ID",data=dat)
Be patient, hlme is running ... 
Error in hlme(Y ~ time, subject = "ID", data = dat) : 
  The argument subject must be numeric
> 
> dat$IDnum <- as.numeric(dat$ID)
> is.numeric(dat$IDnum)
[1] TRUE
> m1 <- hlme(Y ~ time,subject="IDnum",data=dat)
Be patient, hlme is running ... 
The program took 0.01 seconds**

**Comment by mhowland621** [comment]
Dear Dr. Proust,

Thank you for your reply! When I read in my .csv file, my subject ID variable is already defined as numeric, and I am getting that error message (hence my email to you). I assume something else is wrong with my data or maybe my R, so I’ll have to keep troubleshooting. If you have any other ideas, I would appreciate it!

Best,

Mariann

**Comment by CecileProust-Lima** [comment]
What is.numeric() gives? You will see in my example above that is.numeric(dat$IDnum) is TRUE but is.numeric(dat$ID) is FALSE.

**Comment by mhowland621** [comment]
It returns a list of all of the subject IDs. However, I just re-downloaded
my R and Rstudio and updated all of my packages, and I am no longer
receiving the error message, so it must have been something with my R or
packages. My apologies for bothering you!

Best,

Mariann

Mariann Howland (she/her/hers) <https://www.mypronouns.org/>
Doctoral Student | Developmental Psychopathology and Clinical Science
National Science Foundation Graduate Research Fellow
Institute of Child Development | University of Minnesota

*The University of Minnesota stands on Miní Sóta Makhóčhe, the homelands of
the Dakhóta Oyáte. **I acknowledge the Dakhóta Oyate’s sovereignty and
their rightful ownership of this land, their place of origin. **It is their
continued displacement that allows the university to remain today. *

**Comment by iago-pssjd** [comment]
Hi!
I have also got this issue. I detected that if `id` is a numeric variable, then `class(dat[,"id"])` is numeric if `dat` is strictly a `data.frame`, but if it is a tibble, then the subsetting gives another tibble, so
```r
class(dat[,"id"])
[1] "tbl_df"     "tbl"        "data.frame"
```
I believe this would be solved if in the line 30 of `lcmm/R/Contlcmm.R` you used `data[[subject]]` instead of `data[,subject]`.

**Comment by VivianePhilipps** [comment]
Hi,

thank you for your  comment. 
I updated the code according to you suggestion. My first tests seem to be successful, so I hope this will fix your issues.

Thanks!

Viviane
