### ISSUE TITLE
Interactions Between Class Membership Covariates

### ISSUE THREAD

**Issue by rempegp** [CecileProust-Lima/lcmm#61]
Hello, I am attempting to include an interaction between two of my class membership covariates and just want to double check that I am coding it correctly. I did not see an example of this in your paper or in the package documentation but let me know if I missed it.

I have four covariates following the classmb argument (classmb=~X1+X2+X3+X4). X1 is a binary variable, and X2 is continuous. I have been including the interaction between X1 and X2 as follows: classmb =~X1+X2+X3+X4+X1*X2. By doing this the output details what I assume is the interaction between X1 and X2 for each class (X1:X2.....). Is this the correct way to specify interactions between class membership covariates? 
Thank you!

**Comment by VivianePhilipps** [comment]
Hello,

yes, that's it. You can indeed include interactions between variables X1 and X2 in the class membership model, or in any other submodel, with X1*X2.

Viviane
