### ISSUE TITLE
lcmm notation clarifications

### ISSUE THREAD

**Issue by jschoeneberger** [CecileProust-Lima/lcmm#62]
I’m working my way through the lcmm article in the Journal of Statistical Software (https://www.jstatsoft.org/article/view/v078i02) and I had a question I’m hoping you might help me with. I’m not a statistician, but am an applied researcher and am generally familiar with mixed models. In formula (1) in the article, I had some questions about the notation:
 
•	What is the L subscript of the X term signify?
•	What is the T superscript over the tij term signify?
•	Can you explain to me what the wi term represents?  I’ve not seen this term represented in mixed model formulations in the past. In the subsequent paragraphs below formula (1) it is referred to as a random (stochastic) process, but I’m not sure what it is associated with…does it somehow represent the association between time points?

Thanks for sharing this site with me...i've found some other threads that will be useful as well

**Comment by CecileProust-Lima** [comment]
Dear Jason, 
I think this is this equation: 
![LMM](https://user-images.githubusercontent.com/37074860/99824301-d757c480-2b55-11eb-8611-e3bb661cfa85.png)

This is the classical equation of a linear mixed model: 
• L subscript of the X term is just a subscript to say that this is the covariate vector for the longitudinal (L for longitudinal) model as other models with other covariate vectors or matrices are introduced later.  
• T superscript is the mathematical symbol for transpose. It is necessary for the matrix product to be correct
• wi term is an autocorrelated Gaussian process that may add a structure of correlation on the repeated measures of an individual (following a Brownian or an autoregressive process). This is optional. By default, there is no such autocorrelated process in all the lcmm functions. 
I hope this helps. There are also some vignettes if necessary on the cran. 
Cécile

**Comment by jschoeneberger** [comment]
Hi Cécile,

Thanks for the explanation...this is very helpful.  Will be working my way through the vignettes in turn.
