### ISSUE TITLE
Set reference class within classmb 

### ISSUE THREAD

**Issue by ghost** [CecileProust-Lima/lcmm#63]
Dear all, 

I have a question regarding the classmb option within the lcmm package. The reference class is automatically the last class, however, is it possible to change within the model which class will be used as reference class? 

Thank you in advance. 

Best, 
Sara

**Comment by VivianePhilipps** [comment]
Hello,

once the model is estimated, you can reorder the latent classes using the permut function. In that way, you can choose the class you want to be the reference in the class membership model.
Please refer to the vignette "Usual problems" to get an example.

Thanks

Viviane
