### ISSUE TITLE
hlme function random effect

### ISSUE THREAD

**Issue by Behaapy-all** [CecileProust-Lima/lcmm#64]
Dear all,

I would like to ask a quick question about 'hlme'.

Based on my understanding from paper, the' hlme' function is able to handle class-specific fixed effects and the distribution of the random effects. (Page 6, Equation (7) )
This means that at each identified class, we have different coefficients and distribution of the random effect.

However, from the following R code where the number of groups is fixed 2 (This is exactly the same example on the paper), I can see the class-specific fixed effect, but I could 'NOT' find class-specific random-effects.

Could anyone please explain why it is? If I misunderstood, I was wondering if you are able to briefly explain the right understanding of the model.

Hope you stay safe and healthy.

*************** R CODE from your paper ***********************
library(lcmm)
library(NormPsy)
paquid$normMMSE <-normMMSE(paquid$MMSE)
paquid$age65 <- (paquid$age - 65)/10

m1 <- hlme(normMMSE ~ poly(age65, degree = 1, raw = TRUE) + CEP,
            random = ~ poly(age65, degree = 1, raw = TRUE), subject = "ID", ng = 1,
            data = paquid)

m2 <- hlme(normMMSE ~ poly(age65, degree = 1, raw = TRUE) + CEP,
           mixture = ~ poly(age65, degree = 1, raw = TRUE),
           random = ~ poly(age65, degree = 1, raw = TRUE), subject = "ID", ng = 2,
           data = paquid, B = m1)
summary(m2)
*********************************************************************

**Comment by VivianePhilipps** [comment]
Hi,

the model you mention supposes a common distribution of the random effects over the latent classes. You can specify a class specific variance by adding the option nwg=TRUE.

In the same example :
m2 <- hlme(normMMSE ~ poly(age65, degree = 1, raw = TRUE) + CEP,
 mixture = ~ poly(age65, degree = 1, raw = TRUE),
 random = ~ poly(age65, degree = 1, raw = TRUE), subject = "ID", ng = 2,
 data = paquid, B = m1, nwg=TRUE)
summary(m2)

the variance matrix you get (with coefficients 126.44, -30.88, 30.91)  corresponds to the second class. And a proportional coefficients is estimated (value 1.55 is this example) to get the random effects variance of the first class.

Best,

Viviane

**Comment by Behaapy-all** [comment]
Thank you very much for quick response!

Then, one further question is that the random effects of the first class is 1.55 * variance-covariance matrix of the random effects?  Is the number 1.55 multiplied to all elements of the variance-covariance matrix of the second class or only for diagonal elements?

Thanks in advance!

**Comment by CecileProust-Lima** [comment]
To complement the response of Viviane: 
In a latent class mixed model, one can see the random effects as class-specific but actually, it's the distribution of the random effects which is class-specific, ie the mean and possibly the variance (when nwg=T) of normal distribution. In lcmm package implementation, we chose to let the user implement the mean of the random effects in the mixture=~ argument for more flexibility. The variance of the random effects is either the same (nwg=F) or proportional from one class to the other (nwg=T). 
This is for the implementation of the model. Then, you can obtain predictions of the random-effect in each latent class and marginally to the latent classes. You have that in the predRE object. 
I hope this helps you.

**Comment by VivianePhilipps** [comment]
All elements are multiplied, and to ensure positivity we square the proportionality coefficient so :
 varianceClass1 = propCoefClass1^2 * variance = 1.55^2* matrix(c(126.44, -30.88, -30.88, 30.91),2,2)

**Comment by Behaapy-all** [comment]
Thank you all very much and provide this package to the public :)
