### ISSUE TITLE
Vignette Plot Legend

### ISSUE THREAD

**Issue by jschoeneberger** [CecileProust-Lima/lcmm#65]
Hi LCMM:

I was working my way through the "hlme function" vignette, and got a bit confused by the first plot of predicted trajectories for normMMSE.  I realized that the legend line colors didn't align with the classes (at least i believe that's what is going on).  I played around with the legend code, in particular the 'col' line that specifies the colors, to include a blank for the color appearing next to 'class' and then the same color to appear by line-type:
`
plot(pred0, col=c("red","navy"), lty=1,lwd=5,ylab="normMMSE",legend=NULL, 
     main="Predicted trajectories for normMMSE ",ylim=c(0,100))
plot(pred1, col=c("red","navy"), lty=2,lwd=3,legend=NULL,add=TRUE)
legend(x="topright",
       legend=c("class1 :","CEP-","CEP+","class2:","CEP-","CEP+"), 
       col=c(" ","red","red"," ","navy","navy"), lwd=2, lty=c(0,1,2,0,1,2), ncol=2, bty="n", cex = 0.7)
`

If, by chance, there was a three-class solution,  it would look like this:
`
![2-class plot](https://user-images.githubusercontent.com/34711045/106018532-9d43fb00-608f-11eb-92f6-b8e251da8175.png)

plot(pred0, col=c("red","navy","green"), lty=1,lwd=5,ylab="normMMSE",legend=NULL, 
     main="Predicted trajectories for normMMSE ",ylim=c(0,100))
plot(pred1, col=c("red","navy","green"), lty=2,lwd=3,legend=NULL,add=TRUE)
legend(x="topright",
       legend=c("class1 :","CEP-","CEP+","class2:","CEP-","CEP+","class3:","CEP-","CEP+"), 
       col=c(" ","red","red"," ","navy","navy"," ","green","green"), lwd=2, lty=c(0,1,2,0,1,2,0,1,2), ncol=3, bty="n", cex = 0.7)`

This helped me to review the graphs more easily.  HTH --Jason

**Comment by VivianePhilipps** [comment]
Hi, 

there is indeed an inversion, we missed that error.
Thank you for your correction!

Viviane

**Comment by jschoeneberger** [comment]
You're welcome!  A small thing really, but figure it was worth sharing!
