### ISSUE TITLE
Plot when using ns() in hlme

### ISSUE THREAD

**Issue by ZuolinLu** [CecileProust-Lima/lcmm#67]
Dear all,

I am doing a analysis to identifiy the potential classes of BMI with age. Here is my code:

m_bmi <- hlme(bmi ~ ns(age,2), mixture = ns(age,2)
                      random = ~ 1, subject = "id", idiag = TRUE, data  = long_bmi, ng = 3) 

The model converged perfectly. However when I plotted the predictive trajectories, I found that the plots didn't change whatever the range of age I chosen. For example:

newdata1 <-  data.frame(age=seq(60, 80, length=1000))
plot(predictY(m_male_bmi.10, newdata1, var.time = "age"), lwd = 2, main = "newdata1")

newdata2 <-  data.frame(age=seq(70, 100, length=1000))
plot(predictY(m_male_bmi.10, newdata2, var.time = "age"), lwd = 2, main = "newdata2")

![Rplot03](https://user-images.githubusercontent.com/80062330/110008927-99556980-7d1c-11eb-8305-886093285059.png)

In the plot above, I would say that they are actually same. That is very werid! Did I make any mistake? 

Besides, I didn't have such a problem when I used polynominals for nonlinearity. Does this suggest that we shouldn't use natural spline in hlme? 

Looking forward to your reply!
Thanks in advance!

Best, Zuolin

**Comment by VivianePhilipps** [comment]
Dear Zuolin,

this is a recurrent problem with splines defined with the df option. We recommend using the knots and Boundary.knots arguments instead.
Please refer to my answer in issue #28  for an example and let me know if you still have any trouble.

Thanks,

Viviane

**Comment by ZuolinLu** [comment]
Hi Viviane,

Thank you for your swift reply and your suggestions!

After using the knots and Boundary.knots arguments, the plots worked perfectly!

Nice weekend and thanks again!

Best, Zuolin
