### ISSUE TITLE
hlme function in cross sectional context

### ISSUE THREAD

**Issue by Ca-ca-br** [CecileProust-Lima/lcmm#69]
Hello,
 I am currently analyzing data from an experiment where I try to predict aesthetic ratings from the acoustic features of sung melodies. So the data aren’t longitudinal like in studies of disease progression, but I do have repeated measurements from each participant: the experiment was just one testing session where participants rated how much they liked excerpts of sung melodies on a 9-point scale. My basic analysis was fitting a linear mixed effects model (lme4 package in R) with acoustic features (pitch accuracy, vibrato extent, vibrato rate, tempo, signal-to-noise ratio) as fixed effects and subjects and items (melody stimuli) as random effects with random intercepts. Turns out that the acoustic features could hardly predict a small part of the variance of ratings (marginal 𝑅2=0.015, conditional 𝑅2=0.461, MuMIn package in R). I was surprised by this since when I look at mean ratings, I do find moderate correlations with some of the acoustic features, and it seems like there might be different “profiles” of participants in their relationship with the acoustic predictors.
So after looking for some kind of clusterwise-regression that could account for random effects I found your package. I read in the package documentation that the functions apply to longitudinal markers, but can also be used in cross sectional context. I tried my best, but having no background in Mathematics or Statistics and as a novice even to linear mixed models, I am not able to grasp if the computations behind a latent class mixed model for Gaussian longitudinal outcomes are really conceptually wrong for my kind of data (or if they are not ideal but OK to use). 
The hlme function seems to work well to model my data – with the best solution leading to 4 latent classes with different patterns of  relationship between ratings and different acoustic predictors, and a higher proportion of variance explained than with just the one linear mixed model for all 330 participants together. But is it fundamentally wrong of me to be using it? 
It would be incredibly helpful if you could give me some feedback on this matter. Thank you in advance!
Best,
Camila

**Comment by CecileProust-Lima** [comment]
Dear Camila, 
 I am not sure I really understood your data design. lcmm package handles 2-level data by using random effects (in argument random=~ ) on the statistical unit (specified in subject=). That could be grouped data or longitudinal data. IThe package also handles 1-level data by not including random effects using random=~-1. 
I hope this will help you.
Best
Cécile

**Comment by Ca-ca-br** [comment]
Dear Cécile,
Thank you for your answer!
Maybe  my question is a bit naïve; I was unsure with the term 'longitudinal model' in the output of the analysis with hlme, so I just wanted to make sure it's OK to use the hlme function to model my type of (grouped) data with many measures from each subject, but collected in just one testing session.

If my basic model with lmer has a syntax like:

basic_model <- lmer(rating ~ acoustic_predictor1 + acoustic_predictor2 + acoustic_predictor3 + acoustic_predictor4+ acoustic_predictor5+ (1|participant), df)

And I suspect there are different “profiles” of participants in the way they base their responses on different acoustic predictors, than is it correct to further analyze the data with the hlme function as in :

Base model with one class:

model_1cl <- hlme(rating ~ acoustic_predictor1 + acoustic_predictor2 + acoustic_predictor3 + acoustic_predictor4+ acoustic_predictor5, 
random = ~ participant, subject='participant’, data = df)

Model with 2 latent classes:

model_2cl <- hlme(rating ~ acoustic_predictor1 + acoustic_predictor2 + acoustic_predictor3 + acoustic_predictor4+ acoustic_predictor5, 
mixture=~ acoustic_predictor1 + acoustic_predictor2 + acoustic_predictor3 + acoustic_predictor4+ acoustic_predictor5,  
random = ~ participant, subject='participant’, 
ng = 2, data = df)

?

And a secondary question, if I may: did I understand correctly that I could not include a second term in the random effects (item stimuli, in my case)? It seems if I try it, computations will go on forever… would that not be supported by the function?

Thank you again!
Best, Camila

**Comment by CecileProust-Lima** [comment]
Hi Camila, 
indeed, we are so used to apply the method for longitudinal data that we indicated that in the output. But the method also works with grouped cross-sectional data. 
However, be careful and check the companion paper and/or the vignettes cran: random argument should indicate 1 if you want to replicate the model with lmer, not the statistical grouping unit. So you should have : random = ~ 1
I also confirm that you can only specify one grouping unit with argument subject. And then, you can have several random-effects on this grouping unit. Please also refer to the companion paper and vignettes for that. 
Best
Cécile

**Comment by Ca-ca-br** [comment]
Dear Cécile, this was really helpful, thank you so much!
Best, Camila
