### ISSUE TITLE
Unable to specify B vector in hlme using certain sampling functions

### ISSUE THREAD

**Issue by jonathanishhorowicz** [CecileProust-Lima/lcmm#7]
In the following code, specifying B using certain commands throws the error ```The model specified in B should be of class hlme```.  The B vectors all have the same length (6) and are of class ```numeric```

It is particularly strange as `rnorm(6)` and `rnorm(6,0,1)` have the same output. Not sure what to do about this.

Thank you in advance!

```r
library(lcmm)

#
# Create data
#
eps <- 1.0

t <- seq(1.0, 10.0, 1.0)
y1 <- 2*t + 3 + rnorm(length(t), 0.0, eps)
y2 <- -t + 1 + rnorm(length(t), 0.0, eps)

df <- data.frame("t" = t,
                 "y" = c(y1, y2),
                 "patient" = c(rep("1", length(t)), rep("2", length(t))))

#
# Train a gmm without specifying initial parameters B
#
gmm.1 <- hlme(fixed = y~t, mixture=~-1+t, random=~1,
            data = df,
            subject = "patient",
            ng = 2)

#
# For the same model, can specify B using rep
#
gmm.2 <- hlme(fixed = y~t, mixture=~-1+t, random=~1,
                       data = df,
                       subject = "patient",
                       B = rep(1.0, 6),
                       ng = 2)

#
# Can specify B using rnorm if mean and variance are specified
#
gmm.3 <- hlme(fixed = y~t, mixture=~-1+t, random=~1,
              data = df,
              subject = "patient",
              B = rnorm(6, 0, 1),
              ng = 2)

#
# Can't specify B using rnorm if mean and variance are not specified.
# Throws error "The model specified in B should be of class hlme"
#
gmm.4 <- hlme(fixed = y~t, mixture=~-1+t, random=~1,
              data = df,
              subject = "patient",
              B = rnorm(6),
              ng = 2)


#
# Can't specify B using runif
# Throws error "The model specified in B should be of class hlme"
#
gmm.5 <- hlme(fixed = y~t, mixture=~-1+t, random=~1,
              data = df,
              subject = "patient",
              B = runif(6),
              ng = 2)
```

Sessioninfo:

> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8      
 [8] LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lcmm_1.7.8      survival_2.41-3

loaded via a namespace (and not attached):
[1] compiler_3.4.1  Matrix_1.2-11   tools_3.4.1     splines_3.4.1   grid_3.4.1      lattice_0.20-35

**Comment by CecileProust-Lima** [comment]
Thank you for your feedback. You are right, we have not handled this type of specification. B argument is not supposed to include any function. 
If you want to directly consider random initial values (without using our function random(m)), you should 
do it with two lines: 

binit <- rnorm(6, 0, 1)
gmm.3 <- hlme(fixed = y~t, mixture=~-1+t, random=~1,
              data = df,
              subject = "patient",
              B = binit,
              ng = 2)

Cécile
