### ISSUE TITLE
predictY.hlme fails if data variable in original call is named `x` and returndata=FALSE

### ISSUE THREAD

**Issue by orting** [CecileProust-Lima/lcmm#71]
Small example

    library(lcmm)
    
    mydata  <- data.frame(y=rnorm(1000, mean=100), id=rep(1:100,10), day=rep(1:10,each=100))
    mydata$y <- mydata$y + mydata$day
    x <- mydata
    
    models  <- list(m1=hlme(fixed=y~day, data=mydata, subject='id', returndata=T, verbose=F),
                    m2=hlme(fixed=y~day, data=mydata, subject='id', returndata=F, verbose=F),
                    m3=hlme(fixed=y~day, data=x,      subject='id', returndata=T, verbose=F),
                    m4=hlme(fixed=y~day, data=x,      subject='id', returndata=F, verbose=F)) # fails predictY
    
    for (m in names(models)) {
        tryCatch(predictY(models[[m]], x), error=function(e) {print(m); print(e)})
    }

I believe the issue comes from https://github.com/CecileProust-Lima/lcmm/blob/2792a3fae4ba38a78f4010d1964a9fbb15a9daf6/R/predictY.hlme.R#L57-L64

I suggest to store the relevant info in the fitted model instead of relying on being able to pull it from the data used in the fit.

**Comment by VivianePhilipps** [comment]
Hello,

thank you for your feedback.
I just made some changes to stored information about the data in the hlme object. This will avoid recovering the original data in the predictY function. It seems to fix the bug you pointed out.

Changes are done in commit f2c7d5b.
This only concerns hlme models and the corresponding predictY function. If satisfactory, it will also be applied to other models (lcmm, Jointlcmm, etc) and other functions that retrieve the fitting data (predictL, VarExpl, etc.)

Best,

Viviane
