### ISSUE TITLE
subject must be numeric

### ISSUE THREAD

**Issue by markprince77** [CecileProust-Lima/lcmm#72]
I keep getting the following error: 
Error in hlme(value ~ tpt, subject = "subnum", random = ~1, ng = 1, data = sim.gmm.long) : 
  The argument subject must be numeric

the column is numeric, I have explicitly made it numeric and not int, when i look at it using str it say num. 

Any suggestions?

**Comment by CecileProust-Lima** [comment]
Hi, 
there are other closed issues related to this problem. You might have a look. Did you check that your data were stored in a data.frame? This is a possible cause of trouble.
Cécile

**Comment by markprince77** [comment]
I appreciate you getting back to me. My data are stored in a data frame and
subject is definitely numeric. I'll keep looking at the closed issues to
see if there is anything else I might be overlooking.

thanks,
Mark

--
Mark A. Prince, PhD
Assistant Professor
Licensed Psychologist, Colorado PSY.0004925
Associate Director of Addiction Counseling
Department of Psychology
Colorado State University

**Comment by ArianeBodem** [comment]
Hey Mark, 
i have the same Error in hlme and the column is also numeric. Have you found a solution to the problem? 
best wishes

**Comment by markprince77** [comment]
unfortunately, i have not. I tried a few things that didn't work and I gave
up.
--
Mark A. Prince, PhD
Assistant Professor
Licensed Psychologist, Colorado PSY.0004925
Associate Director of Addiction Counseling
Department of Psychology
Colorado State University

**Comment by CecileProust-Lima** [comment]
Hi, 
sorry to hear that the problem remains. We were not able to replicate this type of trouble. Could you provide a very small example that we could explore? In addition, which version of lcmm and of R are you using? 
Cécile

**Comment by CecileProust-Lima** [comment]
Here is an example that worked fine for me: 

library(lcmm)
# hlme with numeric ID
m <- hlme(IST ~ I(age-age_init),random=~ I(age-age_init),subject="ID",data=paquid)
## OK it works fine

# hlme with an ID character
paquid$IDchar <- paste("id",2000+paquid$ID,sep="")
is.numeric(paquid$IDchar)
typeof(paquid$IDchar)

m1 <- hlme(IST ~ I(age-age_init),random=~ I(age-age_init),subject="IDchar",data=paquid)
## OK it does not work

# hlme with and ID recreated from the character ID
paquid$NUM <- match(paquid$IDchar, unique(paquid$IDchar))
is.numeric(paquid$NUM)
typeof(paquid$NUM)
m2 <- hlme(IST ~ I(age-age_init),random=~ I(age-age_init),subject="NUM",data=paquid)
## OK it works fine

**Comment by markprince77** [comment]
interesting. Thank you! I'll give it a try.
--
Mark A. Prince, PhD
Assistant Professor
Licensed Psychologist, Colorado PSY.0004925
Associate Director of Addiction Counseling
Department of Psychology
Colorado State University

**Comment by jrmie** [comment]
I think this problem has been previously solved (#60 ) but the fix is not available on CRAN, while waiting for an update of the package on CRAN you can try to install the development version from Github (you need `devtools` package)

`devtools::install_github("CecileProust-Lima/lcmm")`

**Comment by CecileProust-Lima** [comment]
The fix mentioned in issue #60 is only for tibbles. No bug was identified so far with numeric IDs in dataframes. 
Cécile

**Comment by markprince77** [comment]
ok, the development version solved it for me. Sorry it took me a bit to
cycle back to it. Thank you for the help and support.
--
Mark A. Prince, PhD
Assistant Professor
Licensed Psychologist, Colorado PSY.0004925
Associate Director of Addiction Counseling
Department of Psychology
Colorado State University

**Comment by hannahalveshagy** [comment]
Hi - I am having the same issue. it sounds like downloading the development version will fix this?

**Comment by CecileProust-Lima** [comment]
Really sorry for this. We have never encountered this issue in all our tests (on different operating systems, different R versions), and because of that, we have not been able to identify what could be causing this problem.

**Comment by hannahalveshagy** [comment]
Hello,

I was able to fix this with the following line of code:

#from tibble to data.frame
long <- as.data.frame(long)

Thanks again!

**Comment by CecileProust-Lima** [comment]
Great, thanks for the feedback! If you had a tibble then the new version which will be on cran in a few weeks should solve the problem. 
Cécile
