### ISSUE TITLE
Doubt about random effects and problem with its variance-covariance matrix

### ISSUE THREAD

**Issue by MatheusMancini** [CecileProust-Lima/lcmm#76]
Dear Ms. Proust-Lima, hope you and yours are well.

I would like to ask you two questions about the lcmm package:

Question 1. I'm a little confused about the use of the 'random' argument. After reading the CRAN of the package and some closed issues here in github, that's what I understood about it:

. If you don't even insert the 'random' argument in your model, or if you insert 'random=~-1', you're saying that there is no random effect at all;
. If you insert 'random=~1', you're saying that only the intercept is a random factor. This specifies to the model that the observations of each specific subject are correlated;

Is that right? If no, could you please explain to me how to use the random argument when you don't have a random effect? For example, in the code below, if I don't have a random factor, should I include 'random=~1' or should I keep it as it is? (If there are any other errors, please tell me).

#Null model:
m1 <-lcmm(fo~mata3,subject='id_ok',ng=1,data=dados, link="linear")
#2 groups:
m2 <-lcmm(fo~mata3,subject='id_ok',mixture=~mata3,ng=2,B=m1,data=dados, link="linear")

Question 2. I'm trying to run a model in lcmm package with a random factor (please see the code below). However, when analyzing the output, I noticed that the variance-covariance matrix of the random-effects has only zeros. Could this be right? Or am I doing something wrong? Thank you very much in advance!!

> m2 <-lcmm(fo~conect3,subject='id_ok',mixture=~conect3,random=~mata3,ng=2,B=m1,data=dados,link="linear")
Be patient, lcmm is running ... 
The program took 0.25 seconds 
> summary(m2)
General latent class mixed model 
     fitted by maximum likelihood method 
 
lcmm(fixed = fo ~ conect3, mixture = ~conect3, random = ~mata3, 
    subject = "id_ok", ng = 2, link = "linear", data = dados)
 
Statistical Model: 
     Dataset: dados 
     Number of subjects: 4 
     Number of observations: 34 
     Number of latent classes: 2 
     Number of parameters: 9  
     Link function: linear  
 
Iteration process: 
     Convergence criteria satisfied 
     Number of iterations:  21 
     Convergence criteria: parameters= 2.2e-07 
                         : likelihood= 2.3e-09 
                         : second derivatives= 1.1e-12 
 
Goodness-of-fit statistics: 
     maximum log-likelihood: -141.56  
     AIC: 301.12  
     BIC: 295.59  
 
     Discrete posterior log-likelihood: -126.21  
     Discrete AIC: 270.43  
 
     Mean discrete AIC per subject: 33.8037  
     Mean UACV per subject: 33.7471  
     Mean discrete LL per subject: -31.5537  
 
Maximum Likelihood Estimates: 
 
Fixed effects in the class-membership model:
(the class of reference is the last class) 

                     coef      Se   Wald p-value
intercept class1 -1.09856 1.15468 -0.951 0.34140

Fixed effects in the longitudinal model:

                                     coef      Se   Wald p-value
intercept class1 (not estimated)        0                       
intercept class2                 -1.06101 0.65401 -1.622 0.10474
conect3 class1                    0.00316 0.00128  2.474 0.01335
conect3 class2                    0.00111 0.00088  1.267 0.20498

Variance-covariance matrix of the random-effects:
          intercept mata3
intercept         0      
mata3             0     0

Residual standard error (not estimated) = 1

Parameters of the link function:

                         coef      Se   Wald p-value
Linear 1 (intercept) 16.78902 7.55814  2.221 0.02633
Linear 2 (std err)   14.56199 1.76668  8.243 0.00000

**Comment by MatheusMancini** [comment]
Hi Viviane,

Thank you very much for your reply! 

If you don't mind, I would like to ask one more question: in that cases when we don't have enough subjects to estimate the variance/covariance of the random effects, are these models (and their results) reliable? Can we report them?

Thank you very much!
Matheus.

**Comment by CecileProust-Lima** [comment]
If the model estimated with random effects has a log-likelihood that is similar to the one without the random effects, then I don't see a problem in interpreting the model without random effects. 
Cécile
