### ISSUE TITLE
Positive log-likelihood

### ISSUE THREAD

**Issue by soumyasahu** [CecileProust-Lima/lcmm#77]
Dear lcmm-team,

First of all thanks a lot for your hard work behind this very helpful package. I have used this package mainly for joint latent class modeling. In our data, we have 42 longitudinal variables. We decided to perform some variable screening based on marginal analysis, i.e. using one longitudinal variable at a time. While doing this, for some longitudinal variable, I have encountered a very strange problem-- positive log-likelihood in spite of convergence of the algorithm. I am just pasting the result from one of them:

Joint latent class model for quantitative outcome and competing risks 
     fitted by maximum likelihood method 
 
Jointlcmm(fixed = as.formula(paste(x, "~ Age + time + Gender + Smoking")), 
    mixture = ~Age + time, random = ~poly(time, degree = 2, raw = TRUE), 
    subject = "Patient number", classmb = ~Age + Gender + 
        Smoking + rs61941274n, ng = 2, nwg = T, survival = Surv(surv_time, 
        converted) ~ mixture(Age) + mixture(Gender) + mixture(Smoking) + 
        mixture(rs61941274n), data = data_used1)
 
Statistical Model: 
     Dataset: data_used1 
     Number of subjects: 562 
     Number of observations: 11789 
     Number of latent classes: 2 
     Number of parameters: 33  
     Event 1 : 
        Number of events: 126
        Class-specific hazards and 
        Weibull baseline risk function 
 
Iteration process: 
     **Convergence criteria satisfied** 
     Number of iterations:  53 
     Convergence criteria: parameters= 8.8e-05 
                         : likelihood= 4.5e-06 
                         : second derivatives= 1.4e-05 
 
Goodness-of-fit statistics: 
     **maximum log-likelihood: 9864.78**  
     AIC: -19663.56  
     BIC: -19520.62 

One more question I like to add here. While doing each variable at a time, we are using the log-rank test among the marginal survival times of the assigned classes to check the impact of the longitudinal variable over survival. Do you recommend any better way to check this?

Thanks a lot,
Soumya.

**Comment by CecileProust-Lima** [comment]
Dear Soumya, 
although unusual, positive log-likelihood happen sometimes ... It depends on the size of Y. See for instance below: I use the exact same model and data but I rescale Y into Y/100 and the log-likelihood becomes positive. The parameters though are similar (transformed by the 1/100 scaling):

m <- hlme(fixed = IST ~ I(age-age_init)*CEP,random=~I(age-age_init),subject="ID",
          data=paquid)
summary(m)
paquid$IST100 <- paquid$IST/100
m100 <- hlme(fixed = IST100 ~ I(age-age_init)*CEP,random=~I(age-age_init),subject="ID",
            data=paquid)
summary(m100)

Sorry, I did not understand exactly what you meant to do with the log-rank. 
Cécile

**Comment by soumyasahu** [comment]
Dear Dr. Cécile,

Thanks a lot. Changing the scale of Y works also for my data just like magic.

Let me explain the other question. To find out if the longitudinal variable used in Jlcmm has any effect on survival, we are using a log-rank test between the survival times of two or more groups found by the fitted model. We are using the observed survival or censored times in this case. My question is if there any better way to check this.

I want to add two more questions--  (1) while using plot with 'which = survival' the fitted survival distributions of the groups are plotted, now if I go back and plot the Kaplan-Meier curve for the observed survival or censored time for the groups, they look much different to the former plots. Can you kindly explain why this is happening?
(2) Can jlcmm be used for more than one longitudinal variable using a similar model code as multlcmm?

Thanks again,
Soumya.

**Comment by CecileProust-Lima** [comment]
Hi Soumya, 
What is given in plot (which=surv) is the baseline cumulative hazard or the baseline survival, that is what happens for all the covariates fixed at 0. If you want to obtain the "real" estimates and curves for covariates that are different from zero, you have two options: 
- you compute them by using the classical formulation CumRisk(g) = CumRisk0(g)* exp(X*beta(g)) where beta(g) is the vector of parameters associated with the covariates X (in class g if you have class-specific effects) and X the value of these covariates, and CumRisk0(g) is obtained from the output of the model for each class g. The survival (in the absence of competing risk) is derived as: Surv(g)= exp(-Cumrisk(g)). 
-  you can use the cuminc function which provides the cumulative incidence, that is the probability that the event happens before a certain time. In the absence of competing risks, this would give 1-Surv. You could use this function for each individual based on his/her own covariates. 

Once this is done, you have an estimate in each latent class. If you want an overall estimate, you can simply compute a mean individual specific survival curve (or cumRisk) as the weighted mean over the classes of the survival/cumrisk/cuminc for the subject where the weights are given by his/her posterior probabilities. 

To go back to your first question, one interesting thing to do is to account for the uncertainty (provided by the posterior probabilities). And what I do when I want to compare the predictions from the model with the observations, I compare weighted survival curves in each class (so individual survival of the class weighted by the posterior probability) with a weighted non-parametric estimator. You can find an example in Figure 1D of this paper: https://journals.sagepub.com/doi/10.1177/0962280212445839

Finally, yes, you can use more than 1 longitudinal variable as in multlcmm in the new function mpjlcmm. 

I hope this helps
Cécile
