### ISSUE TITLE
Posterior class memberships estimated as zero for some classes when ng > 3

### ISSUE THREAD

**Issue by jbp7** [CecileProust-Lima/lcmm#79]
Using a growth mixture model (via hlme()), I successively go through the modeling process by increasing ng from 1 to 5 and using the ng=1 model to initialize the ng > 1 models, and I find that when ng > 3 the estimated posterior class membership probabilities are set to zero for everything but three classes. The %class for the top 3 classes in the ng=3 and ng=4 models are similar. In the ng=5 setting, I actually get 3 of the 5 classes to have estimated %class=0. I'm also setting each class to have the same random effect variance (nwg=FALSE). Are there particular situations where you have see this?

**Comment by CecileProust-Lima** [comment]
Hi, 
latent class models and mixture models may converge to local maxima. Those local maxima may correspond to the solution with a smaller number of latent classes, and in that case, some classes may include nobody. In thoses cases, you should have a log-likelihood that is the same in the two models (e.g., 3 and 4 in your example). 
Please look at the vignette "usual problems" on the cran to see how to deal with multimodality, or the companion paper in Journal of Statistical Software. 
Cécile

**Comment by jbp7** [comment]
Thanks!
