### ISSUE TITLE
Specifying nesting structure in lcmm

### ISSUE THREAD

**Issue by cooperr11** [CecileProust-Lima/lcmm#81]
Dear Cécile

I was wondering what the correct syntax is for nesting data in the lcmm package. I have a dataset sourced from multiple different sites. I would like to specify the grouping variable as subjects within each site. Is this possible to specify this in the lcmm package? For example, in the lmer package, the syntax would be:
model <- lmer(variable ~ age + (1|subject_id:site_id), data = data,  na.action = na.omit)
...where each individual is nested within each site. I'm assuming it would be something to do with the subject = ' ' argument in lcmm?

Kind regards,
Rebecca

**Comment by CecileProust-Lima** [comment]
Dear Rebecca, 
I am sorry, lcmm does not handle nested random effects yet. 
Cécile

**Comment by cooperr11** [comment]
Dear Cécile,
Thank you for getting back to me. No worries at all!
Kind regards,
Rebecca
