### ISSUE TITLE
Updating estimation based on significant polynomial factors

### ISSUE THREAD

**Issue by jbp7** [CecileProust-Lima/lcmm#82]
Suppose that I've run hlme on a given dataset for a specified number of classes, modeling time up to quadratic terms. However, if find that the quadratic term is not significant for a subset of those estimated classes, is it possible to "update" the estimation with only linear terms for those classes where the quadratic term was not significant, but keep both the linear and quadratic terms for which the quadratic terms are significant?

**Comment by CecileProust-Lima** [comment]
Hi, 
you could fix some the nonsignificant parameters to 0 and re-estimate the model while keeping them at 0. This is done by : 
- specifying a vector of parameters from your estimates, let say: binit <- m$best
- changing the values you want to 0, let say parameters 6 and 8: binit[c(6,8)] <- 0
- use this vector as initial values of the model to reestimate and fix the 6 and 8 parameters: B=binit, posfix=c(6,8)

**Comment by jbp7** [comment]
Great, thanks!
