### ISSUE TITLE
Question: specifying variance-covariance matrix

### ISSUE THREAD

**Issue by cooperr11** [CecileProust-Lima/lcmm#83]
Dear Cécile,

I have another question for you, apologies! I wanted to know whether the variance-covariance structure can be set/altered for hlme. I understand that currently the options are either unstructured (idiag=FALSE) or diagonal (idiag=TRUE). Are other options able to be set?

Kind regards,
Rebecca

**Comment by VivianePhilipps** [comment]
Hello,

sorry for the delay to reply.
There is no other possibility for the variance of the random effects, it is either unstructured or diagonal.

Best,

Viviane

**Comment by cooperr11** [comment]
Dear Viviane,

 

Thank you for your reply. No worries about the delay. 

 

Best,

 

Rebecca
