### ISSUE TITLE
Error Message: The program stopped abnormally

### ISSUE THREAD

**Issue by edwinadrianta** [CecileProust-Lima/lcmm#84]
I was running an analysis for Growth Mixture Model with the function 'hlme'. When I ran the analysis for 2 latent classes, I got this error message:

_Iteration process: 
     The program stopped abnormally. No results can be displayed._

Here is the statistical model:
Number of subjects: 135 
Number of observations: 32400 
Number of latent classes: 2 
Number of parameters: 20

Additional information:
mixture = ~time + imp
random = ~time + imp
rep = 100
maxiter = 10

model2 <- gridsearch(rep = 100, maxiter = 10, minit = model1,
                   hlme(y ~ x1+x2+x3+x4+x5+time+imp, subject = "code", random=~time+imp,
                        ng = 2, data = dat_csv, mixture = ~time+imp, nwg=T))

Is there anything that I can do to revise the model or to get the analysis to run?

**Comment by VivianePhilipps** [comment]
Hi,

there was some computational problem during estimation. It may sometimes happen, but if it happens every time you run the gridsearch, it may be something wrong with the initial model (model1). Did it converge properly?

Viviane

**Comment by edwinadrianta** [comment]
Hi Viviane,
Thanks for responding to my question. When I call the model with summary(model1), I get this output:

Iteration process: 
     Convergence criteria satisfied 
     Number of iterations:  57 
     Convergence criteria: parameters= 3.6e-06 
                         : likelihood= 3.1e-06 
                         : second derivatives= 5e-07 
 
Goodness-of-fit statistics: 
     maximum log-likelihood: -71644.67  
     AIC: 143319.34  
     BIC: 143362.92 

Followed with the parameter estimates. So I assume the initial model (model1) is working and converge properly.

**Comment by VivianePhilipps** [comment]
Yes, it does.

If you run 
 m2 <- hlme(y ~ x1+x2+x3+x4+x5+time+imp, subject = "code", random=~time+imp,
           ng = 2, data = dat_csv, mixture = ~time+imp, nwg=T, B=random(model1))
several times, you never get any results?

And with 
 m2 <- hlme(y ~ x1+x2+x3+x4+x5+time+imp, subject = "code", random=~time+imp,
           ng = 2, data = dat_csv, mixture = ~time+imp, nwg=T, B=model1)
neither?
