### ISSUE TITLE
Class-specific random effect extraction and average predictions across classes

### ISSUE THREAD

**Issue by elisseos1** [CecileProust-Lima/lcmm#85]
I am able to extract subject-specific Random Effects with the ranef(m) statement or the m$predRE list component, but how do I get class-specific  estimates of the random effects? The ones you report have been averaged over classes.

Also, when I average the ss predictions (pred_ss1,..pred_ss3) in m$pred by the class probabilities in m$pprob, I get the correct overall pred_ss value.  However, when I do the same with the marginal predictions (pred_m1,..,pred_m3),  I get a pred_m value other than the one reported by the package.

m$pprob[1,]
 id class                     prob1       prob2               prob3
1          2     9.440167e-02 0.8179141 8.768423e-02

m$pred[1:2,]
  id   pred_m      resid_m   pred_ss       resid_ss           obs    pred_m1  pred_m2  pred_m3 pred_ss1 pred_ss2 pred_ss3
  1 17.21078   0.1823456 18.23782 -0.8446898 17.39313  17.59396 17.18157 17.88759 18.30650 18.23454 18.19440
  1 18.50977  4.7236866 21.53821  1.6952457 23.23346  18.97162 18.46740 20.16880 21.59301 21.48392 21.98561

# check ID=1 results
prob<-c(9.440167e-02, 0.8179141, 8.768423e-02)
pss<-c(18.30650, 18.23454, 18.19440)
mss<-c(17.59396, 17.18157, 17.88759)
sum(pss*prob) #  18.23782 <- agrees with pred_ss above
sum(mss*prob) #  17.28241 <- does not agree with pred_m above

Thanks.

**Comment by VivianePhilipps** [comment]
Hello,

the subject-specific predictions are indeed averaged over the classes using the posterior probabilities given in m$pprob. These are the probabilities to belong to each class conditional to the observations (of the marker and of the time-ti-event, if one).
But the marginal predictions are weighted by the marginal probabilities to belong to each latent class, which are obtained by the class-membership submodel. They are not given in the output, but can be computed using the estimated parameters.

Viviane

**Comment by VivianePhilipps** [comment]
Yes, they differ according to the class. We do not compute the class-specific random effects, but you can use a tip to get them : 
 - create a variable "prior1" in your data, which has value 1 for all lines
 - call the estimation function again (the same as for model m)  with options : 
      prior="prior1", B=m$best, maxiter=0
- the $predRE you get are the predicted random effects for class 1
- do the same for the other classes (with prior2 for class 2, etc)

Here is an example :
`
## initial model with 2 latent classes
m <- hlme(Y~Time*X1,mixture=~Time,random=~Time,classmb=~X2+X3,subject='ID',
                 ng=2,data=data_hlme,B=c(0.11,-0.74,-0.07,20.71,29.39,-1,0.13,2.45,-0.29,4.5,0.36,0.79,0.9))

## RE for class 1
data_hlme$prior1 <- 1
m_class1 <- hlme(Y~Time*X1,mixture=~Time,random=~Time,classmb=~X2+X3,subject='ID',
                             ng=2,data=data_hlme,B=m$best, maxiter=0, prior="prior1")
head(m_class1$predRE) 

## RE for class 2
data_hlme$prior2 <- 2
m_class2 <- hlme(Y~Time*X1,mixture=~Time,random=~Time,classmb=~X2+X3,subject='ID',
                             ng=2,data=data_hlme,B=m$best, maxiter=0, prior="prior2")
head(m_class2$predRE) 
`

You can check that 
 m_class1$predRE[1, 2:3] * m$pprob[1, 3] + m_class2$predRE[1, 2:3] * m$pprob[1, 4] 
is the same as 
 m$predRE[1, ]


Viviane
