### ISSUE TITLE
Tibbles not accepted

### ISSUE THREAD

**Issue by sjacobson94** [CecileProust-Lima/lcmm#86]
A tibble is not accepted in the data parameter because of the subject check:

    if (!is.numeric(data[, subject])) 
        stop("The argument subject must be numeric")

> is.numeric(as_tibble(data_lcmm)[, "ID"])
[1] FALSE
> is.numeric(as_tibble(data_lcmm)$ID)
[1] TRUE

A tibble indexed this way returns a 1-column tibble instead of a vector.

Please either fix this or put a warning/note in the documentation.

Thanks!

**Comment by VivianePhilipps** [comment]
Hello,

this bug was fixed and the correction is available in the last CRAN version (lcmm_1.9.3) and also in the master branch of the github version.
If you are using another version, please convert your tibble into a data frame using the as.data.frame function.

Best,

Viviane
