### ISSUE TITLE
how to get the classification outcome of each individual?

### ISSUE THREAD

**Issue by ConnieXuhm** [CecileProust-Lima/lcmm#87]
Dear developer,
 I am honored to use lcmm() for classification. My code is as follows.
```
m8<-lcmm(SEVERE~time+AGE+SEX,random=~time,mixture=~time,ng=3,idiag=TRUE,data=cov,link="splines",subject="work.ID")
```
I have three questions for this.
1. My purpose is to classify my sample into 3 group to conduct further analyses, so how can I know the classification outcome of each individual?
2. When using plot(), I want to check the profile of three classified group, while I found the y-lim is ranging from c(-1.5,1.5) , not the real Y-lim (0-9 ) that I expected. Therefore, I want to know how can I achieve this?
3. The outcome of lcmm() shows the "time" term in variance matrix of random effect is 0.0000, is that matters?

So much thank you for your help!

**Comment by VivianePhilipps** [comment]
Hello,

the classification is given in m8$pprob. This is a matrix with as many rows as individuals giving the posterior probabilities in each class and the derived classification.

The plot function with which="fit" indeed represents the predictions and observations in the latent process scale. This is used to assess the model's fit. If you are interested in the estimated trajectories in the natural scale of the outcome, you can use the predictY function, which gives the marginal predictions in each class according to a profile of covariates.

For your last point, if the model converges properly with a small parameter, this should not be a problem. 

Hope this helps,

Viviane
