### ISSUE TITLE
lcmm "crashing"  with non numeric subject

### ISSUE THREAD

**Issue by JoeBlair** [CecileProust-Lima/lcmm#9]
HI Cecilie,

Im not sure if you are the right person to contact :) 

I have notice a small bug in the LCMM package. If you do not cast the subject variable to numeric, my code will stall, and requires me to reboot R in order to continue. 

Perhaps it could automatically flag a warning? or break immediately?

Otherwise I am very much enjoying the package!

**Comment by CecileProust-Lima** [comment]
Thank you for reporting this bug. We always work with numeric IDs and did not check the use of non numeric IDs. 
We will address this problem for next releases. 
Cécile
