### ISSUE TITLE
ns() not working for hlme

### ISSUE THREAD

**Issue by AAzuero** [CecileProust-Lima/lcmm#90]
Hi, I created a simulated data set (attached) 

[all_groups.xlsx](https://github.com/CecileProust-Lima/lcmm/files/6963857/all_groups.xlsx)

with some linear trajectories and a nonlinear trajectory (12 observations per subject, 100 subjects per trajectory):
![all_groups](https://user-images.githubusercontent.com/12257047/128913785-e7a26a6d-bd3d-456a-98f7-c0a8b2ee1e1c.jpg)

With hlme, for a single class model (or more classes), I am unable to fit a simple spline effect (even with just 1 knot) as either a fixed or a random effect.

It works just fine with lmer, for instance:

`library(lme4); library(lmerTest)`
`library(splines)`
`timeknots1 <- quantile(all_groups$time, p = c(0.5))`
`summary( lmer(outcome ~ ns(time,knots=timeknots1) + (1|subject),data = all_groups) )`

fits the model with no problems, an even with a non-linear spline as random effect:
`summary(lmer(outcome ~ ns(time,knots=timeknots1) + (1+ns(time,knots=timeknots1)|subject),data = all_groups) )`
or even without fixed effect:
`summary(lmer(outcome ~ 1 + (1+ns(time,knots=timeknots1)|subject),data = all_groups) )`

I was checking previous issues related to fitting splines, #28 and #67 and it was suggested to specify the boundary knots:
`minmax=c(min(all_groups$time),max(all_groups$time))`
In lmer works again:
`summary( lmer(outcome ~ ns(time,knots=timeknots1,Boundary.knots=minmax)+`
`                (1+ns(time,knots=timeknots1,Boundary.knots=minmax)|subject),`
`                 data = all_groups) )` 

With hlme, a single-class model with linear fixed and random effects runs without issues:
`library(lcmm)`
`m1a <- hlme(outcome ~ time,random =~ time, subject = 'subject', data = all_groups)`
`summary(m1a)`
Or even a model with a quadratic effect:
`m1a.poly2 <- hlme(outcome ~ poly(time,2),random =~poly(time,2), subject = 'subject', data = all_groups)`
`summary(m1a.poly2)`

However, none of the calls below work, even with the specification of the boundary knots:
`m1a.1kn1 <- hlme(outcome ~ ns(time,knots=timeknots1,Boundary.knots=minmax),random =~1, subject = 'subject', data = all_groups)`
`#summary(m1a.1kn) `
`m1a.1kn2 <- hlme(outcome ~ ns(time,knots=timeknots1,Boundary.knots=minmax),random =~time, subject = 'subject', data = all_groups)`
`#summary(m1a.1kn2)` 
`m1a.1kn3 <- hlme(outcome ~ ns(time,knots=timeknots1,Boundary.knots=minmax),`
`                 random =~ns(time,knots=timeknots1,Boundary.knots=minmax), subject = 'subject', data = all_groups)`
`#summary(m1a.1kn3)`

The error message is:

Error in `[.data.frame`(data, , v) : undefined columns selected
In addition: Warning message:
In (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  :
  row names were found from a short variable and have been discarded

I'm using R 4.1.0
lcmm version 1.9.3
Any guidance would be appreciated. Thank you,
Andres

**Comment by CecileProust-Lima** [comment]
Hi,

thank you for your feedback. I did some rapid checks, and indeed, on your dataset, it seems there is a problem with how hlme reads the data within ns function. 
I had never experienced this problem before and checked that the same code was working with other data (for instance those of the package): 

`lmH <- hlme(IST ~ ns(age,knots=80),random=~ 1, subject="ID",data = paquid)`

There is no problem, the code works. So I really believe this comes from how the data frame is created. I tried a few things without success to understand what went wrong for you.

Anyway, the basic solution that always works (even though somewhat more tedious) is to create the variables you want externally to the hlme function as follows:

```
Z <- ns(all_groups$time,knots=timeknots1)
all_groups$Z1 <- Z[,1]
all_groups$Z2 <- Z[,2]
lmH_Z1Z2 <- hlme(outcome ~ Z1 + Z2 ,random=~ 1, subject="subject",data = all_groups)
lmH_Z1Z2_RE <- hlme(outcome ~ Z1 + Z2 ,random=~ 1+Z1 + Z2 , subject="subject",data = all_groups)
```
This works and could help you go through rapidly to what you wanted to do. 

However, I would like to understand what happened. Could you send the code that you used to create the data please?

By the way, this is a different issue from those previously reported (#28 and #67). They were about how to make predictions when using ns, not how to estimate the models.

Again, thanks for reporting this issue.
Cécile

**Comment by CecileProust-Lima** [comment]
Thanks for sharing this bug. Indeed, ns seems to work only when you specify the value directly in the ns call: 
```
# works:
m1a.1knD <- hlme(outcome ~ ns(time,knots= 6.439816),random =~1, subject = 'subject', data = all_groups)

# does not work:
knots <- c(6.439816)
m1a.1kn <- hlme(outcome ~ ns(time,knots= knots),random =~1, subject = 'subject', data = all_groups)
```
We will fix that for next release.
Cécile
