### ISSUE TITLE
The Lo–Mendell–Rubin likelihood ratio test  

### ISSUE THREAD

**Issue by amberntsson** [CecileProust-Lima/lcmm#92]
Is it possible to use/import the The Lo–Mendell–Rubin likelihood ratio test when using the lcmm-package? This test has been proposed as an important part in the model selection process 1, but I have not been able to figure out how to run this test after I´ve modeled the selected number of classes. 
Thank you. 

1. Muthén, B. (2003). Statistical and substantive checking in growth mixture modeling: Comment on bauer and curran (2003). Psychological Methods, 8(3), 369-377. doi:http://dx.doi.org.ezproxy.ub.gu.se/10.1037/1082-989X.8.3.369

**Comment by CecileProust-Lima** [comment]
Hi, 
I chose not to implement this test in the package. I prefer using a set of other criteria that equivalently assess the goodness-of-fit and/or discriminative power : BIC (or Size Adjusted BIC), ICL, Entropy and for joint models the score test of conditional independence (all are available in the summarytable function). I also assess the quality of classification with the posterior classification table (postprob function). 
Cécile
