### ISSUE TITLE
Error Message:     object 'C_jointhet' not found?

### ISSUE THREAD

**Issue by hundes** [CecileProust-Lima/lcmm#97]
Dear VivianePhilipps,
Thank you again for your assistance. When I run the jlcm() function using lcmm package
it released the following error. Please what is the reason behind this error?
library(lcmm)

 mj1 <- Jointlcmm(CD4 ~ Age+Education + Sex,random =~ obstime, survival = Surv(Tevent, status) ~ Education + Sex,
    hazard = "Weibull", subject = 'ID', data = full_data, ng = 1)
    Be patient, Jointlcmm is running ...
    Error in Jointlcmm(CD4 ~ Age + Education + Sex, random = ~obstime, survival = Surv(Tevent, :
    object 'C_jointhet' not found"
    Thank You
    Hunde

**Comment by VivianePhilipps** [comment]
Hello Hunde,

this happens when you extract the function from the package. If you have a "Jointlcmm" function in your environment (when you run the ls() command), remove it so that R uses the package's function.

Best,

Viviane
