### ISSUE TITLE
Applying lcmm() to count data

### ISSUE THREAD

**Issue by yamachua2020** [CecileProust-Lima/lcmm#98]
Dear Dr. Proust-Lima and lcmm-team,

Thank you for creating this wonderful package.

I'm interested in the relationship about the longitudinal smart-phone use pattern and demographic or psychological variables. So, I consider setting total number of times the smartphone is activated per week (n=294, 19 weeks) as the dependent variable.  

I'm afraid a very rudimentary question but, is it ok to apply lcmm() function to the count data outcome?
If not, how about  average of that insetad of total number?

According to the reference manual, lcmm() accommodate discrete outcome. However, I saw that the lcmm doesn't handle count data, elsewhere.
I'm very confused.

Kind regards,
Atsushi

**Comment by CecileProust-Lima** [comment]
Dear Atsushi, 
lcmm and multlcmm function handle different types of data:
- ordinal data using cumulative probit model
- continuous data using linear models for Gaussian variables and curvilinear models for non-Gaussian data. 
These implementations may be used for discrete data. However, we did not specifically implement Poisson model for count data. 
I hope this helps. 
Cécile
